const en = ["Memory Desk", "Personal memory", "Cross-book memory", "Books", "Chapter graph", "Book memory", "Search", "Refresh", "No memories found", "Memory is unavailable at this reading position", "No visible chapter digest", "No chapter memory yet", "Entity names", "Chapter number", "Enter one to eight names, or a positive chapter number", "Open source", "Chapters", "Relations", "No matching entities", "Results limited", "Previous", "Next", "Query", "Chapter"] as const;
const locales: Record<string, readonly string[]> = {
  en,
  "zh-Hans": ["记忆台", "个人记忆", "跨书记忆", "书籍", "章节图谱", "本书记忆", "搜索", "刷新", "没有匹配的记忆", "当前阅读位置无法提供记忆", "没有可见的章节摘要", "尚无章节记忆", "实体名称", "章节号", "请输入一至八个名称，或正整数章节号", "打开原文", "章节", "关系", "没有匹配的实体", "结果已截断", "上一页", "下一页", "查询", "章节"],
  "zh-Hant": ["記憶台", "個人記憶", "跨書記憶", "書籍", "章節圖譜", "本書記憶", "搜尋", "重新整理", "沒有符合的記憶", "目前閱讀位置無法提供記憶", "沒有可見的章節摘要", "尚無章節記憶", "實體名稱", "章節號", "請輸入一至八個名稱，或正整數章節號", "開啟原文", "章節", "關係", "沒有符合的實體", "結果已截斷", "上一頁", "下一頁", "查詢", "章節"],
  ja: ["記憶デスク", "個人の記憶", "書籍横断の記憶", "書籍", "章グラフ", "本の記憶", "検索", "更新", "記憶が見つかりません", "現在の読書位置では記憶を表示できません", "表示可能な章要約がありません", "章の記憶はまだありません", "エンティティ名", "章番号", "1〜8件の名前、または正の章番号を入力してください", "原文を開く", "章", "関係", "一致するエンティティはありません", "結果は制限されています", "前へ", "次へ", "クエリ", "章"],
  de: ["Gedächtnis", "Persönliche Erinnerungen", "Buchübergreifende Erinnerungen", "Bücher", "Kapitelgraph", "Bucherinnerungen", "Suchen", "Aktualisieren", "Keine Erinnerungen gefunden", "An dieser Leseposition nicht verfügbar", "Keine sichtbare Kapitelzusammenfassung", "Noch keine Kapitelerinnerungen", "Entitätsnamen", "Kapitelnummer", "Ein bis acht Namen oder eine positive Kapitelnummer eingeben", "Quelle öffnen", "Kapitel", "Beziehungen", "Keine passenden Entitäten", "Ergebnisse begrenzt", "Zurück", "Weiter", "Suchbegriff", "Kapitel"],
  fr: ["Mémoire", "Souvenirs personnels", "Souvenirs interlivres", "Livres", "Graphe des chapitres", "Mémoire du livre", "Rechercher", "Actualiser", "Aucun souvenir trouvé", "Mémoire indisponible à cette position de lecture", "Aucun résumé de chapitre visible", "Aucune mémoire de chapitre", "Noms des entités", "Numéro du chapitre", "Saisissez un à huit noms ou un numéro de chapitre positif", "Ouvrir la source", "Chapitres", "Relations", "Aucune entité correspondante", "Résultats limités", "Précédent", "Suivant", "Recherche", "Chapitre"],
  es: ["Memoria", "Recuerdos personales", "Recuerdos entre libros", "Libros", "Grafo de capítulos", "Memoria del libro", "Buscar", "Actualizar", "No hay recuerdos", "Memoria no disponible en esta posición de lectura", "No hay resumen de capítulo visible", "Aún no hay memoria de capítulos", "Nombres de entidades", "Número de capítulo", "Introduce de uno a ocho nombres o un número de capítulo positivo", "Abrir fuente", "Capítulos", "Relaciones", "No hay entidades coincidentes", "Resultados limitados", "Anterior", "Siguiente", "Consulta", "Capítulo"],
  ru: ["Память", "Личные воспоминания", "Межкнижные воспоминания", "Книги", "Граф глав", "Память книги", "Поиск", "Обновить", "Воспоминания не найдены", "Память недоступна на этой позиции чтения", "Нет доступного резюме главы", "Памяти глав пока нет", "Имена сущностей", "Номер главы", "Введите от одного до восьми имён или положительный номер главы", "Открыть источник", "Главы", "Связи", "Сущности не найдены", "Результаты ограничены", "Назад", "Далее", "Запрос", "Глава"],
};
export const strings = (locale: string) => locales[locale] ?? locales[locale.split("-")[0]] ?? en;
