type Copy = { limit: string; invalid: string; note: string; reached: string; boundary: string; toc: string; classification: string; empty: string; chapter: string };
const copies: Record<string, Copy> = {
  en: { limit: "Maximum chapter attempts", invalid: "Enter a whole number from 1 to 1000", note: "Empty and failed chapters count. Classification may add a model request; this is not a token or spending limit.", reached: "Chapter limit reached", boundary: "Reading boundary is unknown", toc: "No chapter directory is available", classification: "Book classification is still pending", empty: "Empty chapters", chapter: "Chapter" },
  "zh-Hans": { limit: "最多尝试章节数", invalid: "请输入 1 到 1000 的整数", note: "空章和失败章节也计入。分类可能额外调用模型；这不是 token 或费用上限。", reached: "已达章节上限", boundary: "尚无法确定阅读边界", toc: "没有可用的章节目录", classification: "书籍分类尚未完成", empty: "空章节", chapter: "章节" },
  "zh-Hant": { limit: "最多嘗試章節數", invalid: "請輸入 1 到 1000 的整數", note: "空章與失敗章節也計入。分類可能額外呼叫模型；這不是 token 或費用上限。", reached: "已達章節上限", boundary: "尚無法確定閱讀邊界", toc: "沒有可用的章節目錄", classification: "書籍分類尚未完成", empty: "空章節", chapter: "章節" },
  ja: { limit: "章の試行数の上限", invalid: "1 から 1000 の整数を入力してください", note: "空の章や失敗した章も数えます。分類で追加のモデル呼び出しが発生する場合があります。トークン数や料金の上限ではありません。", reached: "章の上限に達しました", boundary: "読書範囲が不明です", toc: "章の目次がありません", classification: "書籍の分類は未完了です", empty: "空の章", chapter: "章" },
  de: { limit: "Maximale Kapitelversuche", invalid: "Ganze Zahl von 1 bis 1000 eingeben", note: "Leere und fehlgeschlagene Kapitel zählen. Die Klassifizierung kann einen weiteren Modellaufruf benötigen; kein Token- oder Kostenlimit.", reached: "Kapitellimit erreicht", boundary: "Lesegrenze unbekannt", toc: "Kein Kapitelverzeichnis verfügbar", classification: "Buchklassifizierung noch ausstehend", empty: "Leere Kapitel", chapter: "Kapitel" },
  fr: { limit: "Nombre maximal de tentatives", invalid: "Saisissez un entier de 1 à 1000", note: "Les chapitres vides ou en échec comptent. La classification peut ajouter un appel au modèle ; aucune limite de jetons ou de dépenses.", reached: "Limite de chapitres atteinte", boundary: "Limite de lecture inconnue", toc: "Aucun sommaire disponible", classification: "Classification du livre en attente", empty: "Chapitres vides", chapter: "Chapitre" },
  es: { limit: "Máximo de intentos de capítulos", invalid: "Introduce un entero de 1 a 1000", note: "Cuentan los capítulos vacíos o fallidos. La clasificación puede añadir una llamada al modelo; no es un límite de tokens ni de gasto.", reached: "Límite de capítulos alcanzado", boundary: "Límite de lectura desconocido", toc: "No hay índice de capítulos", classification: "Clasificación del libro pendiente", empty: "Capítulos vacíos", chapter: "Capítulo" },
  ru: { limit: "Максимум попыток обработки глав", invalid: "Введите целое число от 1 до 1000", note: "Пустые и неудачные главы учитываются. Классификация может добавить запрос к модели; это не лимит токенов или расходов.", reached: "Достигнут лимит глав", boundary: "Граница чтения неизвестна", toc: "Оглавление недоступно", classification: "Классификация книги ещё не завершена", empty: "Пустые главы", chapter: "Глава" },
};
export const taskBudgetWords = (locale: string) => copies[locale] ?? copies[locale.split("-")[0]] ?? copies.en!;
