import { expect, test } from "bun:test";
import { getPDFMetadata } from "../foliate-js/src/pdf-metadata.js";
import { makePDFTOCItem, resolvePDFHref } from "../foliate-js/src/pdf-navigation.js";
import { makePDFFixture } from "./fixtures/foliate-pdf.js";
import type { PDFDocument } from "../foliate-js/src/vendor/pdfjs/pdf.mjs";

test("PDF metadata validates third-party values without losing titles or authors", () => {
  const values: Record<string, unknown> = { "dc:title": { en: "Title", zh: "标题" },
    "dc:creator": ["First", "Second"], "dc:language": ["en"], "dc:subject": ["reading"] };
  const result = getPDFMetadata({ get: name => values[name] }, { Title: "Fallback", Author: "Fallback author" });
  expect(result.title).toEqual(values["dc:title"]);
  expect(result.author).toEqual(["First", "Second"]);
  expect(result.language).toEqual(["en"]);
  const invalid = getPDFMetadata({ get: () => ({ malformed: 3 }) }, { Title: "Valid", Author: "Writer" });
  expect(invalid.title).toBe("Valid");
  expect(invalid.author).toBe("Writer");
  expect(invalid.language).toBeUndefined();
});

test("PDF navigation accepts named, reference and numeric destinations", async () => {
  const pdf: Pick<PDFDocument, "numPages" | "getPageIndex" | "getDestination"> = {
    numPages: 3, getPageIndex: async ref => ref.num - 10,
    getDestination: async name => name === "final" ? [{ num: 12, gen: 0 }, { name: "Fit" }] : null,
  };
  expect(await resolvePDFHref(pdf, '"final"')).toEqual({ index: 2 });
  expect(await resolvePDFHref(pdf, '[{"num":11,"gen":0},{"name":"Fit"}]')).toEqual({ index: 1 });
  expect(await resolvePDFHref(pdf, '[0,{"name":"Fit"}]')).toEqual({ index: 0 });
  for (const href of ['"missing"', "null", "[]", "[99]", "[-1]", '[{"num":"10","gen":0}]'])
    expect(await resolvePDFHref(pdf, href)).toBeUndefined();
  expect(makePDFTOCItem({ title: "External", dest: null, url: "https://example.org", items: [] }).href)
    .toBe("https://example.org");
});

test("PDF fixture is generated by a real PDF writer and is deterministic", async () => {
  const [a, b] = await Promise.all([makePDFFixture(), makePDFFixture()]);
  expect(a).toEqual(b);
  expect(new TextDecoder().decode(a.slice(0, 5))).toBe("%PDF-");
});
