/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgentLabRouteImport } from './routes/agent-lab'
import { Route as IndexRouteImport } from './routes/index'

const AgentLabRoute = AgentLabRouteImport.update({
  id: '/agent-lab',
  path: '/agent-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-lab': typeof AgentLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-lab': typeof AgentLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-lab': typeof AgentLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent-lab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent-lab'
  id: '__root__' | '/' | '/agent-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentLabRoute: typeof AgentLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agent-lab': {
      id: '/agent-lab'
      path: '/agent-lab'
      fullPath: '/agent-lab'
      preLoaderRoute: typeof AgentLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentLabRoute: AgentLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
