const en = { title: "Reading trends", period: "Period", week: "Last 7 days", month: "Last 30 days", year: "Last 365 days", all: "All time",
  open: "Show trends", total: "Reading time", days: "Active days", books: "Books read", average: "Per active day", change: "Change", none: "Not available",
  dates: "Date totals", hours: "Reading hours (all time)", achievements: "Milestones (all time)", streak: "Current streak", longest: "Longest streak",
  best: "Best day", next: "Next milestone", reference: "Reference day", refresh: "Refresh" };
type Copy = typeof en;
const copies: Record<string, Copy> = {
  en,
  "zh-Hans": { title: "阅读趋势", period: "时间范围", week: "最近 7 天", month: "最近 30 天", year: "最近 365 天", all: "全部时间", open: "查看趋势", total: "阅读时长", days: "活跃天数", books: "阅读书数", average: "每活跃日", change: "变化", none: "暂无", dates: "按日期汇总", hours: "阅读时段（全部时间）", achievements: "里程碑（全部时间）", streak: "当前连续天数", longest: "最长连续天数", best: "最佳阅读日", next: "下一里程碑", reference: "参考日期", refresh: "刷新" },
  "zh-Hant": { title: "閱讀趨勢", period: "時間範圍", week: "最近 7 天", month: "最近 30 天", year: "最近 365 天", all: "全部時間", open: "查看趨勢", total: "閱讀時間", days: "活躍天數", books: "閱讀書數", average: "每活躍日", change: "變化", none: "暫無", dates: "按日期彙總", hours: "閱讀時段（全部時間）", achievements: "里程碑（全部時間）", streak: "目前連續天數", longest: "最長連續天數", best: "最佳閱讀日", next: "下一里程碑", reference: "參考日期", refresh: "重新整理" },
  ja: { title: "読書傾向", period: "期間", week: "過去7日", month: "過去30日", year: "過去365日", all: "全期間", open: "傾向を表示", total: "読書時間", days: "読書日数", books: "読んだ本", average: "読書日あたり", change: "変化", none: "なし", dates: "日付別合計", hours: "読書時間帯（全期間）", achievements: "到達点（全期間）", streak: "現在の連続日数", longest: "最長連続日数", best: "最も読んだ日", next: "次の到達点", reference: "基準日", refresh: "更新" },
  de: { title: "Lesetrends", period: "Zeitraum", week: "Letzte 7 Tage", month: "Letzte 30 Tage", year: "Letzte 365 Tage", all: "Gesamte Zeit", open: "Trends anzeigen", total: "Lesezeit", days: "Aktive Tage", books: "Gelesene Bücher", average: "Pro aktivem Tag", change: "Änderung", none: "Nicht verfügbar", dates: "Datumssummen", hours: "Lesezeiten (gesamt)", achievements: "Meilensteine (gesamt)", streak: "Aktuelle Serie", longest: "Längste Serie", best: "Bester Tag", next: "Nächster Meilenstein", reference: "Referenztag", refresh: "Aktualisieren" },
  fr: { title: "Tendances de lecture", period: "Période", week: "7 derniers jours", month: "30 derniers jours", year: "365 derniers jours", all: "Toute la période", open: "Voir les tendances", total: "Temps de lecture", days: "Jours actifs", books: "Livres lus", average: "Par jour actif", change: "Évolution", none: "Indisponible", dates: "Totaux par date", hours: "Heures de lecture (total)", achievements: "Jalons (total)", streak: "Série actuelle", longest: "Plus longue série", best: "Meilleur jour", next: "Prochain jalon", reference: "Jour de référence", refresh: "Actualiser" },
  es: { title: "Tendencias de lectura", period: "Período", week: "Últimos 7 días", month: "Últimos 30 días", year: "Últimos 365 días", all: "Todo el tiempo", open: "Ver tendencias", total: "Tiempo de lectura", days: "Días activos", books: "Libros leídos", average: "Por día activo", change: "Cambio", none: "No disponible", dates: "Totales por fecha", hours: "Horas de lectura (total)", achievements: "Hitos (total)", streak: "Racha actual", longest: "Mayor racha", best: "Mejor día", next: "Próximo hito", reference: "Día de referencia", refresh: "Actualizar" },
  ru: { title: "Тенденции чтения", period: "Период", week: "Последние 7 дней", month: "Последние 30 дней", year: "Последние 365 дней", all: "Всё время", open: "Показать тенденции", total: "Время чтения", days: "Активные дни", books: "Книг прочитано", average: "За активный день", change: "Изменение", none: "Нет данных", dates: "Итоги по датам", hours: "Часы чтения (всё время)", achievements: "Рубежи (всё время)", streak: "Текущая серия", longest: "Лучшая серия", best: "Лучший день", next: "Следующий рубеж", reference: "Опорная дата", refresh: "Обновить" },
};
export function insightsCopy(locale: string): Copy { return copies[locale] ?? copies[locale.split("-")[0]] ?? en; }
