import type { ReadingAiAction } from "@read-aware/core";

const prompts: Record<string, Record<ReadingAiAction, string>> = {
  en: { explainSelection: "Explain the selected passage in plain language, using its context and distinguishing ambiguity from fact.", defineTerm: "Define the selected word or phrase as used in this passage, including its meaning in context.", translate: "Translate the selected passage into English, preserving its meaning and tone.", summarizeChapter: "Summarize chapter {{chapter}} of this book. Read the chapter itself, not just the visible page. Give its key points without spoilers from later chapters." },
  "zh-Hans": { explainSelection: "请结合上下文，用通俗语言解释所选段落，并区分确定含义与可能的理解。", defineTerm: "请解释所选词语在这段文字中的含义和用法。", translate: "请将所选段落翻译成简体中文，保留原意和语气。", summarizeChapter: "请总结本书第 {{chapter}} 章，阅读全文而不只是当前可见页面，概括要点，不剧透后续章节。" },
  "zh-Hant": { explainSelection: "請結合上下文，用淺白語言解釋所選段落，並區分確定含義與可能的理解。", defineTerm: "請解釋所選詞語在這段文字中的含義和用法。", translate: "請將所選段落翻譯成繁體中文，保留原意和語氣。", summarizeChapter: "請總結本書第 {{chapter}} 章，閱讀全文而不只是目前可見頁面，概括要點，不劇透後續章節。" },
  ja: { explainSelection: "選択した文章を文脈に沿ってわかりやすく説明し、確かな意味と解釈の可能性を区別してください。", defineTerm: "選択した語句の、この文章での意味と用法を説明してください。", translate: "選択した文章を、意味と語調を保って日本語に翻訳してください。", summarizeChapter: "この本の第{{chapter}}章を、表示中のページだけでなく章全体を読んで要約してください。後の章のネタバレは避けてください。" },
  de: { explainSelection: "Erkläre die ausgewählte Passage verständlich im Kontext und unterscheide sichere Aussagen von möglichen Deutungen.", defineTerm: "Definiere das ausgewählte Wort oder die Wendung in ihrem Kontext.", translate: "Übersetze die ausgewählte Passage ins Deutsche und bewahre Bedeutung und Ton.", summarizeChapter: "Fasse Kapitel {{chapter}} dieses Buches zusammen. Lies das ganze Kapitel, nicht nur die sichtbare Seite. Nenne die Kernaussagen ohne Spoiler zu späteren Kapiteln." },
  es: { explainSelection: "Explica el pasaje seleccionado con claridad y en su contexto, distinguiendo los hechos de las posibles interpretaciones.", defineTerm: "Define la palabra o expresión seleccionada según su significado en este contexto.", translate: "Traduce el pasaje seleccionado al español, conservando su significado y tono.", summarizeChapter: "Resume el capítulo {{chapter}} de este libro. Lee el capítulo entero, no solo la página visible. Expón los puntos clave sin revelar capítulos posteriores." },
  fr: { explainSelection: "Explique le passage sélectionné simplement et dans son contexte, en distinguant les faits des interprétations possibles.", defineTerm: "Définis le mot ou l'expression sélectionné selon son sens dans ce contexte.", translate: "Traduis le passage sélectionné en français, en préservant son sens et son ton.", summarizeChapter: "Résume le chapitre {{chapter}} de ce livre. Lis le chapitre entier, pas seulement la page visible. Présente ses points clés sans révéler les chapitres suivants." },
  ru: { explainSelection: "Объясни выделенный отрывок простыми словами с учётом контекста, отделяя факты от возможных толкований.", defineTerm: "Объясни значение выделенного слова или выражения в данном контексте.", translate: "Переведи выделенный отрывок на русский язык, сохранив смысл и тон.", summarizeChapter: "Подведи итог главы {{chapter}} этой книги. Прочитай всю главу, а не только видимую страницу. Выдели главное без спойлеров к следующим главам." },
};

export function readingAiPrompt(locale: string, action: ReadingAiAction, chapterIndex?: number) {
  const language = prompts[locale] ? locale : locale.startsWith("zh") ? locale.includes("Hant") || locale.includes("TW") ? "zh-Hant" : "zh-Hans" : locale.split("-")[0]!;
  return (prompts[language] ?? prompts.en)![action].replace("{{chapter}}", String((chapterIndex ?? 0) + 1));
}
