const locales = ["en", "zh-Hans", "zh-Hant", "ja", "ru", "fr", "de", "es"];
const labels = {
  imageControls: ["Image controls", "图片控制", "圖片控制", "画像操作", "Управление изображением", "Commandes de l'image", "Bildsteuerung", "Controles de imagen"],
  noOpenImage: ["No image viewer open", "尚未打开图片查看器", "尚未開啟圖片檢視器", "画像ビューアは開いていません", "Просмотр изображения не открыт", "Aucune visionneuse ouverte", "Kein Bildbetrachter geöffnet", "No hay un visor de imágenes abierto"],
  zoomIn: ["Zoom in", "放大", "放大", "拡大", "Увеличить", "Agrandir", "Vergrößern", "Acercar"],
  zoomOut: ["Zoom out", "缩小", "縮小", "縮小", "Уменьшить", "Réduire", "Verkleinern", "Alejar"],
  rotateImage: ["Rotate", "旋转", "旋轉", "回転", "Повернуть", "Pivoter", "Drehen", "Girar"],
  resetImage: ["Reset image", "复位图片", "重設圖片", "画像をリセット", "Сбросить изображение", "Réinitialiser l'image", "Bild zurücksetzen", "Restablecer imagen"],
  panLeft: ["Pan left", "向左平移", "向左平移", "左に移動", "Сдвинуть влево", "Déplacer à gauche", "Nach links verschieben", "Mover a la izquierda"],
  panRight: ["Pan right", "向右平移", "向右平移", "右に移動", "Сдвинуть вправо", "Déplacer à droite", "Nach rechts verschieben", "Mover a la derecha"],
  panUp: ["Pan up", "向上平移", "向上平移", "上に移動", "Сдвинуть вверх", "Déplacer vers le haut", "Nach oben verschieben", "Mover hacia arriba"],
  panDown: ["Pan down", "向下平移", "向下平移", "下に移動", "Сдвинуть вниз", "Déplacer vers le bas", "Nach unten verschieben", "Mover hacia abajo"],
  showImage: ["Show image", "查看图片", "檢視圖片", "画像を表示", "Показать изображение", "Afficher l'image", "Bild anzeigen", "Mostrar imagen"],
  closeImage: ["Close image", "关闭图片", "關閉圖片", "画像を閉じる", "Закрыть изображение", "Fermer l'image", "Bild schließen", "Cerrar imagen"],
  imageUpdated: ["Image updated", "图片已更新", "圖片已更新", "画像を更新しました", "Изображение обновлено", "Image mise à jour", "Bild aktualisiert", "Imagen actualizada"],
  imageScale: ["Zoom", "缩放", "縮放", "倍率", "Масштаб", "Zoom", "Zoom", "Zoom"],
  imageRotation: ["Rotation", "旋转角度", "旋轉角度", "回転角度", "Поворот", "Rotation", "Drehung", "Rotación"],
  imagePanX: ["Horizontal offset", "水平偏移", "水平位移", "水平オフセット", "Смещение по горизонтали", "Décalage horizontal", "Horizontaler Versatz", "Desplazamiento horizontal"],
  imagePanY: ["Vertical offset", "垂直偏移", "垂直位移", "垂直オフセット", "Смещение по вертикали", "Décalage vertical", "Vertikaler Versatz", "Desplazamiento vertical"],
  references: ["Notes and links", "脚注与链接", "註腳與連結", "注釈とリンク", "Примечания и ссылки", "Notes et liens", "Anmerkungen und Links", "Notas y enlaces"],
  reference: ["Reference", "引用", "引用", "参照", "Ссылка", "Référence", "Verweis", "Referencia"],
  images: ["Book images", "书内图片", "書內圖片", "書籍の画像", "Иллюстрации книги", "Images du livre", "Buchbilder", "Imágenes del libro"],
  image: ["Image", "图片", "圖片", "画像", "Изображение", "Image", "Bild", "Imagen"],
  noSections: ["No source sections", "没有源文件分节", "沒有來源分節", "元のセクションなし", "Нет разделов источника", "Aucune section source", "Keine Quellabschnitte", "Sin secciones de origen"],
  noReferences: ["No notes or links in this section", "本节没有脚注或链接", "本節沒有註腳或連結", "このセクションに注釈やリンクはありません", "В разделе нет примечаний или ссылок", "Aucune note ni aucun lien dans cette section", "Keine Anmerkungen oder Links in diesem Abschnitt", "Sin notas ni enlaces en esta sección"],
  noImages: ["No images in this section", "本节没有图片", "本節沒有圖片", "このセクションに画像はありません", "В разделе нет изображений", "Aucune image dans cette section", "Keine Bilder in diesem Abschnitt", "Sin imágenes en esta sección"],
  reference_resolved: ["Internal reference", "书内引用", "書內引用", "書籍内の参照", "Внутренняя ссылка", "Référence interne", "Interner Verweis", "Referencia interna"],
  reference_external: ["External link", "外部链接", "外部連結", "外部リンク", "Внешняя ссылка", "Lien externe", "Externer Link", "Enlace externo"],
  reference_blocked: ["Blocked link", "已阻止的链接", "已封鎖的連結", "ブロックされたリンク", "Заблокированная ссылка", "Lien bloqué", "Blockierter Link", "Enlace bloqueado"],
  reference_missing: ["Reference target not found", "找不到引用目标", "找不到引用目標", "参照先が見つかりません", "Цель ссылки не найдена", "Cible de référence introuvable", "Verweisziel nicht gefunden", "Destino de referencia no encontrado"],
  reference_unsupported: ["Unsupported reference", "不支持的引用", "不支援的引用", "非対応の参照", "Неподдерживаемая ссылка", "Référence non prise en charge", "Nicht unterstützter Verweis", "Referencia no compatible"],
  image_missing: ["Image not found", "找不到图片", "找不到圖片", "画像が見つかりません", "Изображение не найдено", "Image introuvable", "Bild nicht gefunden", "Imagen no encontrada"],
  image_external: ["Remote image not loaded", "未加载远程图片", "未載入遠端圖片", "リモート画像は未読込", "Удалённое изображение не загружено", "Image distante non chargée", "Externes Bild nicht geladen", "Imagen remota no cargada"],
  image_unsupported: ["Unsupported image", "不支持的图片", "不支援的圖片", "非対応の画像", "Неподдерживаемое изображение", "Image non prise en charge", "Nicht unterstütztes Bild", "Imagen no compatible"],
  nativeReference: ["Show reader note", "在阅读器预览脚注", "在閱讀器預覽註腳", "リーダーで注釈を表示", "Показать примечание в читалке", "Afficher la note dans le lecteur", "Anmerkung im Reader anzeigen", "Mostrar nota en el lector"],
  nativeImage: ["Open image viewer", "打开图片查看器", "開啟圖片檢視器", "画像ビューアを開く", "Открыть просмотр изображения", "Ouvrir la visionneuse", "Bildbetrachter öffnen", "Abrir visor de imágenes"],
  copyImage: ["Copy image", "复制图片", "複製圖片", "画像をコピー", "Копировать изображение", "Copier l'image", "Bild kopieren", "Copiar imagen"],
  saveImage: ["Save image", "保存图片", "儲存圖片", "画像を保存", "Сохранить изображение", "Enregistrer l'image", "Bild speichern", "Guardar imagen"],
  imageCopied: ["Image copied", "图片已复制", "圖片已複製", "画像をコピーしました", "Изображение скопировано", "Image copiée", "Bild kopiert", "Imagen copiada"],
  imageSaved: ["Image saved", "图片已保存", "圖片已儲存", "画像を保存しました", "Изображение сохранено", "Image enregistrée", "Bild gespeichert", "Imagen guardada"],
  searching: ["Searching", "搜索中", "搜尋中", "検索中", "Поиск", "Recherche en cours", "Suche läuft", "Buscando"],
  searchCancelled: ["Search cancelled", "搜索已取消", "搜尋已取消", "検索をキャンセルしました", "Поиск отменён", "Recherche annulée", "Suche abgebrochen", "Búsqueda cancelada"],
  temporaryMarks: ["Temporary marks", "临时标记", "暫時標記", "一時マーク", "Временные отметки", "Marques temporaires", "Temporäre Markierungen", "Marcas temporales"],
  noTemporaryMarks: ["No temporary marks", "没有临时标记", "沒有暫時標記", "一時マークなし", "Нет временных отметок", "Aucune marque temporaire", "Keine temporären Markierungen", "Sin marcas temporales"],
  markResults: ["Mark these results", "标记本批结果", "標記這批結果", "この結果をマーク", "Отметить эти результаты", "Marquer ces résultats", "Diese Treffer markieren", "Marcar estos resultados"],
  highlightMarks: ["Temporary highlight", "临时强调", "暫時強調", "一時ハイライト", "Временная подсветка", "Surlignage temporaire", "Temporär hervorheben", "Resaltado temporal"],
  underlineMarks: ["Temporary underline", "临时下划线", "暫時底線", "一時下線", "Временное подчёркивание", "Soulignement temporaire", "Temporär unterstreichen", "Subrayado temporal"],
  removeMarks: ["Remove marks", "移除标记", "移除標記", "マークを削除", "Удалить отметки", "Retirer les marques", "Markierungen entfernen", "Quitar marcas"],
  attachedPassages: ["Attached passages", "已呈现文档内的段落", "已呈現文件內的段落", "描画文書内の文章", "Отрывки в отображаемом документе", "Passages du document affiché", "Textstellen im gerenderten Dokument", "Pasajes del documento mostrado"],
  emphasis_attached: ["Attached", "已附着", "已附加", "配置済み", "Прикреплено", "Attaché", "Angefügt", "Adjunto"],
  emphasis_deferred: ["Awaiting document", "等待文档呈现", "等待文件呈現", "文書の描画待ち", "Ожидание документа", "En attente du document", "Warten auf Dokument", "Esperando documento"],
  emphasis_partial: ["Partially attached", "部分已附着", "部分已附加", "一部配置済み", "Частично прикреплено", "Partiellement attaché", "Teilweise angefügt", "Adjunto parcialmente"],
  emphasis_error: ["Mark could not be rendered", "无法呈现标记", "無法呈現標記", "マークを描画できません", "Не удалось отобразить отметку", "Impossible d’afficher la marque", "Markierung konnte nicht dargestellt werden", "No se pudo mostrar la marca"],
  selectPassage: ["Select passage", "选中段落", "選取段落", "文章を選択", "Выделить отрывок", "Sélectionner le passage", "Textstelle auswählen", "Seleccionar pasaje"],
  clearSelection: ["Clear selection", "清除选区", "清除選取", "選択を解除", "Снять выделение", "Effacer la sélection", "Auswahl aufheben", "Quitar selección"],
  inspectPassage: ["Inspect passage", "查看段落", "檢視段落", "文章を確認", "Просмотреть отрывок", "Examiner le passage", "Textstelle prüfen", "Examinar pasaje"],
  inspectSelection: ["Current selection", "当前选区", "目前選取範圍", "現在の選択", "Текущее выделение", "Sélection actuelle", "Aktuelle Auswahl", "Selección actual"],
  noSourceRange: ["No versioned passage is available", "没有可用的版本化段落", "沒有可用的版本化段落", "バージョン付きの文章はありません", "Нет доступного версионированного отрывка", "Aucun passage versionné disponible", "Keine versionierte Textstelle verfügbar", "No hay un pasaje versionado disponible"],
  findPassage: ["Find a passage", "查找段落", "尋找段落", "文章を探す", "Найти отрывок", "Trouver un passage", "Textstelle finden", "Buscar un pasaje"],
  passage: ["Passage", "段落", "段落", "文章", "Отрывок", "Passage", "Textstelle", "Pasaje"],
  sourceSection: ["Source section", "源文件分节", "來源分節", "元のセクション", "Раздел источника", "Section source", "Quellabschnitt", "Sección de origen"],
  openPassage: ["Open passage", "跳转到段落", "跳至段落", "文章を開く", "Открыть отрывок", "Ouvrir le passage", "Textstelle öffnen", "Abrir pasaje"],
  matchCase: ["Match case", "区分大小写", "區分大小寫", "大文字と小文字を区別", "Учитывать регистр", "Respecter la casse", "Groß-/Kleinschreibung beachten", "Distinguir mayúsculas"],
  wholeWords: ["Whole words", "全词匹配", "全詞比對", "単語単位", "Слова целиком", "Mots entiers", "Ganze Wörter", "Palabras completas"],
  invalidPassage: ["Enter 1-500 characters", "请输入 1–500 个字符", "請輸入 1–500 個字元", "1〜500文字で入力してください", "Введите 1–500 символов", "Saisissez 1 à 500 caractères", "1–500 Zeichen eingeben", "Introduzca de 1 a 500 caracteres"],
  searchPending: ["No matches in this batch", "本批次没有匹配", "本批次沒有符合項目", "この範囲に一致なし", "В этой порции совпадений нет", "Aucun résultat dans ce lot", "Keine Treffer in diesem Abschnitt", "Sin coincidencias en este lote"],
  noPassageMatches: ["No matching passage", "没有匹配的段落", "沒有符合的段落", "一致する文章なし", "Отрывок не найден", "Aucun passage correspondant", "Keine passende Textstelle", "Ningún pasaje coincide"],
  search: ["Search", "搜索", "搜尋", "検索", "Поиск", "Rechercher", "Suchen", "Buscar"],
  searchBook: ["Search this book", "搜索本书", "搜尋本書", "この本を検索", "Поиск в книге", "Rechercher dans ce livre", "Dieses Buch durchsuchen", "Buscar en este libro"],
  searchShelf: ["Search indexed books", "搜索已索引书籍", "搜尋已索引書籍", "索引済みの本を検索", "Поиск в индексированных книгах", "Rechercher dans les livres indexés", "Indizierte Bücher durchsuchen", "Buscar en libros indexados"],
  variants: ["Queries (one per line)", "查询词（每行一个）", "查詢詞（每行一個）", "検索語（1行に1つ）", "Запросы (по одному в строке)", "Requêtes (une par ligne)", "Suchanfragen (eine pro Zeile)", "Consultas (una por línea)"],
  invalidQueries: ["Enter 1-12 queries, up to 1024 characters each", "请输入 1–12 个查询词，每个不超过 1024 字符", "請輸入 1–12 個查詢詞，每個不超過 1024 字元", "1〜12件、各1024文字以内で入力してください", "Введите 1–12 запросов, до 1024 символов каждый", "Saisissez 1 à 12 requêtes de 1024 caractères maximum", "1–12 Suchanfragen mit jeweils bis zu 1024 Zeichen eingeben", "Introduzca de 1 a 12 consultas de hasta 1024 caracteres"],
  searchResults: ["Text matches", "正文匹配", "正文比對", "本文の一致", "Совпадения в тексте", "Correspondances", "Texttreffer", "Coincidencias de texto"],
  noMatches: ["No matches in the searched index", "已搜索索引中没有匹配", "已搜尋索引中沒有符合項目", "検索した索引に一致なし", "В просмотренном индексе нет совпадений", "Aucune correspondance dans l'index consulté", "Keine Treffer im durchsuchten Index", "Sin coincidencias en el índice consultado"],
  exactMatch: ["Exact", "精确匹配", "精確比對", "完全一致", "Точное", "Exacte", "Exakt", "Exacta"],
  partialMatch: ["Partial", "词元匹配", "詞元比對", "部分一致", "Частичное", "Partielle", "Teiltreffer", "Parcial"],
  observedState: ["Last text state", "最近正文状态", "最近正文狀態", "直近の本文状態", "Последнее состояние текста", "Dernier état du texte", "Letzter Textstatus", "Último estado del texto"],
  failure: ["Failure", "失败原因", "失敗原因", "失敗理由", "Причина сбоя", "Échec", "Fehler", "Error"],
  busy: ["Another preparation is running", "已有正文准备任务正在进行", "已有正文準備工作正在進行", "別の本文準備が実行中です", "Другая подготовка текста уже идёт", "Une autre préparation est en cours", "Eine andere Textaufbereitung läuft", "Otra preparación está en curso"],
  request: ["Request", "请求状态", "請求狀態", "リクエスト", "Запрос", "Demande", "Anfrage", "Solicitud"],
  requests: ["My requests", "我的请求", "我的請求", "自分のリクエスト", "Мои запросы", "Mes demandes", "Meine Anfragen", "Mis solicitudes"],
  noRequests: ["No requests in this plugin session", "本次插件会话尚无请求", "本次外掛工作階段尚無請求", "このプラグインセッションにリクエストはありません", "В этой сессии плагина нет запросов", "Aucune demande dans cette session du plugin", "Keine Anfragen in dieser Plugin-Sitzung", "Sin solicitudes en esta sesión del complemento"],
  mode: ["Operation", "操作", "操作", "操作", "Операция", "Opération", "Vorgang", "Operación"],
  prepare: ["Prepare text", "准备正文", "準備正文", "本文を準備", "Подготовить текст", "Préparer le texte", "Text aufbereiten", "Preparar texto"],
  rebuild: ["Rebuild index", "重建索引", "重建索引", "索引を再構築", "Перестроить индекс", "Reconstruire l'index", "Index neu aufbauen", "Reconstruir índice"],
  cancelRequest: ["Cancel this request", "取消此请求", "取消此請求", "このリクエストをキャンセル", "Отменить этот запрос", "Annuler cette demande", "Diese Anfrage abbrechen", "Cancelar esta solicitud"],
  confirmRebuild: ["Discard the derived index and extract the source again", "清除派生索引并重新抽取源文件", "清除衍生索引並重新擷取來源檔案", "派生索引を削除して元ファイルから再抽出する", "Удалить производный индекс и извлечь текст заново", "Supprimer l'index dérivé et extraire à nouveau la source", "Abgeleiteten Index verwerfen und Quelle erneut auslesen", "Descartar el índice derivado y extraer de nuevo la fuente"],
  confirmRequired: ["Confirm rebuilding first", "请先确认重建", "請先確認重建", "再構築を確認してください", "Подтвердите перестроение", "Confirmez la reconstruction", "Neuaufbau zuerst bestätigen", "Confirme primero la reconstrucción"],
  task_queued: ["Queued", "已排队", "已排入佇列", "待機中", "В очереди", "En attente", "In Warteschlange", "En cola"],
  task_running: ["Running", "进行中", "進行中", "実行中", "Выполняется", "En cours", "Läuft", "En curso"],
  task_completed: ["Completed", "已完成", "已完成", "完了", "Завершён", "Terminée", "Abgeschlossen", "Completada"],
  task_failed: ["Failed", "已失败", "已失敗", "失敗", "Ошибка", "Échec", "Fehlgeschlagen", "Fallida"],
  task_cancelled: ["Request cancelled", "请求已取消", "請求已取消", "リクエストをキャンセル済み", "Запрос отменён", "Demande annulée", "Anfrage abgebrochen", "Solicitud cancelada"],
  title: ["Text Desk", "正文台", "正文台", "本文一覧", "Текст книг", "Textes des livres", "Buchtexte", "Textos de libros"],
  refresh: ["Refresh", "刷新", "重新整理", "更新", "Обновить", "Actualiser", "Aktualisieren", "Actualizar"],
  open: ["Open book", "打开书籍", "開啟書籍", "本を開く", "Открыть книгу", "Ouvrir le livre", "Buch öffnen", "Abrir libro"],
  previous: ["Previous", "上一页", "上一頁", "前へ", "Назад", "Précédent", "Zurück", "Anterior"],
  next: ["Next", "下一页", "下一頁", "次へ", "Далее", "Suivant", "Weiter", "Siguiente"],
  empty: ["No books", "没有书籍", "沒有書籍", "本がありません", "Нет книг", "Aucun livre", "Keine Bücher", "Sin libros"],
  status: ["Preparation", "准备状态", "準備狀態", "準備状態", "Подготовка", "Préparation", "Vorbereitung", "Preparación"],
  unprepared: ["Not prepared", "尚未准备", "尚未準備", "未準備", "Не подготовлен", "Non préparé", "Nicht vorbereitet", "Sin preparar"],
  preparing: ["Preparing", "准备中", "準備中", "準備中", "Подготовка", "En préparation", "In Vorbereitung", "Preparando"],
  ready: ["Prepared", "已准备", "已準備", "準備済み", "Подготовлен", "Prêt", "Vorbereitet", "Preparado"],
  partial: ["Incomplete", "未完成", "未完成", "未完了", "Не завершено", "Incomplet", "Unvollständig", "Incompleto"],
  unsupported: ["Unsupported", "不支持", "不支援", "非対応", "Не поддерживается", "Non pris en charge", "Nicht unterstützt", "No compatible"],
  unavailable: ["Source unavailable", "源文件不可用", "來源檔案無法使用", "元ファイルなし", "Источник недоступен", "Source indisponible", "Quelle nicht verfügbar", "Fuente no disponible"],
  error: ["Preparation failed", "准备失败", "準備失敗", "準備失敗", "Ошибка подготовки", "Échec de préparation", "Vorbereitung fehlgeschlagen", "Error de preparación"],
  queryError: ["Status could not be loaded", "无法读取状态", "無法讀取狀態", "状態を取得できません", "Не удалось загрузить состояние", "État indisponible", "Status konnte nicht geladen werden", "No se pudo cargar el estado"],
  text: ["Text layer", "文本层", "文字層", "テキスト層", "Текстовый слой", "Couche de texte", "Textebene", "Capa de texto"],
  unknown: ["Unknown", "未知", "未知", "不明", "Неизвестно", "Inconnu", "Unbekannt", "Desconocido"],
  available: ["Text found", "有文本", "有文字", "テキストあり", "Текст найден", "Texte trouvé", "Text vorhanden", "Texto disponible"],
  textless: ["No extractable text", "无可抽取文本", "無可擷取文字", "抽出可能な文字なし", "Нет извлекаемого текста", "Aucun texte extractible", "Kein extrahierbarer Text", "Sin texto extraíble"],
  chapters: ["Indexed chapters", "已索引章节", "已索引章節", "索引済みの章", "Глав в индексе", "Chapitres indexés", "Indizierte Kapitel", "Capítulos indexados"],
  sections: ["Read sections", "已读取分节", "已讀取分節", "読取済みセクション", "Прочитанные разделы", "Sections lues", "Gelesene Abschnitte", "Secciones leídas"],
  failed: ["Failed sections", "失败分节", "失敗分節", "失敗したセクション", "Сбои разделов", "Sections en échec", "Fehlgeschlagene Abschnitte", "Secciones fallidas"],
  unsupportedSections: ["Unsupported sections", "不支持的分节", "不支援的分節", "非対応セクション", "Неподдерживаемые разделы", "Sections non prises en charge", "Nicht unterstützte Abschnitte", "Secciones no compatibles"],
} satisfies Record<string, string[]>;
export function tr(locale: string, key: keyof typeof labels): string { return labels[key][Math.max(0, locales.indexOf(locale))]!; }
