/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OpenSourceEbookReaderRouteImport } from './routes/open-source-ebook-reader'
import { Route as EpubReaderForWindowsRouteImport } from './routes/epub-reader-for-windows'
import { Route as EpubReaderForAndroidRouteImport } from './routes/epub-reader-for-android'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CbzCbrReaderRouteImport } from './routes/cbz-cbr-reader'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZhIndexRouteImport } from './routes/zh/index'
import { Route as ZhHantIndexRouteImport } from './routes/zh-hant/index'
import { Route as RuIndexRouteImport } from './routes/ru/index'
import { Route as JaIndexRouteImport } from './routes/ja/index'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as EsIndexRouteImport } from './routes/es/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DeIndexRouteImport } from './routes/de/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ZhPricingRouteImport } from './routes/zh/pricing'
import { Route as ZhDocsRouteImport } from './routes/zh/docs'
import { Route as ZhChangelogRouteImport } from './routes/zh/changelog'
import { Route as ZhBlogRouteImport } from './routes/zh/blog'
import { Route as ZhHantPricingRouteImport } from './routes/zh-hant/pricing'
import { Route as ZhHantChangelogRouteImport } from './routes/zh-hant/changelog'
import { Route as RuPricingRouteImport } from './routes/ru/pricing'
import { Route as RuChangelogRouteImport } from './routes/ru/changelog'
import { Route as JaPricingRouteImport } from './routes/ja/pricing'
import { Route as JaDocsRouteImport } from './routes/ja/docs'
import { Route as JaChangelogRouteImport } from './routes/ja/changelog'
import { Route as JaBlogRouteImport } from './routes/ja/blog'
import { Route as FrPricingRouteImport } from './routes/fr/pricing'
import { Route as FrChangelogRouteImport } from './routes/fr/changelog'
import { Route as EsPricingRouteImport } from './routes/es/pricing'
import { Route as EsChangelogRouteImport } from './routes/es/changelog'
import { Route as DocsInstallRouteImport } from './routes/docs/install'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DePricingRouteImport } from './routes/de/pricing'
import { Route as DeChangelogRouteImport } from './routes/de/changelog'
import { Route as BlogReadingThatRemembersRouteImport } from './routes/blog/reading-that-remembers'
import { Route as BlogPluginsV1RouteImport } from './routes/blog/plugins-v1'
import { Route as BlogLocalFirstRouteImport } from './routes/blog/local-first'
import { Route as ZhDocsIndexRouteImport } from './routes/zh/docs/index'
import { Route as ZhBlogIndexRouteImport } from './routes/zh/blog/index'
import { Route as JaDocsIndexRouteImport } from './routes/ja/docs/index'
import { Route as JaBlogIndexRouteImport } from './routes/ja/blog/index'
import { Route as DocsPluginsIndexRouteImport } from './routes/docs/plugins/index'
import { Route as ZhDocsInstallRouteImport } from './routes/zh/docs/install'
import { Route as ZhDocsGettingStartedRouteImport } from './routes/zh/docs/getting-started'
import { Route as ZhBlogReadingThatRemembersRouteImport } from './routes/zh/blog/reading-that-remembers'
import { Route as ZhBlogPluginsV1RouteImport } from './routes/zh/blog/plugins-v1'
import { Route as ZhBlogLocalFirstRouteImport } from './routes/zh/blog/local-first'
import { Route as JaDocsInstallRouteImport } from './routes/ja/docs/install'
import { Route as JaDocsGettingStartedRouteImport } from './routes/ja/docs/getting-started'
import { Route as JaBlogReadingThatRemembersRouteImport } from './routes/ja/blog/reading-that-remembers'
import { Route as JaBlogPluginsV1RouteImport } from './routes/ja/blog/plugins-v1'
import { Route as JaBlogLocalFirstRouteImport } from './routes/ja/blog/local-first'
import { Route as DocsPluginsPublishingRouteImport } from './routes/docs/plugins/publishing'
import { Route as DocsPluginsApiRouteImport } from './routes/docs/plugins/api'
import { Route as ZhDocsPluginsIndexRouteImport } from './routes/zh/docs/plugins/index'
import { Route as JaDocsPluginsIndexRouteImport } from './routes/ja/docs/plugins/index'
import { Route as ZhDocsPluginsPublishingRouteImport } from './routes/zh/docs/plugins/publishing'
import { Route as ZhDocsPluginsApiRouteImport } from './routes/zh/docs/plugins/api'
import { Route as JaDocsPluginsPublishingRouteImport } from './routes/ja/docs/plugins/publishing'
import { Route as JaDocsPluginsApiRouteImport } from './routes/ja/docs/plugins/api'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceEbookReaderRoute = OpenSourceEbookReaderRouteImport.update({
  id: '/open-source-ebook-reader',
  path: '/open-source-ebook-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const EpubReaderForWindowsRoute = EpubReaderForWindowsRouteImport.update({
  id: '/epub-reader-for-windows',
  path: '/epub-reader-for-windows',
  getParentRoute: () => rootRouteImport,
} as any)
const EpubReaderForAndroidRoute = EpubReaderForAndroidRouteImport.update({
  id: '/epub-reader-for-android',
  path: '/epub-reader-for-android',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CbzCbrReaderRoute = CbzCbrReaderRouteImport.update({
  id: '/cbz-cbr-reader',
  path: '/cbz-cbr-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/zh/',
  path: '/zh/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantIndexRoute = ZhHantIndexRouteImport.update({
  id: '/zh-hant/',
  path: '/zh-hant/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuIndexRoute = RuIndexRouteImport.update({
  id: '/ru/',
  path: '/ru/',
  getParentRoute: () => rootRouteImport,
} as any)
const JaIndexRoute = JaIndexRouteImport.update({
  id: '/ja/',
  path: '/ja/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DeIndexRoute = DeIndexRouteImport.update({
  id: '/de/',
  path: '/de/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ZhPricingRoute = ZhPricingRouteImport.update({
  id: '/zh/pricing',
  path: '/zh/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhDocsRoute = ZhDocsRouteImport.update({
  id: '/zh/docs',
  path: '/zh/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhChangelogRoute = ZhChangelogRouteImport.update({
  id: '/zh/changelog',
  path: '/zh/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhBlogRoute = ZhBlogRouteImport.update({
  id: '/zh/blog',
  path: '/zh/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantPricingRoute = ZhHantPricingRouteImport.update({
  id: '/zh-hant/pricing',
  path: '/zh-hant/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantChangelogRoute = ZhHantChangelogRouteImport.update({
  id: '/zh-hant/changelog',
  path: '/zh-hant/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const RuPricingRoute = RuPricingRouteImport.update({
  id: '/ru/pricing',
  path: '/ru/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RuChangelogRoute = RuChangelogRouteImport.update({
  id: '/ru/changelog',
  path: '/ru/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const JaPricingRoute = JaPricingRouteImport.update({
  id: '/ja/pricing',
  path: '/ja/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const JaDocsRoute = JaDocsRouteImport.update({
  id: '/ja/docs',
  path: '/ja/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const JaChangelogRoute = JaChangelogRouteImport.update({
  id: '/ja/changelog',
  path: '/ja/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const JaBlogRoute = JaBlogRouteImport.update({
  id: '/ja/blog',
  path: '/ja/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const FrPricingRoute = FrPricingRouteImport.update({
  id: '/fr/pricing',
  path: '/fr/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FrChangelogRoute = FrChangelogRouteImport.update({
  id: '/fr/changelog',
  path: '/fr/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const EsPricingRoute = EsPricingRouteImport.update({
  id: '/es/pricing',
  path: '/es/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EsChangelogRoute = EsChangelogRouteImport.update({
  id: '/es/changelog',
  path: '/es/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallRoute = DocsInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DePricingRoute = DePricingRouteImport.update({
  id: '/de/pricing',
  path: '/de/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DeChangelogRoute = DeChangelogRouteImport.update({
  id: '/de/changelog',
  path: '/de/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogReadingThatRemembersRoute =
  BlogReadingThatRemembersRouteImport.update({
    id: '/reading-that-remembers',
    path: '/reading-that-remembers',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogPluginsV1Route = BlogPluginsV1RouteImport.update({
  id: '/plugins-v1',
  path: '/plugins-v1',
  getParentRoute: () => BlogRoute,
} as any)
const BlogLocalFirstRoute = BlogLocalFirstRouteImport.update({
  id: '/local-first',
  path: '/local-first',
  getParentRoute: () => BlogRoute,
} as any)
const ZhDocsIndexRoute = ZhDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZhDocsRoute,
} as any)
const ZhBlogIndexRoute = ZhBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZhBlogRoute,
} as any)
const JaDocsIndexRoute = JaDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JaDocsRoute,
} as any)
const JaBlogIndexRoute = JaBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JaBlogRoute,
} as any)
const DocsPluginsIndexRoute = DocsPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => DocsRoute,
} as any)
const ZhDocsInstallRoute = ZhDocsInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => ZhDocsRoute,
} as any)
const ZhDocsGettingStartedRoute = ZhDocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => ZhDocsRoute,
} as any)
const ZhBlogReadingThatRemembersRoute =
  ZhBlogReadingThatRemembersRouteImport.update({
    id: '/reading-that-remembers',
    path: '/reading-that-remembers',
    getParentRoute: () => ZhBlogRoute,
  } as any)
const ZhBlogPluginsV1Route = ZhBlogPluginsV1RouteImport.update({
  id: '/plugins-v1',
  path: '/plugins-v1',
  getParentRoute: () => ZhBlogRoute,
} as any)
const ZhBlogLocalFirstRoute = ZhBlogLocalFirstRouteImport.update({
  id: '/local-first',
  path: '/local-first',
  getParentRoute: () => ZhBlogRoute,
} as any)
const JaDocsInstallRoute = JaDocsInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => JaDocsRoute,
} as any)
const JaDocsGettingStartedRoute = JaDocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => JaDocsRoute,
} as any)
const JaBlogReadingThatRemembersRoute =
  JaBlogReadingThatRemembersRouteImport.update({
    id: '/reading-that-remembers',
    path: '/reading-that-remembers',
    getParentRoute: () => JaBlogRoute,
  } as any)
const JaBlogPluginsV1Route = JaBlogPluginsV1RouteImport.update({
  id: '/plugins-v1',
  path: '/plugins-v1',
  getParentRoute: () => JaBlogRoute,
} as any)
const JaBlogLocalFirstRoute = JaBlogLocalFirstRouteImport.update({
  id: '/local-first',
  path: '/local-first',
  getParentRoute: () => JaBlogRoute,
} as any)
const DocsPluginsPublishingRoute = DocsPluginsPublishingRouteImport.update({
  id: '/plugins/publishing',
  path: '/plugins/publishing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPluginsApiRoute = DocsPluginsApiRouteImport.update({
  id: '/plugins/api',
  path: '/plugins/api',
  getParentRoute: () => DocsRoute,
} as any)
const ZhDocsPluginsIndexRoute = ZhDocsPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => ZhDocsRoute,
} as any)
const JaDocsPluginsIndexRoute = JaDocsPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => JaDocsRoute,
} as any)
const ZhDocsPluginsPublishingRoute = ZhDocsPluginsPublishingRouteImport.update({
  id: '/plugins/publishing',
  path: '/plugins/publishing',
  getParentRoute: () => ZhDocsRoute,
} as any)
const ZhDocsPluginsApiRoute = ZhDocsPluginsApiRouteImport.update({
  id: '/plugins/api',
  path: '/plugins/api',
  getParentRoute: () => ZhDocsRoute,
} as any)
const JaDocsPluginsPublishingRoute = JaDocsPluginsPublishingRouteImport.update({
  id: '/plugins/publishing',
  path: '/plugins/publishing',
  getParentRoute: () => JaDocsRoute,
} as any)
const JaDocsPluginsApiRoute = JaDocsPluginsApiRouteImport.update({
  id: '/plugins/api',
  path: '/plugins/api',
  getParentRoute: () => JaDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/cbz-cbr-reader': typeof CbzCbrReaderRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/epub-reader-for-android': typeof EpubReaderForAndroidRoute
  '/epub-reader-for-windows': typeof EpubReaderForWindowsRoute
  '/open-source-ebook-reader': typeof OpenSourceEbookReaderRoute
  '/pricing': typeof PricingRoute
  '/blog/local-first': typeof BlogLocalFirstRoute
  '/blog/plugins-v1': typeof BlogPluginsV1Route
  '/blog/reading-that-remembers': typeof BlogReadingThatRemembersRoute
  '/de/changelog': typeof DeChangelogRoute
  '/de/pricing': typeof DePricingRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/install': typeof DocsInstallRoute
  '/es/changelog': typeof EsChangelogRoute
  '/es/pricing': typeof EsPricingRoute
  '/fr/changelog': typeof FrChangelogRoute
  '/fr/pricing': typeof FrPricingRoute
  '/ja/blog': typeof JaBlogRouteWithChildren
  '/ja/changelog': typeof JaChangelogRoute
  '/ja/docs': typeof JaDocsRouteWithChildren
  '/ja/pricing': typeof JaPricingRoute
  '/ru/changelog': typeof RuChangelogRoute
  '/ru/pricing': typeof RuPricingRoute
  '/zh-hant/changelog': typeof ZhHantChangelogRoute
  '/zh-hant/pricing': typeof ZhHantPricingRoute
  '/zh/blog': typeof ZhBlogRouteWithChildren
  '/zh/changelog': typeof ZhChangelogRoute
  '/zh/docs': typeof ZhDocsRouteWithChildren
  '/zh/pricing': typeof ZhPricingRoute
  '/blog/': typeof BlogIndexRoute
  '/de/': typeof DeIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/es/': typeof EsIndexRoute
  '/fr/': typeof FrIndexRoute
  '/ja/': typeof JaIndexRoute
  '/ru/': typeof RuIndexRoute
  '/zh-hant/': typeof ZhHantIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/docs/plugins/api': typeof DocsPluginsApiRoute
  '/docs/plugins/publishing': typeof DocsPluginsPublishingRoute
  '/ja/blog/local-first': typeof JaBlogLocalFirstRoute
  '/ja/blog/plugins-v1': typeof JaBlogPluginsV1Route
  '/ja/blog/reading-that-remembers': typeof JaBlogReadingThatRemembersRoute
  '/ja/docs/getting-started': typeof JaDocsGettingStartedRoute
  '/ja/docs/install': typeof JaDocsInstallRoute
  '/zh/blog/local-first': typeof ZhBlogLocalFirstRoute
  '/zh/blog/plugins-v1': typeof ZhBlogPluginsV1Route
  '/zh/blog/reading-that-remembers': typeof ZhBlogReadingThatRemembersRoute
  '/zh/docs/getting-started': typeof ZhDocsGettingStartedRoute
  '/zh/docs/install': typeof ZhDocsInstallRoute
  '/docs/plugins/': typeof DocsPluginsIndexRoute
  '/ja/blog/': typeof JaBlogIndexRoute
  '/ja/docs/': typeof JaDocsIndexRoute
  '/zh/blog/': typeof ZhBlogIndexRoute
  '/zh/docs/': typeof ZhDocsIndexRoute
  '/ja/docs/plugins/api': typeof JaDocsPluginsApiRoute
  '/ja/docs/plugins/publishing': typeof JaDocsPluginsPublishingRoute
  '/zh/docs/plugins/api': typeof ZhDocsPluginsApiRoute
  '/zh/docs/plugins/publishing': typeof ZhDocsPluginsPublishingRoute
  '/ja/docs/plugins/': typeof JaDocsPluginsIndexRoute
  '/zh/docs/plugins/': typeof ZhDocsPluginsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cbz-cbr-reader': typeof CbzCbrReaderRoute
  '/changelog': typeof ChangelogRoute
  '/epub-reader-for-android': typeof EpubReaderForAndroidRoute
  '/epub-reader-for-windows': typeof EpubReaderForWindowsRoute
  '/open-source-ebook-reader': typeof OpenSourceEbookReaderRoute
  '/pricing': typeof PricingRoute
  '/blog/local-first': typeof BlogLocalFirstRoute
  '/blog/plugins-v1': typeof BlogPluginsV1Route
  '/blog/reading-that-remembers': typeof BlogReadingThatRemembersRoute
  '/de/changelog': typeof DeChangelogRoute
  '/de/pricing': typeof DePricingRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/install': typeof DocsInstallRoute
  '/es/changelog': typeof EsChangelogRoute
  '/es/pricing': typeof EsPricingRoute
  '/fr/changelog': typeof FrChangelogRoute
  '/fr/pricing': typeof FrPricingRoute
  '/ja/changelog': typeof JaChangelogRoute
  '/ja/pricing': typeof JaPricingRoute
  '/ru/changelog': typeof RuChangelogRoute
  '/ru/pricing': typeof RuPricingRoute
  '/zh-hant/changelog': typeof ZhHantChangelogRoute
  '/zh-hant/pricing': typeof ZhHantPricingRoute
  '/zh/changelog': typeof ZhChangelogRoute
  '/zh/pricing': typeof ZhPricingRoute
  '/blog': typeof BlogIndexRoute
  '/de': typeof DeIndexRoute
  '/docs': typeof DocsIndexRoute
  '/es': typeof EsIndexRoute
  '/fr': typeof FrIndexRoute
  '/ja': typeof JaIndexRoute
  '/ru': typeof RuIndexRoute
  '/zh-hant': typeof ZhHantIndexRoute
  '/zh': typeof ZhIndexRoute
  '/docs/plugins/api': typeof DocsPluginsApiRoute
  '/docs/plugins/publishing': typeof DocsPluginsPublishingRoute
  '/ja/blog/local-first': typeof JaBlogLocalFirstRoute
  '/ja/blog/plugins-v1': typeof JaBlogPluginsV1Route
  '/ja/blog/reading-that-remembers': typeof JaBlogReadingThatRemembersRoute
  '/ja/docs/getting-started': typeof JaDocsGettingStartedRoute
  '/ja/docs/install': typeof JaDocsInstallRoute
  '/zh/blog/local-first': typeof ZhBlogLocalFirstRoute
  '/zh/blog/plugins-v1': typeof ZhBlogPluginsV1Route
  '/zh/blog/reading-that-remembers': typeof ZhBlogReadingThatRemembersRoute
  '/zh/docs/getting-started': typeof ZhDocsGettingStartedRoute
  '/zh/docs/install': typeof ZhDocsInstallRoute
  '/docs/plugins': typeof DocsPluginsIndexRoute
  '/ja/blog': typeof JaBlogIndexRoute
  '/ja/docs': typeof JaDocsIndexRoute
  '/zh/blog': typeof ZhBlogIndexRoute
  '/zh/docs': typeof ZhDocsIndexRoute
  '/ja/docs/plugins/api': typeof JaDocsPluginsApiRoute
  '/ja/docs/plugins/publishing': typeof JaDocsPluginsPublishingRoute
  '/zh/docs/plugins/api': typeof ZhDocsPluginsApiRoute
  '/zh/docs/plugins/publishing': typeof ZhDocsPluginsPublishingRoute
  '/ja/docs/plugins': typeof JaDocsPluginsIndexRoute
  '/zh/docs/plugins': typeof ZhDocsPluginsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/cbz-cbr-reader': typeof CbzCbrReaderRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/epub-reader-for-android': typeof EpubReaderForAndroidRoute
  '/epub-reader-for-windows': typeof EpubReaderForWindowsRoute
  '/open-source-ebook-reader': typeof OpenSourceEbookReaderRoute
  '/pricing': typeof PricingRoute
  '/blog/local-first': typeof BlogLocalFirstRoute
  '/blog/plugins-v1': typeof BlogPluginsV1Route
  '/blog/reading-that-remembers': typeof BlogReadingThatRemembersRoute
  '/de/changelog': typeof DeChangelogRoute
  '/de/pricing': typeof DePricingRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/install': typeof DocsInstallRoute
  '/es/changelog': typeof EsChangelogRoute
  '/es/pricing': typeof EsPricingRoute
  '/fr/changelog': typeof FrChangelogRoute
  '/fr/pricing': typeof FrPricingRoute
  '/ja/blog': typeof JaBlogRouteWithChildren
  '/ja/changelog': typeof JaChangelogRoute
  '/ja/docs': typeof JaDocsRouteWithChildren
  '/ja/pricing': typeof JaPricingRoute
  '/ru/changelog': typeof RuChangelogRoute
  '/ru/pricing': typeof RuPricingRoute
  '/zh-hant/changelog': typeof ZhHantChangelogRoute
  '/zh-hant/pricing': typeof ZhHantPricingRoute
  '/zh/blog': typeof ZhBlogRouteWithChildren
  '/zh/changelog': typeof ZhChangelogRoute
  '/zh/docs': typeof ZhDocsRouteWithChildren
  '/zh/pricing': typeof ZhPricingRoute
  '/blog/': typeof BlogIndexRoute
  '/de/': typeof DeIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/es/': typeof EsIndexRoute
  '/fr/': typeof FrIndexRoute
  '/ja/': typeof JaIndexRoute
  '/ru/': typeof RuIndexRoute
  '/zh-hant/': typeof ZhHantIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/docs/plugins/api': typeof DocsPluginsApiRoute
  '/docs/plugins/publishing': typeof DocsPluginsPublishingRoute
  '/ja/blog/local-first': typeof JaBlogLocalFirstRoute
  '/ja/blog/plugins-v1': typeof JaBlogPluginsV1Route
  '/ja/blog/reading-that-remembers': typeof JaBlogReadingThatRemembersRoute
  '/ja/docs/getting-started': typeof JaDocsGettingStartedRoute
  '/ja/docs/install': typeof JaDocsInstallRoute
  '/zh/blog/local-first': typeof ZhBlogLocalFirstRoute
  '/zh/blog/plugins-v1': typeof ZhBlogPluginsV1Route
  '/zh/blog/reading-that-remembers': typeof ZhBlogReadingThatRemembersRoute
  '/zh/docs/getting-started': typeof ZhDocsGettingStartedRoute
  '/zh/docs/install': typeof ZhDocsInstallRoute
  '/docs/plugins/': typeof DocsPluginsIndexRoute
  '/ja/blog/': typeof JaBlogIndexRoute
  '/ja/docs/': typeof JaDocsIndexRoute
  '/zh/blog/': typeof ZhBlogIndexRoute
  '/zh/docs/': typeof ZhDocsIndexRoute
  '/ja/docs/plugins/api': typeof JaDocsPluginsApiRoute
  '/ja/docs/plugins/publishing': typeof JaDocsPluginsPublishingRoute
  '/zh/docs/plugins/api': typeof ZhDocsPluginsApiRoute
  '/zh/docs/plugins/publishing': typeof ZhDocsPluginsPublishingRoute
  '/ja/docs/plugins/': typeof JaDocsPluginsIndexRoute
  '/zh/docs/plugins/': typeof ZhDocsPluginsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/cbz-cbr-reader'
    | '/changelog'
    | '/docs'
    | '/epub-reader-for-android'
    | '/epub-reader-for-windows'
    | '/open-source-ebook-reader'
    | '/pricing'
    | '/blog/local-first'
    | '/blog/plugins-v1'
    | '/blog/reading-that-remembers'
    | '/de/changelog'
    | '/de/pricing'
    | '/docs/getting-started'
    | '/docs/install'
    | '/es/changelog'
    | '/es/pricing'
    | '/fr/changelog'
    | '/fr/pricing'
    | '/ja/blog'
    | '/ja/changelog'
    | '/ja/docs'
    | '/ja/pricing'
    | '/ru/changelog'
    | '/ru/pricing'
    | '/zh-hant/changelog'
    | '/zh-hant/pricing'
    | '/zh/blog'
    | '/zh/changelog'
    | '/zh/docs'
    | '/zh/pricing'
    | '/blog/'
    | '/de/'
    | '/docs/'
    | '/es/'
    | '/fr/'
    | '/ja/'
    | '/ru/'
    | '/zh-hant/'
    | '/zh/'
    | '/docs/plugins/api'
    | '/docs/plugins/publishing'
    | '/ja/blog/local-first'
    | '/ja/blog/plugins-v1'
    | '/ja/blog/reading-that-remembers'
    | '/ja/docs/getting-started'
    | '/ja/docs/install'
    | '/zh/blog/local-first'
    | '/zh/blog/plugins-v1'
    | '/zh/blog/reading-that-remembers'
    | '/zh/docs/getting-started'
    | '/zh/docs/install'
    | '/docs/plugins/'
    | '/ja/blog/'
    | '/ja/docs/'
    | '/zh/blog/'
    | '/zh/docs/'
    | '/ja/docs/plugins/api'
    | '/ja/docs/plugins/publishing'
    | '/zh/docs/plugins/api'
    | '/zh/docs/plugins/publishing'
    | '/ja/docs/plugins/'
    | '/zh/docs/plugins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cbz-cbr-reader'
    | '/changelog'
    | '/epub-reader-for-android'
    | '/epub-reader-for-windows'
    | '/open-source-ebook-reader'
    | '/pricing'
    | '/blog/local-first'
    | '/blog/plugins-v1'
    | '/blog/reading-that-remembers'
    | '/de/changelog'
    | '/de/pricing'
    | '/docs/getting-started'
    | '/docs/install'
    | '/es/changelog'
    | '/es/pricing'
    | '/fr/changelog'
    | '/fr/pricing'
    | '/ja/changelog'
    | '/ja/pricing'
    | '/ru/changelog'
    | '/ru/pricing'
    | '/zh-hant/changelog'
    | '/zh-hant/pricing'
    | '/zh/changelog'
    | '/zh/pricing'
    | '/blog'
    | '/de'
    | '/docs'
    | '/es'
    | '/fr'
    | '/ja'
    | '/ru'
    | '/zh-hant'
    | '/zh'
    | '/docs/plugins/api'
    | '/docs/plugins/publishing'
    | '/ja/blog/local-first'
    | '/ja/blog/plugins-v1'
    | '/ja/blog/reading-that-remembers'
    | '/ja/docs/getting-started'
    | '/ja/docs/install'
    | '/zh/blog/local-first'
    | '/zh/blog/plugins-v1'
    | '/zh/blog/reading-that-remembers'
    | '/zh/docs/getting-started'
    | '/zh/docs/install'
    | '/docs/plugins'
    | '/ja/blog'
    | '/ja/docs'
    | '/zh/blog'
    | '/zh/docs'
    | '/ja/docs/plugins/api'
    | '/ja/docs/plugins/publishing'
    | '/zh/docs/plugins/api'
    | '/zh/docs/plugins/publishing'
    | '/ja/docs/plugins'
    | '/zh/docs/plugins'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/cbz-cbr-reader'
    | '/changelog'
    | '/docs'
    | '/epub-reader-for-android'
    | '/epub-reader-for-windows'
    | '/open-source-ebook-reader'
    | '/pricing'
    | '/blog/local-first'
    | '/blog/plugins-v1'
    | '/blog/reading-that-remembers'
    | '/de/changelog'
    | '/de/pricing'
    | '/docs/getting-started'
    | '/docs/install'
    | '/es/changelog'
    | '/es/pricing'
    | '/fr/changelog'
    | '/fr/pricing'
    | '/ja/blog'
    | '/ja/changelog'
    | '/ja/docs'
    | '/ja/pricing'
    | '/ru/changelog'
    | '/ru/pricing'
    | '/zh-hant/changelog'
    | '/zh-hant/pricing'
    | '/zh/blog'
    | '/zh/changelog'
    | '/zh/docs'
    | '/zh/pricing'
    | '/blog/'
    | '/de/'
    | '/docs/'
    | '/es/'
    | '/fr/'
    | '/ja/'
    | '/ru/'
    | '/zh-hant/'
    | '/zh/'
    | '/docs/plugins/api'
    | '/docs/plugins/publishing'
    | '/ja/blog/local-first'
    | '/ja/blog/plugins-v1'
    | '/ja/blog/reading-that-remembers'
    | '/ja/docs/getting-started'
    | '/ja/docs/install'
    | '/zh/blog/local-first'
    | '/zh/blog/plugins-v1'
    | '/zh/blog/reading-that-remembers'
    | '/zh/docs/getting-started'
    | '/zh/docs/install'
    | '/docs/plugins/'
    | '/ja/blog/'
    | '/ja/docs/'
    | '/zh/blog/'
    | '/zh/docs/'
    | '/ja/docs/plugins/api'
    | '/ja/docs/plugins/publishing'
    | '/zh/docs/plugins/api'
    | '/zh/docs/plugins/publishing'
    | '/ja/docs/plugins/'
    | '/zh/docs/plugins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CbzCbrReaderRoute: typeof CbzCbrReaderRoute
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRouteWithChildren
  EpubReaderForAndroidRoute: typeof EpubReaderForAndroidRoute
  EpubReaderForWindowsRoute: typeof EpubReaderForWindowsRoute
  OpenSourceEbookReaderRoute: typeof OpenSourceEbookReaderRoute
  PricingRoute: typeof PricingRoute
  DeChangelogRoute: typeof DeChangelogRoute
  DePricingRoute: typeof DePricingRoute
  EsChangelogRoute: typeof EsChangelogRoute
  EsPricingRoute: typeof EsPricingRoute
  FrChangelogRoute: typeof FrChangelogRoute
  FrPricingRoute: typeof FrPricingRoute
  JaBlogRoute: typeof JaBlogRouteWithChildren
  JaChangelogRoute: typeof JaChangelogRoute
  JaDocsRoute: typeof JaDocsRouteWithChildren
  JaPricingRoute: typeof JaPricingRoute
  RuChangelogRoute: typeof RuChangelogRoute
  RuPricingRoute: typeof RuPricingRoute
  ZhHantChangelogRoute: typeof ZhHantChangelogRoute
  ZhHantPricingRoute: typeof ZhHantPricingRoute
  ZhBlogRoute: typeof ZhBlogRouteWithChildren
  ZhChangelogRoute: typeof ZhChangelogRoute
  ZhDocsRoute: typeof ZhDocsRouteWithChildren
  ZhPricingRoute: typeof ZhPricingRoute
  DeIndexRoute: typeof DeIndexRoute
  EsIndexRoute: typeof EsIndexRoute
  FrIndexRoute: typeof FrIndexRoute
  JaIndexRoute: typeof JaIndexRoute
  RuIndexRoute: typeof RuIndexRoute
  ZhHantIndexRoute: typeof ZhHantIndexRoute
  ZhIndexRoute: typeof ZhIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source-ebook-reader': {
      id: '/open-source-ebook-reader'
      path: '/open-source-ebook-reader'
      fullPath: '/open-source-ebook-reader'
      preLoaderRoute: typeof OpenSourceEbookReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epub-reader-for-windows': {
      id: '/epub-reader-for-windows'
      path: '/epub-reader-for-windows'
      fullPath: '/epub-reader-for-windows'
      preLoaderRoute: typeof EpubReaderForWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epub-reader-for-android': {
      id: '/epub-reader-for-android'
      path: '/epub-reader-for-android'
      fullPath: '/epub-reader-for-android'
      preLoaderRoute: typeof EpubReaderForAndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbz-cbr-reader': {
      id: '/cbz-cbr-reader'
      path: '/cbz-cbr-reader'
      fullPath: '/cbz-cbr-reader'
      preLoaderRoute: typeof CbzCbrReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/': {
      id: '/zh/'
      path: '/zh'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/': {
      id: '/zh-hant/'
      path: '/zh-hant'
      fullPath: '/zh-hant/'
      preLoaderRoute: typeof ZhHantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/': {
      id: '/ru/'
      path: '/ru'
      fullPath: '/ru/'
      preLoaderRoute: typeof RuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/': {
      id: '/ja/'
      path: '/ja'
      fullPath: '/ja/'
      preLoaderRoute: typeof JaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/de/': {
      id: '/de/'
      path: '/de'
      fullPath: '/de/'
      preLoaderRoute: typeof DeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/zh/pricing': {
      id: '/zh/pricing'
      path: '/zh/pricing'
      fullPath: '/zh/pricing'
      preLoaderRoute: typeof ZhPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/docs': {
      id: '/zh/docs'
      path: '/zh/docs'
      fullPath: '/zh/docs'
      preLoaderRoute: typeof ZhDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/changelog': {
      id: '/zh/changelog'
      path: '/zh/changelog'
      fullPath: '/zh/changelog'
      preLoaderRoute: typeof ZhChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/blog': {
      id: '/zh/blog'
      path: '/zh/blog'
      fullPath: '/zh/blog'
      preLoaderRoute: typeof ZhBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/pricing': {
      id: '/zh-hant/pricing'
      path: '/zh-hant/pricing'
      fullPath: '/zh-hant/pricing'
      preLoaderRoute: typeof ZhHantPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/changelog': {
      id: '/zh-hant/changelog'
      path: '/zh-hant/changelog'
      fullPath: '/zh-hant/changelog'
      preLoaderRoute: typeof ZhHantChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/pricing': {
      id: '/ru/pricing'
      path: '/ru/pricing'
      fullPath: '/ru/pricing'
      preLoaderRoute: typeof RuPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/changelog': {
      id: '/ru/changelog'
      path: '/ru/changelog'
      fullPath: '/ru/changelog'
      preLoaderRoute: typeof RuChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/pricing': {
      id: '/ja/pricing'
      path: '/ja/pricing'
      fullPath: '/ja/pricing'
      preLoaderRoute: typeof JaPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/docs': {
      id: '/ja/docs'
      path: '/ja/docs'
      fullPath: '/ja/docs'
      preLoaderRoute: typeof JaDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/changelog': {
      id: '/ja/changelog'
      path: '/ja/changelog'
      fullPath: '/ja/changelog'
      preLoaderRoute: typeof JaChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/blog': {
      id: '/ja/blog'
      path: '/ja/blog'
      fullPath: '/ja/blog'
      preLoaderRoute: typeof JaBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/pricing': {
      id: '/fr/pricing'
      path: '/fr/pricing'
      fullPath: '/fr/pricing'
      preLoaderRoute: typeof FrPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/changelog': {
      id: '/fr/changelog'
      path: '/fr/changelog'
      fullPath: '/fr/changelog'
      preLoaderRoute: typeof FrChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/pricing': {
      id: '/es/pricing'
      path: '/es/pricing'
      fullPath: '/es/pricing'
      preLoaderRoute: typeof EsPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/changelog': {
      id: '/es/changelog'
      path: '/es/changelog'
      fullPath: '/es/changelog'
      preLoaderRoute: typeof EsChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/install': {
      id: '/docs/install'
      path: '/install'
      fullPath: '/docs/install'
      preLoaderRoute: typeof DocsInstallRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/de/pricing': {
      id: '/de/pricing'
      path: '/de/pricing'
      fullPath: '/de/pricing'
      preLoaderRoute: typeof DePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/changelog': {
      id: '/de/changelog'
      path: '/de/changelog'
      fullPath: '/de/changelog'
      preLoaderRoute: typeof DeChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/reading-that-remembers': {
      id: '/blog/reading-that-remembers'
      path: '/reading-that-remembers'
      fullPath: '/blog/reading-that-remembers'
      preLoaderRoute: typeof BlogReadingThatRemembersRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/plugins-v1': {
      id: '/blog/plugins-v1'
      path: '/plugins-v1'
      fullPath: '/blog/plugins-v1'
      preLoaderRoute: typeof BlogPluginsV1RouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/local-first': {
      id: '/blog/local-first'
      path: '/local-first'
      fullPath: '/blog/local-first'
      preLoaderRoute: typeof BlogLocalFirstRouteImport
      parentRoute: typeof BlogRoute
    }
    '/zh/docs/': {
      id: '/zh/docs/'
      path: '/'
      fullPath: '/zh/docs/'
      preLoaderRoute: typeof ZhDocsIndexRouteImport
      parentRoute: typeof ZhDocsRoute
    }
    '/zh/blog/': {
      id: '/zh/blog/'
      path: '/'
      fullPath: '/zh/blog/'
      preLoaderRoute: typeof ZhBlogIndexRouteImport
      parentRoute: typeof ZhBlogRoute
    }
    '/ja/docs/': {
      id: '/ja/docs/'
      path: '/'
      fullPath: '/ja/docs/'
      preLoaderRoute: typeof JaDocsIndexRouteImport
      parentRoute: typeof JaDocsRoute
    }
    '/ja/blog/': {
      id: '/ja/blog/'
      path: '/'
      fullPath: '/ja/blog/'
      preLoaderRoute: typeof JaBlogIndexRouteImport
      parentRoute: typeof JaBlogRoute
    }
    '/docs/plugins/': {
      id: '/docs/plugins/'
      path: '/plugins'
      fullPath: '/docs/plugins/'
      preLoaderRoute: typeof DocsPluginsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/zh/docs/install': {
      id: '/zh/docs/install'
      path: '/install'
      fullPath: '/zh/docs/install'
      preLoaderRoute: typeof ZhDocsInstallRouteImport
      parentRoute: typeof ZhDocsRoute
    }
    '/zh/docs/getting-started': {
      id: '/zh/docs/getting-started'
      path: '/getting-started'
      fullPath: '/zh/docs/getting-started'
      preLoaderRoute: typeof ZhDocsGettingStartedRouteImport
      parentRoute: typeof ZhDocsRoute
    }
    '/zh/blog/reading-that-remembers': {
      id: '/zh/blog/reading-that-remembers'
      path: '/reading-that-remembers'
      fullPath: '/zh/blog/reading-that-remembers'
      preLoaderRoute: typeof ZhBlogReadingThatRemembersRouteImport
      parentRoute: typeof ZhBlogRoute
    }
    '/zh/blog/plugins-v1': {
      id: '/zh/blog/plugins-v1'
      path: '/plugins-v1'
      fullPath: '/zh/blog/plugins-v1'
      preLoaderRoute: typeof ZhBlogPluginsV1RouteImport
      parentRoute: typeof ZhBlogRoute
    }
    '/zh/blog/local-first': {
      id: '/zh/blog/local-first'
      path: '/local-first'
      fullPath: '/zh/blog/local-first'
      preLoaderRoute: typeof ZhBlogLocalFirstRouteImport
      parentRoute: typeof ZhBlogRoute
    }
    '/ja/docs/install': {
      id: '/ja/docs/install'
      path: '/install'
      fullPath: '/ja/docs/install'
      preLoaderRoute: typeof JaDocsInstallRouteImport
      parentRoute: typeof JaDocsRoute
    }
    '/ja/docs/getting-started': {
      id: '/ja/docs/getting-started'
      path: '/getting-started'
      fullPath: '/ja/docs/getting-started'
      preLoaderRoute: typeof JaDocsGettingStartedRouteImport
      parentRoute: typeof JaDocsRoute
    }
    '/ja/blog/reading-that-remembers': {
      id: '/ja/blog/reading-that-remembers'
      path: '/reading-that-remembers'
      fullPath: '/ja/blog/reading-that-remembers'
      preLoaderRoute: typeof JaBlogReadingThatRemembersRouteImport
      parentRoute: typeof JaBlogRoute
    }
    '/ja/blog/plugins-v1': {
      id: '/ja/blog/plugins-v1'
      path: '/plugins-v1'
      fullPath: '/ja/blog/plugins-v1'
      preLoaderRoute: typeof JaBlogPluginsV1RouteImport
      parentRoute: typeof JaBlogRoute
    }
    '/ja/blog/local-first': {
      id: '/ja/blog/local-first'
      path: '/local-first'
      fullPath: '/ja/blog/local-first'
      preLoaderRoute: typeof JaBlogLocalFirstRouteImport
      parentRoute: typeof JaBlogRoute
    }
    '/docs/plugins/publishing': {
      id: '/docs/plugins/publishing'
      path: '/plugins/publishing'
      fullPath: '/docs/plugins/publishing'
      preLoaderRoute: typeof DocsPluginsPublishingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/plugins/api': {
      id: '/docs/plugins/api'
      path: '/plugins/api'
      fullPath: '/docs/plugins/api'
      preLoaderRoute: typeof DocsPluginsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/zh/docs/plugins/': {
      id: '/zh/docs/plugins/'
      path: '/plugins'
      fullPath: '/zh/docs/plugins/'
      preLoaderRoute: typeof ZhDocsPluginsIndexRouteImport
      parentRoute: typeof ZhDocsRoute
    }
    '/ja/docs/plugins/': {
      id: '/ja/docs/plugins/'
      path: '/plugins'
      fullPath: '/ja/docs/plugins/'
      preLoaderRoute: typeof JaDocsPluginsIndexRouteImport
      parentRoute: typeof JaDocsRoute
    }
    '/zh/docs/plugins/publishing': {
      id: '/zh/docs/plugins/publishing'
      path: '/plugins/publishing'
      fullPath: '/zh/docs/plugins/publishing'
      preLoaderRoute: typeof ZhDocsPluginsPublishingRouteImport
      parentRoute: typeof ZhDocsRoute
    }
    '/zh/docs/plugins/api': {
      id: '/zh/docs/plugins/api'
      path: '/plugins/api'
      fullPath: '/zh/docs/plugins/api'
      preLoaderRoute: typeof ZhDocsPluginsApiRouteImport
      parentRoute: typeof ZhDocsRoute
    }
    '/ja/docs/plugins/publishing': {
      id: '/ja/docs/plugins/publishing'
      path: '/plugins/publishing'
      fullPath: '/ja/docs/plugins/publishing'
      preLoaderRoute: typeof JaDocsPluginsPublishingRouteImport
      parentRoute: typeof JaDocsRoute
    }
    '/ja/docs/plugins/api': {
      id: '/ja/docs/plugins/api'
      path: '/plugins/api'
      fullPath: '/ja/docs/plugins/api'
      preLoaderRoute: typeof JaDocsPluginsApiRouteImport
      parentRoute: typeof JaDocsRoute
    }
  }
}

interface BlogRouteChildren {
  BlogLocalFirstRoute: typeof BlogLocalFirstRoute
  BlogPluginsV1Route: typeof BlogPluginsV1Route
  BlogReadingThatRemembersRoute: typeof BlogReadingThatRemembersRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogLocalFirstRoute: BlogLocalFirstRoute,
  BlogPluginsV1Route: BlogPluginsV1Route,
  BlogReadingThatRemembersRoute: BlogReadingThatRemembersRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DocsRouteChildren {
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsInstallRoute: typeof DocsInstallRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsPluginsApiRoute: typeof DocsPluginsApiRoute
  DocsPluginsPublishingRoute: typeof DocsPluginsPublishingRoute
  DocsPluginsIndexRoute: typeof DocsPluginsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsInstallRoute: DocsInstallRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsPluginsApiRoute: DocsPluginsApiRoute,
  DocsPluginsPublishingRoute: DocsPluginsPublishingRoute,
  DocsPluginsIndexRoute: DocsPluginsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface JaBlogRouteChildren {
  JaBlogLocalFirstRoute: typeof JaBlogLocalFirstRoute
  JaBlogPluginsV1Route: typeof JaBlogPluginsV1Route
  JaBlogReadingThatRemembersRoute: typeof JaBlogReadingThatRemembersRoute
  JaBlogIndexRoute: typeof JaBlogIndexRoute
}

const JaBlogRouteChildren: JaBlogRouteChildren = {
  JaBlogLocalFirstRoute: JaBlogLocalFirstRoute,
  JaBlogPluginsV1Route: JaBlogPluginsV1Route,
  JaBlogReadingThatRemembersRoute: JaBlogReadingThatRemembersRoute,
  JaBlogIndexRoute: JaBlogIndexRoute,
}

const JaBlogRouteWithChildren =
  JaBlogRoute._addFileChildren(JaBlogRouteChildren)

interface JaDocsRouteChildren {
  JaDocsGettingStartedRoute: typeof JaDocsGettingStartedRoute
  JaDocsInstallRoute: typeof JaDocsInstallRoute
  JaDocsIndexRoute: typeof JaDocsIndexRoute
  JaDocsPluginsApiRoute: typeof JaDocsPluginsApiRoute
  JaDocsPluginsPublishingRoute: typeof JaDocsPluginsPublishingRoute
  JaDocsPluginsIndexRoute: typeof JaDocsPluginsIndexRoute
}

const JaDocsRouteChildren: JaDocsRouteChildren = {
  JaDocsGettingStartedRoute: JaDocsGettingStartedRoute,
  JaDocsInstallRoute: JaDocsInstallRoute,
  JaDocsIndexRoute: JaDocsIndexRoute,
  JaDocsPluginsApiRoute: JaDocsPluginsApiRoute,
  JaDocsPluginsPublishingRoute: JaDocsPluginsPublishingRoute,
  JaDocsPluginsIndexRoute: JaDocsPluginsIndexRoute,
}

const JaDocsRouteWithChildren =
  JaDocsRoute._addFileChildren(JaDocsRouteChildren)

interface ZhBlogRouteChildren {
  ZhBlogLocalFirstRoute: typeof ZhBlogLocalFirstRoute
  ZhBlogPluginsV1Route: typeof ZhBlogPluginsV1Route
  ZhBlogReadingThatRemembersRoute: typeof ZhBlogReadingThatRemembersRoute
  ZhBlogIndexRoute: typeof ZhBlogIndexRoute
}

const ZhBlogRouteChildren: ZhBlogRouteChildren = {
  ZhBlogLocalFirstRoute: ZhBlogLocalFirstRoute,
  ZhBlogPluginsV1Route: ZhBlogPluginsV1Route,
  ZhBlogReadingThatRemembersRoute: ZhBlogReadingThatRemembersRoute,
  ZhBlogIndexRoute: ZhBlogIndexRoute,
}

const ZhBlogRouteWithChildren =
  ZhBlogRoute._addFileChildren(ZhBlogRouteChildren)

interface ZhDocsRouteChildren {
  ZhDocsGettingStartedRoute: typeof ZhDocsGettingStartedRoute
  ZhDocsInstallRoute: typeof ZhDocsInstallRoute
  ZhDocsIndexRoute: typeof ZhDocsIndexRoute
  ZhDocsPluginsApiRoute: typeof ZhDocsPluginsApiRoute
  ZhDocsPluginsPublishingRoute: typeof ZhDocsPluginsPublishingRoute
  ZhDocsPluginsIndexRoute: typeof ZhDocsPluginsIndexRoute
}

const ZhDocsRouteChildren: ZhDocsRouteChildren = {
  ZhDocsGettingStartedRoute: ZhDocsGettingStartedRoute,
  ZhDocsInstallRoute: ZhDocsInstallRoute,
  ZhDocsIndexRoute: ZhDocsIndexRoute,
  ZhDocsPluginsApiRoute: ZhDocsPluginsApiRoute,
  ZhDocsPluginsPublishingRoute: ZhDocsPluginsPublishingRoute,
  ZhDocsPluginsIndexRoute: ZhDocsPluginsIndexRoute,
}

const ZhDocsRouteWithChildren =
  ZhDocsRoute._addFileChildren(ZhDocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CbzCbrReaderRoute: CbzCbrReaderRoute,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRouteWithChildren,
  EpubReaderForAndroidRoute: EpubReaderForAndroidRoute,
  EpubReaderForWindowsRoute: EpubReaderForWindowsRoute,
  OpenSourceEbookReaderRoute: OpenSourceEbookReaderRoute,
  PricingRoute: PricingRoute,
  DeChangelogRoute: DeChangelogRoute,
  DePricingRoute: DePricingRoute,
  EsChangelogRoute: EsChangelogRoute,
  EsPricingRoute: EsPricingRoute,
  FrChangelogRoute: FrChangelogRoute,
  FrPricingRoute: FrPricingRoute,
  JaBlogRoute: JaBlogRouteWithChildren,
  JaChangelogRoute: JaChangelogRoute,
  JaDocsRoute: JaDocsRouteWithChildren,
  JaPricingRoute: JaPricingRoute,
  RuChangelogRoute: RuChangelogRoute,
  RuPricingRoute: RuPricingRoute,
  ZhHantChangelogRoute: ZhHantChangelogRoute,
  ZhHantPricingRoute: ZhHantPricingRoute,
  ZhBlogRoute: ZhBlogRouteWithChildren,
  ZhChangelogRoute: ZhChangelogRoute,
  ZhDocsRoute: ZhDocsRouteWithChildren,
  ZhPricingRoute: ZhPricingRoute,
  DeIndexRoute: DeIndexRoute,
  EsIndexRoute: EsIndexRoute,
  FrIndexRoute: FrIndexRoute,
  JaIndexRoute: JaIndexRoute,
  RuIndexRoute: RuIndexRoute,
  ZhHantIndexRoute: ZhHantIndexRoute,
  ZhIndexRoute: ZhIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
