const en = {
  title: "Synchronization", status: "Status", unavailable: "Synchronization unavailable on this platform",
  backend: "Backend", relay: "ReadAware Relay", transport: "Plugin transport", none: "None", unknown: "Unknown",
  lastSync: "Last synchronization", never: "Never", managing: "Connection management", yes: "In progress", no: "Idle",
  backlog: "Current local backlog", events: "Events", blobs: "Files", cycleBacklog: "Backlog at cycle start",
  lastCycle: "Last cycle", pulled: "Events pulled", pushed: "Events pushed", verified: "Events verified",
  backfilled: "History events backfilled", remaining: "History events remaining", blobsDone: "Files transferred", blobsTotal: "Files in this cycle",
  refresh: "Refresh", settings: "Open sync settings", account: "Read account usage (online)", noAccount: "No connected Relay account",
  tier: "Tier", bytesUsed: "Stored file bytes", eventsUsed: "Stored events", creditsUsed: "AI credits used this month",
  maxBlob: "Maximum bytes per file", maxBytes: "Stored file byte limit", maxEvents: "Stored event limit", maxCredits: "Monthly AI credit limit",
  unlimited: "Unlimited", choose: "Connect synchronization", continue: "Continue", results: "Recent operations",
  connectReview: "Continue to the native connection form. Identity, credentials and passphrase stay in the host.",
  disconnectReview: "Disconnect this device from synchronization. Local books remain on this device. Confirm in the native settings.",
  deleteReview: "Delete the connected Relay account and its remote data. Local books remain. The host requires your final confirmation; cancelling this wait cannot undo deletion already started.",
  upgradeReview: "Open the host's plan selection. A browser handoff is not a completed purchase.",
  billingReview: "Open the host's billing controls. A browser handoff is not confirmation that billing changed.",
  syncReview: "Synchronize local changes using the configured connection. This can upload and download data. Cancelling the wait does not stop a shared synchronization or undo applied changes.",
  states: { disabled: "Disabled", idle: "Idle", syncing: "Synchronizing", error: "Synchronization failed", unauthenticated: "Sign-in required" },
  phases: { bootstrap: "Restoring device", pull: "Pulling events", verify: "Verifying receipts", push: "Pushing events",
    blobs: "Transferring files", backfill: "Backfilling history", checkpoint: "Updating checkpoint" },
};
const zh: typeof en = {
  title: "同步", status: "状态", unavailable: "此平台不支持同步",
  backend: "后端", relay: "ReadAware Relay", transport: "插件传输", none: "无", unknown: "未知",
  lastSync: "上次同步", never: "从未同步", managing: "连接管理", yes: "正在处理", no: "空闲",
  backlog: "当前本地积压", events: "事件", blobs: "文件", cycleBacklog: "本轮开始时的积压",
  lastCycle: "上轮同步", pulled: "拉取事件", pushed: "推送事件", verified: "已核验事件",
  backfilled: "回填历史事件", remaining: "剩余历史事件", blobsDone: "已传输文件", blobsTotal: "本轮文件总数",
  refresh: "刷新", settings: "打开同步设置", account: "查询账户用量（联网）", noAccount: "未连接 Relay 账户",
  tier: "套餐", bytesUsed: "已存文件字节", eventsUsed: "已存事件", creditsUsed: "本月已用 AI 点数",
  maxBlob: "单文件字节上限", maxBytes: "文件总字节上限", maxEvents: "事件总数上限", maxCredits: "每月 AI 点数上限",
  unlimited: "不限", choose: "连接同步", continue: "继续", results: "近期操作",
  connectReview: "继续后打开原生连接表单。身份、凭据和口令均由宿主处理。",
  disconnectReview: "断开此设备的同步连接，本机书籍仍保留。请在原生设置中确认。",
  deleteReview: "删除所连接的 Relay 账户及其远端数据，本机书籍仍保留。宿主会要求最终确认；取消等待无法撤销已开始的删除。",
  upgradeReview: "打开宿主套餐选择。跳转浏览器不代表购买完成。",
  billingReview: "打开宿主账单管理。跳转浏览器不代表账单已变更。",
  syncReview: "使用当前连接同步本地变更，可能上传和下载数据。取消等待不会停止共享同步，也不能撤销已应用的变更。",
  states: { disabled: "已停用", idle: "空闲", syncing: "正在同步", error: "同步失败", unauthenticated: "需要登录" },
  phases: { bootstrap: "正在恢复设备", pull: "正在拉取事件", verify: "正在核验回执", push: "正在推送事件",
    blobs: "正在传输文件", backfill: "正在回填历史", checkpoint: "正在更新检查点" },
};
export const syncCopy = (locale: string) => locale.startsWith("zh") ? zh : en;
