/** Source-audited facts. Generated Markdown/HTML must not be edited independently. */
export type HostState = "实装" | "部分" | "引擎" | "占位" | "待建" | "非桌面";
export type ActorState = "接通" | "部分" | "自动" | "内部" | "扩展" | "未接";
export type Actor = { state: ActorState; via: string; target: string };
export type Capability = {
  id: string; name: string; host: HostState; agent: Actor; plugin: Actor;
  sources: string[]; consumers: string; gap: string; baseline: string[];
};
export const actor = (state: ActorState, via: string, target: string): Actor => ({ state, via, target });
export const absent = (target: string): Actor => actor("未接", "无正式入口", target);
export const cap = (id: string, name: string, host: HostState, agent: Actor, plugin: Actor,
  sources: string[], consumers: string, gap: string): Capability =>
  ({ id, name, host, agent, plugin, sources, consumers, gap, baseline: [] });

export const sources: Record<string, string> = {
  API: "packages/plugin-types/src/index.ts",
  CTX: "apps/web/src/features/plugins/runtime/plugin-context.ts",
  WIRE: "apps/web/src/features/plugins/runtime/plugin-worker-host.ts",
  WORKER: "apps/web/src/features/plugins/runtime/plugin-sandbox.worker.ts",
  CATALOG: "packages/core/src/capabilities.ts",
  DOM: "apps/web/src/domain/registry.ts",
  LIB: "apps/web/src/domain/library.ts",
  LIBUI: "apps/web/src/features/library/hooks/useLibraryCommands.ts",
  IMPORT: "apps/web/src/features/library/lib/book-import.ts",
  ENRICH: "apps/web/src/features/library/lib/book-enrichment.ts",
  DEDUPE: "apps/web/src/platform/book-dedupe.ts",
  TEXT: "apps/web/src/features/library/lib/book-text-store.ts",
  READER: "apps/web/src/features/reader/components/FoliateReaderView.tsx",
  SESSION: "apps/web/src/features/reader/hooks/useReaderSession.ts",
  WORKSPACE: "apps/web/src/features/reader/components/ReaderWorkspace.tsx",
  ENGINE: "apps/web/foliate-js/src/view.ts",
  HISTORY: "apps/web/foliate-js/src/history.ts",
  NAV: "apps/web/src/features/plugins/state/reader-nav.ts",
  UNITS: "apps/web/src/features/reader/hooks/useTextUnitNavigator.ts",
  AUDIO: "apps/web/src/features/reader/hooks/useReadAloud.ts",
  ANNOT: "apps/web/src/domain/annotations.ts",
  ANNDB: "apps/web/src/features/annotations/lib/annotation-db.ts",
  TEXTACTIONS: "apps/web/src/features/reader/hooks/useReaderTextActions.ts",
  READING: "apps/web/src/domain/reading.ts",
  TIME: "apps/web/src/platform/reading-session.ts",
  STATS: "apps/web/src/features/stats/lib/reading-insights.ts",
  STATUI: "apps/web/src/features/stats/components/StatsWorkspace.tsx",
  SETTINGS: "apps/web/src/domain/settings/catalog.ts",
  SETDOMAIN: "apps/web/src/domain/settings/domain.ts",
  PREFS: "apps/web/src/features/settings/lib/reader-settings.ts",
  OVERRIDES: "apps/web/src/features/settings/lib/reader-overrides.ts",
  GENERAL: "apps/web/src/features/settings/lib/general-settings.ts",
  AIPREFS: "apps/web/src/features/settings/lib/ai-preferences.ts",
  AICONFIG: "apps/web/src/features/ai/lib/ai-config.ts",
  MODELCATALOG: "apps/web/src/features/ai/lib/model-catalog.ts",
  AICONFIGUI: "apps/web/src/features/settings/components/AIConfigPanel.tsx",
  SHELF: "apps/web/src/features/shelf/lib/shelf-view.ts",
  SHELFUI: "apps/web/src/features/shelf/components/Shelf.tsx",
  SHORTCUT: "apps/web/src/features/settings/lib/shortcuts.ts",
  SHORTUI: "apps/web/src/features/settings/sections/ShortcutsPanel.tsx",
  MENU: "apps/web/src/features/menus/lib/menu-registry.tsx",
  MENUSTATE: "apps/web/src/features/menus/state/menu-config.ts",
  COMMAND: "apps/web/src/features/command/lib/build-commands.tsx",
  APP: "apps/web/src/App.tsx",
  UI: "apps/web/src/state/ui.ts",
  CHAT: "apps/web/src/features/ai/lib/conversation-store.ts",
  CHATDOMAIN: "apps/web/src/domain/conversations.ts",
  CHATUI: "apps/web/src/features/ai/components/ChatPanel.tsx",
  CHATCONTROL: "apps/web/src/features/ai/hooks/useBookConversation.ts",
  AGENTUI: "apps/web/src/features/agent/components/AgentWorkspace.tsx",
  REGISTRY: "packages/agent/src/tools/registry.ts",
  PORTS: "apps/web/src/features/ai/agent/ports/index.ts",
  LIBPORT: "apps/web/src/features/ai/agent/ports/library-port.ts",
  TEXTPORT: "apps/web/src/features/ai/agent/ports/book-text-port.ts",
  READERPORT: "apps/web/src/features/ai/agent/ports/reader-port.ts",
  MEMORYPORT: "apps/web/src/features/ai/agent/ports/memory-port.ts",
  PROFILEPORT: "apps/web/src/features/ai/agent/ports/profile-port.ts",
  CHATPORT: "apps/web/src/features/ai/agent/ports/conversation-port.ts",
  GRAPHP: "apps/web/src/features/ai/agent/ports/book-memory-port.ts",
  LIBTOOLS: "packages/agent/src/tools/library-tools.ts",
  SHELFTOOLS: "packages/agent/src/tools/shelf-tools.ts",
  ANNTOOLS: "packages/agent/src/tools/annotation-tools.ts",
  TEXTTOOLS: "packages/agent/src/tools/book-text-tools.ts",
  READTOOLS: "packages/agent/src/tools/reader-tools.ts",
  CHATTOOLS: "packages/agent/src/tools/conversation-tools.ts",
  MEMTOOLS: "packages/agent/src/tools/memory-tools.ts",
  GRAPHTOOLS: "packages/agent/src/tools/graph-tools.ts",
  SETTOOLS: "packages/agent/src/tools/settings-tools.ts",
  INTERACTION: "packages/agent/src/tools/interaction-tools.ts",
  PRESENT: "packages/agent/src/tools/present-tools.ts",
  THREAD: "packages/agent/src/runtime/thread.ts",
  RUNTIME: "packages/agent/src/runtime/runtime.ts",
  MAINT: "apps/web/src/features/ai/agent/maintenance.ts",
  ONBOARD: "packages/agent/src/onboarding.ts",
  CONSOLIDATE: "packages/agent/src/memory/consolidation.ts",
  GROUND: "packages/agent/src/runtime/grounding-context.ts",
  SPOILER: "packages/agent/src/tools/spoiler-permission.ts",
  EXTOOLS: "apps/web/src/features/plugins/runtime/plugin-tools.ts",
  VIEWS: "apps/web/src/features/plugins/lib/plugin-view.ts",
  RENDER: "apps/web/src/features/plugins/components/PluginViewRenderer.tsx",
  HOST: "apps/web/src/features/plugins/runtime/plugin-host.ts",
  SCHED: "apps/web/src/features/plugins/runtime/plugin-scheduler.ts",
  VIRTUAL: "apps/web/src/features/plugins/lib/virtual-books.ts",
  KV: "apps/web/src/platform/local-store.ts",
  DOCS: "apps/web/src/features/plugins/runtime/plugin-backend.ts",
  SECRETS: "apps/web/src/platform/secret-store.ts",
  BLOB: "apps/web/src/platform/blob-store.ts",
  HTTP: "apps/web/src/platform/http-client.ts",
  EXPORT: "apps/web/src/platform/export-file.ts",
  PICKER: "apps/web/src/features/library/lib/pick-book-files.ts",
  EXTERNAL: "apps/web/src/platform/external-link.ts",
  EVENTS: "apps/web/src/platform/domain-events.ts",
  EVENTROSTER: "apps/web/src/domain/events.ts",
  APPEVENTS: "apps/web/src/platform/app-events.ts",
  COREVENTS: "packages/core/src/events.ts",
  RUST: "apps/desktop/src-tauri/src/lib.rs",
  APPLY: "apps/desktop/src-tauri/src/storage/apply.rs",
  SYNC: "apps/web/src/platform/sync/sync-scheduler.ts",
  SYNCCONNECT: "apps/web/src/platform/sync/connect.ts",
  SYNCENGINE: "apps/web/src/platform/sync/sync-engine.ts",
  SYNCTRANSPORT: "apps/web/src/platform/sync/transport-registry.ts",
  ROAM: "apps/web/src/platform/roaming-preferences.ts",
  ACCOUNTUI: "apps/web/src/features/settings/sections/SyncAccountGroup.tsx",
  BACKUP: "apps/web/src/features/settings/lib/backup-io.ts",
  DATAUI: "apps/web/src/features/settings/sections/DataSyncPanel.tsx",
  WIPE: "apps/web/src/features/settings/lib/delete-all-data.ts",
  DIAG: "apps/web/src/features/settings/lib/diagnostics.ts",
  UPDATE: "apps/web/src/features/update/lib/software-update.ts",
  WHATSNEW: "apps/web/src/features/update/hooks/useWhatsNewDialog.ts",
  WINDOW: "apps/web/src/features/navigation/components/WindowCaptionControls.tsx",
  ERRORS: "packages/core/src/errors.ts",
  MARKET: "apps/web/src/features/plugins/runtime/marketplace.ts",
  DICT: "plugins/dictionary/src/index.ts",
  DICTTOOLS: "plugins/dictionary/src/agent-tools.ts",
  DICTVIEWS: "plugins/dictionary/src/views.ts",
  DICTEXPORT: "plugins/dictionary/src/export.ts",
  RSS: "plugins/rss-reader/src/index.ts",
  RSSTOOLS: "plugins/rss-reader/src/agent-tools.ts",
  RSSVIEWS: "plugins/rss-reader/src/views.ts",
  RSSFEED: "plugins/rss-reader/src/feed.ts",
  TTS: "plugins/tts/src/index.ts",
  SENTENCE: "plugins/sentence-reader/src/index.ts",
  THEMES: "plugins/editorial-themes/manifest.json",
  WEBDAV: "plugins/webdav-sync/src/index.ts",
};

export const groups: { name: string; rows: Capability[] }[] = [
  { name: "书库与内容生命周期", rows: [
    cap("LIB01", "枚举/查询书籍与书目元数据", "实装", actor("接通", "list_books[全局] / get_book_overview[双域]", "查询工具"), actor("接通", "library.queries.books.list/get", "只读领域"), ["LIB","LIBTOOLS","LIBPORT","CTX"], "书架；RSS 订阅校验", "Agent 读模型不含封面和原文件；字段不能借元数据查询全部泄露"),
    cap("LIB02", "修改标题/作者", "实装", actor("接通", "update_book", "写工具"), actor("接通", "library.commands.books.editMetadata", "写领域"), ["LIB","LIBUI","SHELFTOOLS","CTX"], "书架；Agent", "已有单项写，批量与冲突另列"),
    cap("LIB03", "收藏/取消收藏", "实装", actor("接通", "update_book.starred", "写工具"), actor("接通", "library.commands.books.setStarred", "写领域"), ["LIB","LIBUI","SHELFTOOLS","CTX"], "书架；Agent", "按对象授权与写回执仍需基线回归"),
    cap("LIB04", "删除单本书", "实装", actor("接通", "delete_book + 用户批准", "受控写工具"), actor("接通", "library.commands.books.remove", "写领域/风险策略"), ["LIB","LIBUI","SHELFTOOLS","CTX"], "书架；Agent；RSS", "Agent 有批准环节；插件是已授权直接写，不等价于逐次批准"),
    cap("LIB05", "批量删除书籍", "实装", actor("部分", "可逐个 delete_book，无批次契约", "批量受控工具"), actor("部分", "可循环 remove，未开放 removeMany", "批量写与逐项结果"), ["LIB","LIBUI","SHELFTOOLS","CTX"], "书架多选", "循环单项不等于宿主批量语义；需原子性/部分成功契约"),
    cap("LIB06", "导入已有支持格式的书籍字节", "实装", absent("用户选文件后导入工具"), actor("部分", "library.commands.books.importBook", "导入任务"), ["IMPORT","LIB","CTX","REGISTRY"], "书架导入/拖放/系统打开", "Agent 无导入工具；插件有字节入口，无完整进度/取消/FileRef"),
    cap("LIB07", "识别格式/DRM/损坏文件并报告", "实装", absent("查询导入能力/失败原因"), actor("部分", "importBook 间接触发", "格式能力与错误契约"), ["IMPORT","READER","SESSION","CTX"], "导入与阅读加载", "不能由 BookFormat enum 推断任意文件可读"),
    cap("LIB08", "查询/读取书籍原文件与本地可用性", "实装", absent("受控资源查询"), absent("Book ResourceRef 查询/导出"), ["BLOB","SESSION","LIB","API"], "阅读加载；备份；同步", "当前 BookSummary 不提供源文件资源；不可开放任意路径"),
    cap("LIB09", "提取/显示封面与封面可用状态", "实装", actor("部分", "present_books 间接显示书卡", "封面资源查询/呈现"), absent("封面 ResourceRef"), ["ENRICH","LIB","PRESENT","API"], "书架；Agent 书卡；封面后台补齐", "Agent 书卡由宿主解析，模型/插件没有封面字节接口"),
    cap("LIB10", "缺失封面/元数据后台补齐", "实装", absent("状态查询/受控重试"), absent("状态查询/受控重试"), ["ENRICH","APP","COREVENTS"], "scheduleCatchUpEnrichment / enrichFromOpenBook", "宿主后台任务已存在；不是新增插件算法要求"),
    cap("LIB11", "重复检测、同源书合并和 ID 重定向", "实装", absent("预览后批准合并"), absent("预览后批准合并"), ["DEDUPE","LIB","APPLY"], "导入去重；同步后 reconcileDuplicateBooks", "查询候选与合并结果映射未公开"),
    cap("LIB12", "创建/幂等绑定虚拟书并更新标题", "实装", actor("扩展", "RSS subscribe_feed[全局]", "内容创建工具/贡献消费"), actor("接通", "addVirtualBook，同 binding 更新标题", "插件自有内容领域"), ["CTX","VIRTUAL","RSSFEED","RSSTOOLS"], "RSS", "不是所有虚拟书创建都自动成为 Agent 工具；仅 RSS 提供一例"),
    cap("LIB13", "移除插件自有虚拟书", "部分", actor("部分", "delete_book 通用删除；无 RSS 退订工具", "受控删除工具"), actor("部分", "removeVirtualBook", "自有内容删除回执"), ["CTX","RSSVIEWS","SHELFTOOLS"], "RSS 退订；书架删除后订阅清理", "removeVirtualBook 捕获删除错误后仍解绑，不能算可靠删除完成"),
    cap("LIB14", "虚拟内容修订/离线缓存/当前书刷新", "部分", actor("扩展", "RSS refresh_feed[全局]", "内容刷新工具"), actor("部分", "contentProviders.load + 私有缓存", "revision/失效/重载契约"), ["VIRTUAL","RSSFEED","RSSVIEWS","API"], "RSS", "订阅缓存更新不是通用内容版本协议；在读书/旧位置失效未闭合"),
    cap("LIB15", "列出集合及其成员", "实装", actor("接通", "list_collections[全局]", "查询工具"), actor("接通", "library.queries.collections.list/booksIn", "只读领域"), ["LIB","SHELFTOOLS","CTX"], "书架；Agent", "集合单归属模型保持不变"),
    cap("LIB16", "创建/重命名集合", "实装", actor("接通", "manage_collection[全局]", "写工具"), actor("接通", "collections.create/rename", "写领域"), ["LIB","SHELFTOOLS","CTX"], "书架；Agent", "书内不注册全局集合管理工具是明确 scope 策略"),
    cap("LIB17", "删除集合", "实装", actor("接通", "delete_collection[全局] + 批准", "受控写工具"), actor("接通", "collections.remove", "写领域/风险策略"), ["LIB","SHELFTOOLS","CTX"], "书架；Agent", "删除集合与删除其中书籍是不同操作"),
    cap("LIB18", "批量分配/移出集合", "实装", actor("接通", "manage_collection.assign[全局]", "批量写工具"), actor("接通", "collections.assignBooks", "批量写领域"), ["LIB","SHELFTOOLS","CTX"], "书架拖放/多选；Agent", "移动书籍只是成员变更，不是文件移动"),
  ] },
  { name: "正文、检索与位置", rows: [
    cap("TXT01", "读取抽取章节目录", "实装", actor("接通", "get_toc", "查询工具"), actor("接通", "library.queries.books.getToc", "正文查询"), ["TEXT","TEXTPORT","TEXTTOOLS","LIB"], "Agent；抽取正文管线", "同叫 TOC：模型输出不带 hrefs，插件也不带；不是原书完整目录"),
    cap("TXT02", "读取原书分层导航目录及 href", "实装", actor("部分", "BookTextPort.hrefs 内部可供 open_book", "结构化导航目录工具"), absent("分层目录 + Location"), ["READER","WORKSPACE","READTOOLS","TEXTPORT"], "阅读目录", "Agent 内部映射不等于完整目录工具输出；索引不等于印刷章号"),
    cap("TXT03", "按抽取章节读正文/分段", "实装", actor("接通", "read_chapter(part)，带剧透控制", "分段读取工具"), actor("接通", "library.queries.books.getChapterText", "正文查询"), ["TEXT","TEXTTOOLS","LIB"], "Agent；章节摘要", "插件整章字符串不含坐标/语言/版本；Agent 分段不是渲染分页"),
    cap("TXT04", "查询无文本/未抽取/就绪", "实装", actor("部分", "get_toc/read_chapter 内部 getTextStatus", "显式可用性查询"), absent("正文任务状态查询"), ["TEXT","TEXTPORT","TEXTTOOLS"], "Agent 正文工具", "port 只有 ok/unextracted/textless，缺处理中/部分失败的正式模型"),
    cap("TXT05", "启动、重建、暂停让路正文抽取", "实装", absent("请求准备正文/任务状态"), absent("可取消正文准备任务"), ["TEXT","APPEVENTS","SESSION"], "书籍导入/阅读需求优先调度", "任务控制仍在宿主；reader-demand-activity 非公开插件事件"),
    cap("TXT06", "当前书及跨书多查询正文检索", "实装", actor("接通", "search_book_text，scope/剧透约束", "检索工具"), absent("授权范围正文检索"), ["TEXT","TEXTPORT","TEXTTOOLS"], "Agent", "结果为 snippet+章节 offset，不是精准可渲染范围；当前共享文本扫描而非通用 FTS API"),
    cap("TXT07", "引擎全文精确搜索并返回 CFI", "引擎", absent("精确命中/位置工具"), absent("精确搜索任务"), ["ENGINE","READER","READTOOLS"], "Foliate search 已有；未见内置全文搜索 UI 接入", "不能把引擎已有说成产品 UI 已有；Agent 文本检索不可替代位置搜索"),
    cap("TXT08", "搜索分页、取消、背压和过期查询淘汰", "待建", absent("有界搜索任务"), absent("有界搜索任务"), ["ENGINE","API","WIRE"], "无完整公共实现", "引擎局部 cancel 不等于端到端插件/Agent 任务协议"),
    cap("TXT09", "读取当前可见文本/阅读游标", "实装", actor("自动", "ReadingCursor 进入书内每轮 grounding", "按需读当前会话 + 自动 grounding"), actor("部分", "选择/动作回调仅给局部上下文", "会话快照与范围查询"), ["READER","GROUND","THREAD","API"], "书内 Agent；文本单元导航", "Agent 自动上下文并无独立快照工具；插件不能随时查询视口"),
    cap("TXT10", "选区附近句段上下文", "实装", actor("自动", "TurnAttachment / grounding context", "有来源的范围读取"), actor("部分", "selectionActions.run(input.context)", "可按范围查询"), ["TEXTACTIONS","GROUND","API","DICT"], "Ask AI；Dictionary", "只在特定回调拿到，不代表任意范围读取"),
    cap("TXT11", "书内脚注/链接目标解析与预览", "实装", absent("引用目标查询/宿主预览"), absent("书内链接 ResourceRef/预览"), ["ENGINE","READER","API"], "ReaderFootnotePopover", "DOM 与样式保持宿主所有；只开放语义目标"),
    cap("TXT12", "书内图片读取与灯箱缩放预览", "实装", absent("受控图片查询/预览"), absent("图片 ResourceRef/预览"), ["READER","BLOB","API"], "ReaderImageLightbox", "灯箱存在不等于模型已有图像输入工具"),
    cap("TXT13", "统一位置/范围解析、校验、版本与失效", "部分", actor("部分", "open_book 接受 anchor/chapterHref/index", "宿主签发 Location/Range"), actor("部分", "goTo 接受 cfi/href", "宿主签发 Location/Range"), ["ENGINE","NAV","READTOOLS","API"], "目录/标注/Agent/RSS", "缺稳定跨来源引用和 content generation；插件不能靠自行造 CFI 补齐"),
  ] },
  { name: "阅读会话与呈现控制", rows: [
    cap("READ01", "打开书/恢复保存位置", "实装", actor("部分", "open_book 返回 opened:true 仅表示派发", "等待 ready 的导航工具"), actor("部分", "reading.commands.openBook void", "导航命令 + 回执"), ["SESSION","READERPORT","READTOOLS","CTX"], "书架；Agent；RSS", "两端共同缺实际开书成功回执，不只是插件缺口"),
    cap("READ02", "关闭当前书并返回书架", "实装", absent("关闭指定会话工具"), absent("关闭指定会话命令"), ["SESSION","WORKSPACE","APP","API"], "阅读关闭/完成页", "开与关应成对；失效 SessionRef 不可关闭新书"),
    cap("READ03", "按章节/标注/href/CFI 跳转", "实装", actor("部分", "open_book(章节索引/标注/anchor/href)", "验证后导航工具"), actor("部分", "reading.commands.goTo(cfi/href)", "导航命令 + 实际落点"), ["READTOOLS","READERPORT","CTX","NAV"], "阅读目录/标注；Agent；RSS 文章", "Agent 比插件多索引解析，但共同缺 ready/completion；无位置标注可退化成仅开书"),
    cap("READ04", "前后翻页、章节、书首书尾", "实装", absent("导航步骤工具"), absent("导航步骤命令"), ["READER","SHORTCUT","API","REGISTRY"], "键盘/页面按钮/滚轮", "不得以 open_book 近似所有翻页语义"),
    cap("READ05", "按进度/固定版式页索引定位", "实装", absent("进度/页位置工具"), absent("seek 命令"), ["READER","WORKSPACE","ENGINE","API"], "阅读进度拖动", "页索引/印刷页标签/重排页数必须区分"),
    cap("READ06", "导航历史 back/forward 及可用性", "引擎", absent("导航历史工具"), absent("共享历史查询/命令"), ["HISTORY","ENGINE","API","READTOOLS"], "Foliate history；未见完整共享 UI 命令接入", "引擎指针移动不等于导航成功；公共历史所有权未建立"),
    cap("READ07", "统一当前书/位置/加载/历史快照", "部分", actor("自动", "书内 scope+cursor 注入，非可调用查询", "显式会话查询工具"), actor("部分", "session 未来事件 + stats 持久读", "当前会话快照"), ["SESSION","THREAD","API"], "ReaderWorkspace；Agent 每轮上下文", "宿主状态分散在组件/引擎，尚无统一快照；中途启用插件无法重建全部当前状态"),
    cap("READ08", "会话开关/章节/进度事件", "实装", actor("自动", "宿主向线程传递 cursor/scope", "有限可观察会话状态"), actor("部分", "services.session.subscribe 四事件", "含 ready/reason/origin/generation 事件"), ["APPEVENTS","THREAD","API","DICTTOOLS"], "Dictionary 缓存当前书标题", "四事件存在，但并无 ready/精确位置/历史/模式事件"),
    cap("READ09", "阅读沉浸/显示隐藏控制层", "实装", absent("有用户意图的呈现命令"), absent("会话呈现命令"), ["WORKSPACE","READER","SHORTCUT"], "空格/内容点击/滚动隐藏", "属于宿主运行态，不因不持久化而拒绝抽象"),
    cap("READ10", "目录/注释/外观/聊天面板开关", "实装", absent("打开指定语义面板"), absent("面板导航服务"), ["WORKSPACE","UI","MENU","API"], "Reader header", "参数化面板操作，不是允许访问 Jotai atom"),
    cap("READ11", "阅读面板尺寸/布局与焦点恢复", "实装", absent("受控面板布局/焦点意图"), absent("声明式面板布局/关闭回调"), ["WORKSPACE","READER","RENDER"], "聊天/目录 resize；阅读焦点", "不能用插件任意 DOM 或抢焦点代替"),
    cap("READ12", "固定版式自动适配；图片缩放/平移/旋转", "实装", absent("格式适用的呈现工具"), absent("呈现状态/命令"), ["READER","ENGINE"], "固定版式自动适配；图片灯箱交互", "已核对图片灯箱缩放；不把它算作书页手动缩放控件"),
    cap("READ13", "读取/建立/清除文本选区", "实装", actor("部分", "自动接收附件，无设置选区工具", "Range 查询/受控选择"), actor("部分", "动作输入有选区，无通用 get/set/clear", "选区查询/命令"), ["READER","ENGINE","TEXTACTIONS","API"], "选择菜单；Agent 附件；Dictionary", "固定版式的当前产品限制需按格式报告"),
    cap("READ14", "临时范围强调/搜索标记及释放", "引擎", absent("受控临时呈现"), absent("插件所属 overlay"), ["ENGINE","READER","UNITS"], "文本单元 wash；引擎选区/overlayer", "用户高亮和临时强调分离，不能写 annotation 充当搜索标记"),
    cap("READ15", "贡献句子/段落等分段模式", "实装", actor("未接", "无算法注册工具", "不开放：模型不注册运行代码"), actor("接通", "readerModes.register(text-unit-navigator)", "模式贡献"), ["API","CTX","SENTENCE","UNITS"], "sentence-reader", "只开放分段策略，不是任意渲染器/格式解码器"),
    cap("READ16", "启停模式/上下一单元/跟随/回当前", "实装", absent("阅读单元控制工具"), absent("模式状态与控制命令"), ["UNITS","WORKSPACE","SHORTCUT"], "文本单元工具栏；快捷键", "贡献模式不等于能通过 API 控制模式"),
    cap("READ17", "列声音并合成音频的提供者", "实装", actor("部分", "update_settings 可改 TTS 非敏感设置", "受控声源选择"), actor("接通", "voiceProviders.register/listVoices/synthesize", "语音贡献"), ["TTS","CTX","API","AUDIO"], "tts；宿主系统语音回退", "Agent 不能借设置接口声称已经触发朗读"),
    cap("READ18", "开始/停止朗读、播放位置与 fallback 状态", "实装", absent("朗读控制工具"), absent("朗读会话服务"), ["AUDIO","UNITS","API"], "文本单元朗读按钮", "宿主拥有音频播放/预取/回退；两端都无直接控制"),
    cap("READ19", "完成页、标记读完/撤销读完", "实装", actor("接通", "update_book.finished", "状态写工具"), actor("接通", "reading.commands.setFinished", "状态写领域"), ["READING","READER","SHELFTOOLS","CTX"], "完成页；书架；Agent", "状态写接通；导航到完成页是另一个呈现行为"),
    cap("READ20", "跨书/并发导航的取消、序列化与回执", "待建", actor("部分", "open_book sequential 只约束工具调度", "全来源导航事务"), actor("部分", "requestId 派发，不是完成协议", "全来源导航事务"), ["READTOOLS","NAV","APP","HISTORY"], "现有局部防重", "用户/Agent/插件竞争、失败不推进历史仍缺统一裁决"),
  ] },
  { name: "标注与阅读统计", rows: [
    cap("ANN01", "列出/按书按词按类型检索标注", "实装", actor("接通", "get_annotations；类型在工具层过滤", "查询工具"), actor("接通", "annotations.queries.list", "只读领域"), ["ANNOT","ANNDB","LIBTOOLS","CTX"], "阅读注释；全局 Agent 注释；Agent", "列表已接通，分页/稳定游标另列"),
    cap("ANN02", "创建高亮", "实装", actor("接通", "create_annotation(kind=highlight)", "写工具"), actor("接通", "annotations.commands.createHighlight", "写领域"), ["ANNOT","ANNTOOLS","CTX","TEXTACTIONS"], "选择菜单；Agent", "来源与 Range 校验仍受 TXT13 限制"),
    cap("ANN03", "创建下划线样式", "实装", actor("未接", "create_annotation 未传 style", "标注样式参数"), actor("接通", "createHighlight(style=underline)", "写领域"), ["ANNOT","ANNTOOLS","TEXTACTIONS","API"], "选择菜单", "同一 host 命令支持 style，但 Agent adapter/tool 丢了该参数"),
    cap("ANN04", "高亮改色/删除", "实装", actor("接通", "edit_annotation / delete_annotation+批准", "受控写工具"), actor("接通", "recolorHighlight/removeHighlight", "写领域"), ["ANNOT","ANNTOOLS","CTX"], "标注菜单；Agent", "修改高亮文本/改样式不是当前命令的已支持语义"),
    cap("ANN05", "创建/编辑/删除笔记", "实装", actor("接通", "create/edit/delete_annotation", "受控写工具"), actor("接通", "createNote/updateNote/removeNote", "写领域"), ["ANNOT","ANNTOOLS","CTX"], "NoteEditor；Agent", "可无位置笔记；删除 Agent 批准和插件授权不是同一种策略"),
    cap("ANN06", "读取/删除 ask 问题轨迹", "实装", actor("接通", "get_annotations / delete_annotation+批准", "查询/受控删除"), actor("部分", "可 list ask，未导出 removeAsk", "查询/受控删除"), ["ANNOT","ANNTOOLS","CTX"], "Agent；注释视图", "同一领域 removeAsk 有实现但 plugin-context 省略"),
    cap("ANN07", "自动记录书内问题轨迹", "实装", actor("自动", "thread 轮末 recordAsk → createAsk", "保留自动管线"), actor("未接", "createAsk 为 agent-only", "不开放：禁止伪造问题历史"), ["ANNOT","THREAD","PORTS"], "书内 Agent", "自动行为不算模型可以任意调用的写工具"),
    cap("ANN08", "按 ID 读取、分页、批量/版本冲突标注操作", "部分", actor("部分", "全量 list 后找 ID；可循环单项", "有界查询/批量工具"), actor("部分", "list+单项命令，无 ID getter/游标/CAS", "有界领域操作"), ["ANNDB","ANNOT","ANNTOOLS","API"], "现有列表与单项动作", "底层 annotation_get 已有；整个行要求的批次/版本协议未有"),
    cap("ANN09", "标注变化与远端失效观察", "部分", actor("自动", "每轮读快照，不订阅工具", "自动刷新/按需查询"), actor("部分", "annotations.events.subscribe", "完整授权 change feed"), ["EVENTROSTER","EVENTS","CTX","SYNC"], "宿主注释 revision", "GAP09/GAP11；同步投影变化不等同本地领域广播"),
    cap("STAT01", "单书/全库/总览已结算阅读统计", "实装", actor("接通", "get_reading_stats", "查询工具"), actor("接通", "reading.queries.stats.forBook/list/overview", "统计查询"), ["READING","SHELFTOOLS","CTX"], "StatsWorkspace；Agent", "已结算持久数据与当前会话 scratch 必须区分"),
    cap("STAT02", "周月年/连续阅读/热图/时段/成就派生", "实装", actor("部分", "get_reading_stats 格式化时长/活跃天等", "有界统计查询/工具侧计算"), actor("部分", "daily 可派生；BookStats 无小时分布", "原始统计口径+插件计算"), ["STATS","STATUI","READING","SHELFTOOLS"], "统计页", "不是每一种图表都要新 host API；小时分布不是 daily 可以还原的数据"),
    cap("STAT03", "当前未结算时长/会话及精确观察时钟", "实装", absent("统计快照含 provisional 标记"), absent("统计快照含 pending session"), ["TIME","RUST","READING"], "阅读计时与退出 flush", "已有 reading_sessions_pending IPC，不在 Agent/插件统计读模型"),
    cap("STAT04", "计时/位置累积、小时结算和重启恢复", "实装", actor("未接", "宿主自动采集", "不开放：不得伪造阅读"), actor("未接", "宿主自动采集", "不开放：只读统计/真实阅读操作"), ["TIME","RUST","APPLY"], "useReadingTimeTracker", "底层 accrue/position/flush/import/genesis 不是插件写权限"),
    cap("STAT05", "book.sessionRecorded 正式事件", "实装", actor("自动", "下轮读统计，无模型事件订阅", "运行时数据刷新"), actor("部分", "runtime roster 有，public union 无", "同源事件契约"), ["EVENTROSTER","API","COREVENTS"], "领域订阅实现", "公开类型漂移；不能把 legacy timeRecorded 当今天的实际事件"),
  ] },
];

groups.push(
  { name: "应用导航、命令与配置范围", rows: [
    cap("UI01", "书架/Agent/统计/设置与集合页面导航", "实装", actor("部分", "open_book；present_books 仅书卡", "语义导航工具"), actor("部分", "openBook；插件自己的 page", "语义路由服务"), ["APP","UI","COMMAND","API"], "主导航；命令面板", "无通用 openSettings/openCollection/goStats；不公开 Router/Jotai"),
    cap("UI02", "书架搜索/布局/排序/分组/多选", "实装", actor("部分", "list_books 查数据，不改变视图", "查询视图状态/受控设置"), absent("视图状态与选择集服务"), ["SHELF","SHELFUI","COMMAND"], "书架；命令面板", "数据查询不是切换用户当前列表；多选不是用户授权批量删除"),
    cap("UI03", "发现/执行宿主命令与可用条件", "实装", absent("可审计的命令调用"), actor("部分", "commands.register 只贡献自己的命令", "命令注册与受控调用分离"), ["COMMAND","SHORTCUT","CTX"], "命令面板/快捷键", "不能把菜单 ID 或命令 label 当稳定 RPC；需参数 schema、条件、回执"),
    cap("UI04", "快捷键查询、重绑、冲突与重置", "实装", absent("快捷键设置工具"), actor("部分", "贡献默认 shortcut，无重绑查询", "命令绑定与冲突查询"), ["SHORTCUT","SHORTUI","API"], "快捷键设置页；插件命令", "默认快捷键不是用户实际绑定；菜单快捷键与原生快捷键需一致"),
    cap("UI05", "菜单可见/溢出位置及自定义重排", "实装", actor("接通", "get_settings/update_settings menus.*", "结构化设置工具"), actor("接通", "settings domain menus.* 按路径授权", "结构化设置领域"), ["MENU","MENUSTATE","SETTINGS","SETTOOLS"], "菜单设置；插件 header/selection", "可改布局不代表可调用菜单动作；具体 8 个路径另逐项列出"),
    cap("CFG01", "设置 discover/read/update 与动态选项", "实装", actor("接通", "get_settings/update_settings", "设置工具"), actor("接通", "settings.queries.discover/read + commands.update", "路径授权设置领域"), ["SETTINGS","SETDOMAIN","SETTOOLS","CTX"], "Agent；Theme Schedule；TTS options", "路径、scope、可写性运行时发现；设置 API 接通不证明值有消费者"),
    cap("CFG02", "全局/本书/全书阅读设置覆盖", "实装", actor("接通", "update_settings target", "显式作用域写工具"), actor("接通", "settings.commands.update target", "显式作用域写领域"), ["SETDOMAIN","SETTINGS","OVERRIDES","SETTOOLS"], "AppearancePanel；Agent", "all-books 写全局并更新 overrides，不等于清除所有覆盖"),
    cap("CFG03", "清除覆盖/恢复默认/查询值来源", "实装", absent("reset + effective value/provenance"), absent("reset + effective value/provenance"), ["PREFS","OVERRIDES","SETTINGS"], "阅读外观设置", "当前 update 不能表达 inherit/delete override；不是写默认值可替代"),
    cap("CFG04", "阅读对齐 reading.textAlign", "实装", absent("补入设置目录"), absent("补入设置目录"), ["PREFS","SETTINGS","READER"], "阅读设置/渲染", "实际字段存在但 settings catalog 缺失"),
    cap("CFG05", "固定版式颜色 reading.fixedLayoutColor", "实装", absent("补入设置目录"), absent("补入设置目录"), ["PREFS","SETTINGS","READER"], "固定版式外观", "不是 reading.theme 的同义项；catalog 缺失"),
    cap("CFG06", "更新内容弹窗 general.whatsNewDialog", "实装", absent("补入设置目录"), absent("补入设置目录"), ["GENERAL","WHATSNEW","SETTINGS"], "GeneralPanel / useWhatsNewDialog", "开关实际有效，但 catalog 漏项"),
    cap("CFG07", "AI 提供商/端点/密钥配置", "实装", actor("部分", "只读 provider/credentialConfigured；无密钥", "打开宿主敏感配置流程"), actor("部分", "受权读非敏感存在状态；无宿主 key", "打开宿主敏感配置流程"), ["AICONFIG","AICONFIGUI","SETTINGS","SECRETS"], "AIConfigPanel", "不开放：读取宿主密钥；不能把 readonly provider 算作可切换提供商"),
    cap("CFG08", "模型目录刷新、连接测试与模型能力", "实装", actor("部分", "设置 discover 给模型选项", "连接诊断/能力查询"), actor("部分", "settings discover 动态选项", "连接诊断/能力查询"), ["MODELCATALOG","AICONFIGUI","SETTINGS"], "AI 配置页", "选择已缓存模型不等于能刷新/测试连接"),
    cap("CFG09", "插件非敏感设置的动态路径", "实装", actor("接通", "plugins.<id>.<field> get/update_settings", "参数配置工具"), actor("接通", "自有路径默认授权；他者路径需 grant", "隔离设置领域"), ["CTX","SETTINGS","SETDOMAIN"], "TTS/RSS/Theme Schedule 等", "插件启用/声明决定目录；secret/password 字段不暴露；配置不等于执行插件命令"),
    cap("CFG10", "设置变化事件/外部写入刷新", "部分", actor("自动", "每次读当前目录/值", "运行时刷新"), actor("部分", "settings events + storage.onChange", "有版本/来源的观察"), ["SETDOMAIN","CTX","WORKER","KV"], "Theme Schedule；插件设置视图", "GAP03/09/11：失败回滚、远端写与异步 callback 仍未闭合"),
  ] },
  { name: "对话、Agent 交互与推理", rows: [
    cap("AI01", "读取书内/全局对话及搜索历史", "实装", actor("接通", "search_conversation/get_recent_turns", "有界查询工具"), actor("接通", "conversations.queries getBookThread/listThreads/getThread", "受权只读领域"), ["CHATDOMAIN","CHATPORT","CHATTOOLS","CTX"], "Agent；聊天历史", "插件拿到 transcript 不等于自动得到画像/记忆；当前查询范围和列表量需约束"),
    cap("AI02", "创建/切换/清空全局线程和书内聊天", "实装", absent("线程管理/受控清空工具"), absent("线程导航/受控清空命令"), ["CHAT","AGENTUI","CHATCONTROL","REGISTRY"], "AgentWorkspace；ChatPanel", "clearConversation 已有，但插件 conversations 无 commands；不可伪造 role 消息"),
    cap("AI03", "发送/流式生成/停止/重试聊天回合", "实装", actor("自动", "用户回合驱动 thread.run", "运行时保持宿主所有"), actor("部分", "llm.ask 是独立推理，不是向聊天发送", "受控 conversation turn 意图"), ["THREAD","CHATCONTROL","CHATUI","RUNTIME","API"], "书内聊天；全局聊天", "自动递归对话/伪造用户消息不开放；用户触发的发送和停止需意图契约"),
    cap("AI04", "提问、选项澄清、批准/拒绝高风险动作", "实装", actor("接通", "ask_user + InteractionPort", "宿主交互工具"), actor("部分", "表单可收输入，无通用权限批准票据", "宿主拥有的一次性批准流程"), ["INTERACTION","ANNTOOLS","SHELFTOOLS","API"], "Agent question/permission cards", "确认 UI 与授权决策分离；插件自画 Yes 按钮不是 host approval"),
    cap("AI05", "Agent 展示可点击书卡与词典卡", "实装", actor("接通", "present_books[全局]；插件 tool details.wordCards", "结构化结果呈现"), actor("部分", "agentTools 固定 word-card details", "类型化呈现结果"), ["PRESENT","EXTOOLS","API","DICTTOOLS"], "Agent 书卡；Dictionary 单词卡", "工具结果卡与 PluginView 协议不同，不能任意互换"),
    cap("AI06", "一次性文本/结构化/流式 LLM 推理", "实装", actor("自动", "Runtime ask + 线程推理", "运行时服务"), actor("接通", "services.llm.ask fast/smart + schema/onText", "受预算约束的推理服务"), ["RUNTIME","CTX","API","DICT"], "Dictionary；Agent 后台管线", "流式回调存在，但无公开 AbortSignal/任务预算/用量回执"),
    cap("AI07", "推理取消、超时、用量/预算/成本可见性", "部分", actor("部分", "线程 abort；model API 内部控制", "统一任务/预算"), actor("部分", "ask 无公开取消/用量字段", "统一任务/预算"), ["THREAD","RUNTIME","CTX","WIRE"], "聊天 Stop；模型错误处理", "宿主线程停止不是所有插件推理任务的可取消协议"),
    cap("AI08", "书内 scope/游标/选区自动 grounding", "实装", actor("自动", "thread + grounding-context", "自动且有来源的上下文"), actor("部分", "context/retrieval provider 能补充，不能覆写核心", "受限上下文贡献"), ["THREAD","GROUND","EXTOOLS"], "书内 Agent", "自动注入不等于独立工具；不允许插件注入更高优先级系统策略"),
    cap("AI09", "剧透边界、请求允许超前内容", "实装", actor("接通", "read_chapter/search_book_text/query_book_graph + 批准", "宿主策略"), actor("部分", "book text domain 无同样的模型剧透审批", "数据授权与 Agent 剧透策略分开"), ["SPOILER","TEXTTOOLS","GRAPHTOOLS","LIB"], "书内 Agent", "访问权限不是剧透许可；插件提供上下文需要 provenance/fence 政策"),
    cap("AI10", "注册供模型使用的插件工具", "实装", actor("扩展", "extraTools(scope) 进入真实 registry", "受 scope/授权控制工具"), actor("接通", "agentTools.register", "工具贡献"), ["REGISTRY","PORTS","EXTOOLS","DICTTOOLS","RSSTOOLS"], "Dictionary 3 个；RSS 3 个", "插件安装/启用后才存在；不能将拥有插件 UI 视为已经有 Agent 工具"),
    cap("AI11", "每轮上下文 provider", "实装", actor("自动", "plugin context provider 注入线程", "受预算/来源约束消费"), actor("接通", "agentContextProviders.register", "上下文贡献"), ["EXTOOLS","THREAD","API"], "宿主已接线；本仓六插件未注册该类", "无消费者是 adoption 缺口，不是 host 未实现"),
    cap("AI12", "按需插件检索 provider", "实装", actor("扩展", "自动生成 retrieve 工具", "按需有界检索工具"), actor("接通", "agentRetrievalProviders.register", "检索贡献"), ["EXTOOLS","DICTTOOLS","REGISTRY"], "Dictionary saved-vocabulary", "名称隔离/限量由 adapter 控制；查询结果不是可信指令"),
  ] },
  { name: "长期记忆、画像与图谱", rows: [
    cap("MEM01", "查询长期记忆", "实装", actor("接通", "search_memory", "检索工具"), absent("受 scope 授权的只读 memory domain"), ["MEMTOOLS","MEMORYPORT","PORTS","API"], "Agent", "没有 plugin memory domain；不能用 conversation 查询冒充记忆读取"),
    cap("MEM02", "显式记住事实/偏好", "实装", actor("接通", "remember", "有来源的写工具"), actor("部分", "只能贡献 memory candidates", "候选提议，由宿主裁决"), ["MEMTOOLS","MEMORYPORT","API"], "Agent", "不开放：插件直接写记忆投影或伪造强化次数"),
    cap("MEM03", "轮后抽取/去重/强化记忆", "实装", actor("自动", "thread 轮后抽取与 reinforce", "自动管线"), actor("部分", "memoryCandidateProviders.propose", "候选贡献"), ["THREAD","MEMORYPORT","API"], "Agent 后台；本仓无候选 provider 消费者", "自动管线已实装；buildMemory 开关未接消费，见逐项设置"),
    cap("MEM04", "记忆巩固、修订/替代/遗忘", "实装", actor("自动", "maintenance → consolidateIfNeeded → applyMemoryChanges", "自动管线+受控反馈工具"), absent("候选/反馈接口，不直接改投影"), ["MAINT","CONSOLIDATE","MEMORYPORT","APPLY"], "空闲维护", "不能沿用旧说明声称全部 consolidation 未实现；模型无独立遗忘工具"),
    cap("MEM05", "用户反馈记忆质量/纠错", "部分", actor("内部", "memory.feedback 事件/投影，未注册工具", "受控反馈工具"), absent("受控反馈命令"), ["COREVENTS","APPLY","MEMTOOLS"], "历史 genesis 回填；未见当前反馈 UI 入口", "事件与投影存在不代表用户/Agent 可以触发；需来源与撤销语义"),
    cap("MEM06", "读取用户画像并注入上下文", "实装", actor("自动", "ProfilePort.read → thread prompt", "自动上下文/受控查询"), absent("授权字段画像查询"), ["PROFILEPORT","THREAD","PORTS"], "Agent system prompt", "画像当前存 localKV；不是 profile.updated 的成熟投影"),
    cap("MEM07", "Onboarding 访谈写入画像", "部分", actor("内部", "onboarding.ts seed 可写端口；未见产品调用", "明确接入用户确认后的写流程"), absent("候选画像变更流程"), ["ONBOARD","PROFILEPORT","THREAD"], "访谈提示词有；独立 seed 仅导出/测试", "函数存在不能算完成的访谈→画像闭环"),
    cap("MEM08", "profile.updated / entity.resolved / entity.merged 投影", "占位", actor("内部", "事件类型/端口，并非完整实体整合", "宿主 consolidation 投影"), absent("未来只读/候选接口"), ["COREVENTS","APPLY"], "apply.rs 接受但返回无投影", "宿主自身待实现，不应归为插件 API 单纯漏导出"),
    cap("MEM09", "叙事性分类/重分类与图谱风格", "实装", actor("自动", "digest pipeline 自动分类", "管线状态+用户重分类意图"), absent("分类查询/受控重分类"), ["MAINT","RUNTIME","COREVENTS","APPLY"], "章节 digest 后台管线", "narrative 与 expository 的 fence 不同；重分类后旧 flavor 懒重建"),
    cap("MEM10", "完成章节摘要、人物/概念图生成与补齐", "实装", actor("自动", "digestBook/digestBookCatchUp + idle", "自动任务+状态/重试"), absent("图谱任务查询/候选提供"), ["MAINT","RUNTIME","GRAPHP"], "阅读后 catch-up；空闲维护", "没有公开任务进度/取消/重建入口；不能说只有函数没调用"),
    cap("MEM11", "检索书内人物/关系/概念图", "实装", actor("接通", "query_book_graph", "有 fence 的查询工具"), absent("book memory 只读领域"), ["GRAPHTOOLS","GRAPHP","API"], "Agent", "插件缺读图谱领域；原始 chapterDigests 列表不是完整安全查询"),
    cap("MEM12", "跨对话 insights 与滚动摘要", "实装", actor("接通", "get_conversation_insights[全局]；rolling summary 自动", "检索工具+自动摘要"), actor("部分", "可读 transcript，无 insights/summary 正式 API", "有来源的只读查询"), ["CHATTOOLS","THREAD","CHATPORT"], "全局 Agent；长对话", "不能将可重读对话当作已有相同摘要/洞见"),
    cap("MEM13", "可版本化导出 context bundle", "待建", absent("上下文包查询/导出工具"), absent("上下文包资源服务"), ["API","PORTS","RUNTIME","BACKUP"], "无正式 context bundle 产品能力", "这是既定方向，不是已存在宿主能力；备份 JSON 不是 context bundle"),
  ] },
  { name: "插件界面、贡献与实际消费者", rows: [
    cap("EXT01", "选择菜单动作/lookup/标注入口", "实装", actor("部分", "选择附件可触发 Agent；非调用任意 action", "语义动作意图"), actor("接通", "selectionActions.register", "声明式动作贡献"), ["API","CTX","DICT","TEXTACTIONS"], "Dictionary lookup-save", "menu contribution 是入口位置，不提供跳转/搜索本体能力"),
    cap("EXT02", "书架与阅读 header menu 入口", "实装", absent("命令工具而不是菜单 DOM 操作"), actor("接通", "headerActions.register(surface=shelf/reader)", "声明式 header 动作"), ["API","CTX","MENU","RSS","DICT"], "Dictionary/RSS 书架入口；Jumper 阅读入口可用", "Jumper 缺口不是 header 插槽，而是 TXT/D/任务语义"),
    cap("EXT03", "插件页面/对话框/视图结果与栈导航", "实装", actor("未接", "模型不渲染 PluginView 树", "通过工具结构化输出，由宿主呈现"), actor("部分", "PluginViewResult push/pop/replace/close", "宿主声明式视图"), ["API","VIEWS","RENDER","WIRE"], "Dictionary/RSS", "当前可用，但 GAP06/10 的 callback 生命周期和过期结果未闭合"),
    cap("EXT04", "列表、搜索、详情、Markdown、blocks 组合", "实装", absent("工具结果呈现，不注册任意组件"), actor("接通", "PluginView list/detail/markdown/blocks", "声明式内容视图"), ["API","RENDER","DICTVIEWS","RSSVIEWS"], "Dictionary/RSS", "宿主组件有 Table/Tree 不等于插件 schema 有；复杂数据视图另列"),
    cap("EXT05", "表单输入、动态选项、验证与提交", "实装", actor("部分", "ask_user 固定 question 交互", "结构化交互 schema"), actor("接通", "PluginFormView.onSubmit + submitMode=explicit/change", "声明式表单"), ["API","RENDER","DICTVIEWS","RSSVIEWS"], "RSS 订阅/OPML粘贴；Dictionary", "OPML 是文本粘贴而非通用选择文件服务"),
    cap("EXT06", "大列表分页/虚拟化、Tree/Table/编辑器/图像资源", "部分", absent("有界工具结果/资源引用"), actor("部分", "list 已用 PluginVirtualRows；无通用分页/Tree/Table", "按原语补全 schema"), ["API","RENDER"], "宿主 UI 库比 PluginView schema 更丰富", "虚拟行已实现，不与分页混为一谈；不能开放 React/HTML/DOM 逃生口；表格/树等需 schema 与键盘契约"),
    cap("EXT07", "Toast、持久错误、进度/取消/确认交互", "部分", actor("部分", "工具 error/interaction + streaming", "统一失败/任务呈现"), actor("部分", "showToast(string)；视图自建错误内容", "类型化 error/progress/approval"), ["API","RENDER","ERRORS","INTERACTION"], "插件 toast；Agent 工具输出", "Toast string 不能表达 stable code/retryability；错误不得借 modal 中断用户"),
    cap("EXT08", "应用/阅读主题和字体贡献", "实装", actor("部分", "settings 选择已声明主题/字体", "选择工具，不注册代码资产"), actor("接通", "manifest themes/fonts", "静态主题/字体贡献"), ["THEMES","API","SETTINGS"], "editorial-themes", "能力 catalog 含 themes/fonts，ctx 无 register 是声明式设计而非漏实现"),
    cap("EXT09", "词典查询/收藏/复习列表/CSV 导出", "实装", actor("扩展", "lookup_word/get_vocabulary/save_word", "插件工具"), actor("接通", "Dictionary 私有 storage + LLM + views/export", "现有原语组合"), ["DICT","DICTTOOLS","DICTVIEWS","DICTEXPORT"], "Dictionary", "Agent 无删词/CSV 导出工具；不应把词汇领域搬回宿主"),
    cap("EXT10", "RSS 订阅/刷新/退订/OPML/阅读文章", "实装", actor("扩展", "list_feeds/subscribe_feed/refresh_feed[全局]", "插件工具"), actor("接通", "RSS 私有 collection + content provider", "现有原语组合"), ["RSS","RSSTOOLS","RSSVIEWS","RSSFEED"], "RSS", "退订与 OPML 无 Agent 工具；刷新正在读的版本仍见 LIB14"),
    cap("EXT11", "本地 marketplace 插件清单与启用状态", "实装", absent("只读插件目录/能力查询工具"), actor("部分", "ctx.manifest/capabilities 仅自己", "自有与受控公共目录"), ["HOST","MARKET","API"], "插件管理页", "不能将仓库里存在等于用户已安装/启用；本次未读取用户安装态"),
    cap("EXT12", "安装/授权/启停/更新/回滚/卸载插件", "实装", absent("打开宿主审批流程"), absent("自管理申请，不得静默控制其他插件"), ["HOST","MARKET","RUST"], "Plugins settings", "不开放：插件静默授予自己权限/安装代码；Agent 操作也应经宿主批准"),
  ] },
  { name: "存储、网络与原生资源", rows: [
    cap("SYS01", "插件隔离 KV 同步读写镜像", "部分", actor("扩展", "通过插件工具间接使用，无 KV 工具", "不得读任意私有 KV"), actor("部分", "storage.get/set/remove/onChange", "带 durable ack 的隔离 KV"), ["CTX","WORKER","KV","DICT"], "全部有设置/状态插件", "GAP02/03：void 写和 worker mirror 不能证明持久成功"),
    cap("SYS02", "插件私有文档 collection CRUD/限量查询", "实装", actor("扩展", "Dictionary/RSS 工具通过插件访问", "插件工具封装其自有数据"), actor("接通", "storage.collection put/get/delete/list", "隔离文档服务"), ["CTX","DOCS","API","DICT","RSS"], "Dictionary words；RSS feeds", "无游标/CAS/事务/全字段搜索；bookId/anchor 是索引不是自动删除所有权"),
    cap("SYS03", "插件 schema 迁移/快照/更新回滚", "部分", actor("未接", "宿主管理安装生命周期", "不开放：模型操作迁移存储"), actor("部分", "migrate storage-only；host snapshot/restore", "quiescent + durable migration"), ["HOST","WIRE","WORKER","RUST"], "RSS legacy feeds 迁移；插件更新", "GAP01/02：快照时序与写持久屏障不完整"),
    cap("SYS04", "插件自有 secret get/set/remove", "实装", actor("未接", "不提供密钥读取工具", "不开放：密钥进模型上下文"), actor("接通", "services.secrets namespace", "隔离凭据服务"), ["CTX","SECRETS","TTS","WEBDAV"], "TTS；WebDAV", "私有 secret 不等于可读宿主 AI key/同步解密 key"),
    cap("SYS05", "插件数据导入导出/配额/同步策略", "部分", actor("扩展", "仅插件自定义工具", "插件拥有的数据操作"), actor("部分", "exportFile + 私有 CRUD；无通用配额/同步状态", "隔离数据生命周期"), ["API","DOCS","ROAM","BACKUP"], "Dictionary CSV；RSS OPML", "KV、plugin_docs、secrets、blob 的漫游/备份边界不同，不能统一宣称可同步"),
    cap("SYS06", "原生网络 HTTP 请求与响应", "实装", actor("内部", "推理端口/插件工具，无通用 fetch 工具", "有用途/域名约束网络工具"), actor("部分", "services.network.fetch", "完整有界 HTTP 服务"), ["HTTP","CTX","WIRE","WORKER","RSS","TTS"], "RSS/TTS/WebDAV", "GAP04/05：Request 语义丢失、AbortSignal 不端到端；headers/二进制也需契约测试"),
    cap("SYS07", "网络域名授权、预算、下载流和离线重试", "部分", absent("用途受限任务"), actor("部分", "network permission 是大开关，无完整流/配额", "授权/任务/缓存原语"), ["API","HTTP","WIRE","CATALOG"], "宿主内部 HTTP；各插件自行缓存", "不是给每个插件重新实现重试/缓存的理由；实时 socket 不算宿主当前产品能力"),
    cap("SYS08", "剪贴板写文本", "实装", actor("未接", "无复制工具", "用户触发的复制意图"), actor("接通", "services.clipboard.writeText", "受权剪贴板写"), ["API","CTX","TEXTACTIONS"], "选择复制；插件动作", "写文本不含读剪贴板或图片"),
    cap("SYS09", "图片复制/导出原生图片资源", "实装", absent("用户触发的图像导出"), absent("Image ResourceRef + 受权复制/导出"), ["READER","EXPORT","RUST"], "ReaderImageLightbox", "二进制 exportFile 可保存已持有字节，但无书内图像资源查询/图片剪贴板"),
    cap("SYS10", "保存文本/二进制文件与取消回执", "实装", absent("宿主文件导出工具"), actor("接通", "ui.exportFile(filename,content,mimeType) → boolean", "用户确认的文件导出"), ["EXPORT","CTX","API","DICTEXPORT"], "Dictionary CSV；原生保存", "已有取消 boolean，不应误报完全缺文件输出；没有流式 FileRef"),
    cap("SYS11", "用户选文件/目录、拖放和流式文件句柄", "实装", absent("用户授予 FileRef 后导入"), absent("受控文件选择/句柄服务"), ["PICKER","IMPORT","RUST"], "书籍导入；插件安装选择 ZIP", "不能把导入字节 API 当作文件选择器；任意路径/FS 不开放"),
    cap("SYS12", "打开外部 URL/系统关联打开/深链接路由", "实装", actor("部分", "回答链接可由用户点击，无 opener 工具", "用户意图下的受控 URL 打开"), absent("scheme 白名单外部打开/URI contribution"), ["EXTERNAL","APP","RUST"], "账号登录/购买链接；系统打开书籍", "外部 URL 打开与注册任意协议不同；OAuth ticket 不给插件"),
    cap("SYS13", "Blob 范围读取/流式读写/提交/中止", "实装", actor("内部", "正文/推理端口间接用，不读任意 blob", "受权 ResourceRef"), actor("部分", "导入/导出只支持持有的 bytes", "资源句柄/流/额度"), ["BLOB","RUST","API"], "原书阅读；同步分片；封面", "底层 get_blob/blob_write_* 不可直接暴露；跨线程大对象需 transferable/backpressure"),
    cap("SYS14", "系统字体枚举和字体资产加载", "实装", actor("部分", "settings discover reading.fontFamily", "受支持字体列表"), actor("部分", "settings options + fonts manifest", "字体资源能力"), ["RUST","SETTINGS","API"], "阅读字体选择；editorial-themes", "列表选择已可组合，不需要插件访问系统字体目录"),
    cap("SYS15", "原生日志/诊断包/崩溃报告导出与发送", "实装", absent("打开宿主脱敏诊断流程"), absent("隔离 logger + 自有诊断输出"), ["DIAG","ERRORS","RUST"], "设置 Troubleshooting；CrashFollowUpPrompt", "不得向任意插件暴露全量日志/凭据；发送需显式用户意图"),
    cap("SYS16", "检查/下载/安装更新与重启", "实装", absent("查询状态/打开更新批准流程"), absent("只读版本/更新状态；宿主执行升级"), ["UPDATE","APP","RUST","API"], "软件更新页；autoUpdate 检查", "不开放：插件静默执行更新/重启；appVersion 不是更新状态"),
    cap("SYS17", "窗口最小化/最大化/全屏/关闭/标题栏", "实装", absent("用户触发的窗口意图"), absent("受限窗口状态/命令"), ["WINDOW","APP","RUST"], "Tauri window controls/macOS traffic lights", "不开放任意窗口创建与 shell；关闭必须先等待持久化 flush"),
    cap("SYS18", "Android/iOS 遗留桥：状态栏/安全区/音量键/商店", "非桌面", absent("不开放：不在当前 desktop 产品范围"), absent("不开放：不在当前 desktop 产品范围"), ["RUST"], "cfg 分支或桌面 no-op", "Android updater/book picker/background task 和 App Store storefront 不计为桌面插件缺口"),
  ] },
  { name: "同步、账号、备份与维护", rows: [
    cap("OPS01", "同步连接/断开/立即同步/状态与积压", "实装", absent("只读状态 + 用户批准操作"), actor("部分", "syncTransports 提供后端，不控制 scheduler", "只读状态/受控同步请求"), ["SYNC","SYNCCONNECT","ACCOUNTUI","API"], "Data & Sync", "传输插件是 engine 被调用的 port，不是可以控制整套 sync 的服务"),
    cap("OPS02", "事件/Blob E2E 加解密、游标、去重/确认与重试", "实装", actor("未接", "宿主内部同步", "不开放：原始密钥/ACK/游标写"), actor("部分", "只处理 SealedEventWire/密文字节", "只贡献传输"), ["SYNCENGINE","SYNC","SYNCTRANSPORT","RUST"], "Relay/WebDAV", "不得通过插件改变确认语义或读取其他插件/账号明文"),
    cap("OPS03", "检查点/投影恢复/事件历史回填", "实装", actor("未接", "宿主内部恢复", "只读健康状态/宿主修复流程"), absent("只读健康状态/宿主修复流程"), ["RUST","SYNCENGINE","APPLY"], "checkpoint maintain/publish/bootstrap；backfill", "管理底层游标/投影不算通用插件写能力"),
    cap("OPS04", "WebDAV 等自定义密文 transport", "实装", actor("部分", "可改非敏感插件设置，不能连接", "宿主连接流程"), actor("接通", "syncTransports.register/open/session methods", "密文传输贡献"), ["API","WEBDAV","SYNCTRANSPORT"], "webdav-sync", "GAP14：session 缺 close/dispose，不能据 register.dispose 推断连接释放"),
    cap("OPS05", "偏好漫游/远端合并后的 UI 失效", "部分", actor("自动", "下一轮读取投影/配置", "一致快照与刷新"), actor("部分", "roaming KV 与 plugin docs 路径不等价", "授权 change feed + 同步策略"), ["ROAM","SYNC","APPEVENTS","DOCS"], "跨设备设置/书架/聊天刷新", "GAP09：远端应用缺逐领域订阅广播；不得让插件 replay 原始事件补洞"),
    cap("OPS06", "账号登录、连接 token、退出、删除账号", "实装", absent("打开宿主账号流程"), absent("打开宿主账号流程/匿名状态"), ["ACCOUNTUI","SYNCCONNECT","RUST","EXTERNAL"], "SyncAccountGroup", "删除远端账号和删除本地数据不同；身份 token 不向模型/插件公开"),
    cap("OPS07", "套餐/用量/购买/账单管理", "实装", absent("只读非敏感状态/用户确认跳转"), absent("非敏感状态/用户确认跳转"), ["ACCOUNTUI","EXTERNAL"], "购买/账单 portal", "远端服务契约未在本次本地代码审计验证；不开放自动付款"),
    cap("OPS08", "备份导出与合并导入", "部分", absent("宿主批准的备份任务"), absent("仅自有数据；宿主批准的备份流程"), ["BACKUP","DATAUI","RUST"], "DataSyncPanel", "v1 仅 KV/books/collections/annotations/files；独立 ai_chat/memories/plugin_docs/secret/event-log 未枚举，不能称全量备份；全量内存 JSON"),
    cap("OPS09", "删除本地全部数据", "实装", absent("打开显式二次确认流程"), absent("不开放：插件直接 wipe 用户全部数据"), ["WIPE","DATAUI","RUST"], "DELETE 文字确认", "清空本地与删账号不同；私有卸载清理不能升级成全局清空"),
    cap("OPS10", "数据目录显示/Reveal", "占位", absent("待宿主实现后暴露意图"), absent("待宿主实现后暴露意图"), ["DATAUI"], "disabled Reveal / PendingBadge", "UI 占位不能计入宿主已实现，更不能计入 Agent 或插件覆盖"),
    cap("OPS11", "事件写入、重建/验证投影、历史 genesis", "实装", actor("内部", "领域端口提交业务事件", "只走有语义领域命令"), actor("部分", "公开领域命令内部 commit", "只走有语义领域命令"), ["EVENTS","APPLY","RUST"], "commit_events/rebuild_projections/verify_projections", "不开放：任意 SQL/事件 append/投影写；旧日志未记录的变更不可凭空恢复"),
  ] },
  { name: "跨能力协议与明确边界", rows: [
    cap("CON01", "能力发现/版本/权限/依赖与安装同意", "实装", actor("部分", "registry 按 scope 产工具；无完整 host 能力目录工具", "语义工具目录"), actor("接通", "ctx.capabilities + manifest requires/permissions", "版本化能力目录"), ["CATALOG","API","HOST","REGISTRY"], "插件安装校验；工具构建", "catalog 当前只列已公开 API，不自动覆盖 host UI/engine/native；新增宿主行为必须更新此表"),
    cap("CON02", "对象级授权/用户批准/来源与审计", "部分", actor("部分", "book scope + destructive approval", "最小授权工具"), actor("部分", "domain permissions/settings path grants/plugin namespace", "对象级授权/审批票据"), ["CTX","CATALOG","ANNTOOLS","SHELFTOOLS"], "Agent 写工具；插件 manifest", "域权限不是每个对象的授权；session metadata 默认开放需明确政策 GAP15"),
    cap("CON03", "生命周期 staging/activate/deactivate 与资源释放", "部分", actor("自动", "runtime invalidation/flush background", "任务/贡献消费生命周期"), actor("部分", "lifecycle staged contributions/disposables", "全来源 structured cancellation"), ["HOST","CTX","WIRE","THREAD"], "插件启停/升级；Agent 运行时重建", "GAP06/08/14：callback、已发出的 host effect、transport session 不能全被关闭"),
    cap("CON04", "跨 Worker RPC 的类型、错误与资源额度", "部分", actor("扩展", "插件 tool 也经过同一 worker bridge", "工具任务不被悬挂"), actor("部分", "describeContext/encode/decode/invoke", "有界可取消版本化 RPC"), ["WORKER","WIRE","API","ERRORS"], "所有 Worker 插件及其 Agent 工具", "GAP07/12/13/17：超时/崩溃、__fn 碰撞、解码配额、错误码漂移"),
    cap("CON05", "稳定错误码/安全文案/可重试与降级状态", "部分", actor("部分", "工具错误包装与产品错误表面", "可机器判定回执"), actor("部分", "桥会保留 code；非所有生命周期路径", "统一错误 envelope"), ["ERRORS","WIRE","HOST","CTX"], "宿主 AppError；插件 UI toast", "错误字符串/空列表 fallback 不能算成功；消费者需明确 empty 与 failed"),
    cap("CON06", "长任务进度、取消、超时、并发与幂等", "部分", actor("部分", "局部 thread abort/工具 sequential", "统一任务原语"), actor("部分", "局部请求 id/回调，无通用 TaskRef", "统一任务服务"), ["THREAD","WIRE","HOST","API"], "搜索/导入/LLM/同步等各自实现", "重复业务实现的原因之一；只新增函数名不补任务契约仍会反复缺能力"),
    cap("CON07", "领域事件的本地/远端/外部变化一致性", "部分", actor("自动", "端口每轮读；runtime 配置失效", "有版本快照/读后写"), actor("部分", "domain subscribe / ignoreSelf / session", "统一 change feed"), ["EVENTROSTER","APPEVENTS","CTX","SYNC"], "本地 domain broadcasts；app invalidation", "GAP09/11 与 STAT05；事件类型、实发事件、异步错误三处要同源"),
    cap("CON08", "事务/CAS/撤销/跨对象一致回执", "部分", actor("部分", "单工具领域写/批准，无跨工具事务", "受控批量/预览/回执"), actor("部分", "单域命令 Promise；无通用事务/CAS", "声明式批次，不给 DB transaction handle"), ["EVENTS","APPLY","LIB","ANNOT","API"], "底层 commit_events 单 SQLite 事务", "数据库事务存在不等于业务跨调用事务；undo 与导航 back 是两类能力"),
    cap("CON09", "沙箱、权限撤销和 packaged CSP 验证", "部分", actor("扩展", "插件工具间接承受同样沙箱风险", "统一信任边界"), actor("部分", "Worker + API gate + CSP", "可测试的最小出口"), ["WORKER","WIRE","RUST","HOST"], "安装信任边界", "GAP16 仍需真实 packaged Tauri 验证；既不宣称已越狱，也不宣称完全隔离"),
    cap("CON10", "宿主-工具-插件覆盖门禁/契约测试", "部分", actor("部分", "registry/tool-surface 测试覆盖当前工具", "host 行为映射门禁"), actor("部分", "capability catalog/ctx shape/marketplace checks", "双端一致性/失败时序测试"), ["CATALOG","REGISTRY","API","WIRE"], "现有测试；本次矩阵库存检查", "GAP18：形状匹配不能证明语义/消费者/交付；本表盘点也不替代 E2E"),
    cap("CON11", "任意 SQL/FS/shell/DOM、密钥、伪造历史", "实装", actor("未接", "未注册这些工具", "不开放：越过领域/用户授权"), actor("未接", "不属于 public API", "不开放：越过隔离/宿主所有权"), ["API","REGISTRY","CTX","RUST"], "宿主内部可能需要底层权力", "拒绝原始权力不等于拒绝语义需求：用 ResourceRef/审批/领域命令替代"),
    cap("CON12", "新格式/OCR/实时协作/向量/任意编辑与新平台", "待建", absent("宿主能力更新后再建模"), absent("宿主能力更新后再建模"), ["API","RUNTIME","ENGINE"], "不计当前宿主对等开放率", "不能承诺未来所有插件永不需要新 host；只能承诺当前能力闭包及其可组合范围"),
  ] },
);

export const staticSettingPaths = [
  "general.startView", "general.language", "general.crashPrompt", "general.launchAtStartup",
  "general.fileAssociations", "general.autoUpdate", "appearance.theme", "appearance.motion",
  "reading.theme", "reading.fontFamily", "reading.fontSize", "reading.fontWeight",
  "reading.lineSpacing", "reading.paragraphSpacing", "reading.pageMargins", "reading.readingMode",
  "reading.fixedLayoutReadingMode", "ai.preferences.features.explainSelection",
  "ai.preferences.features.defineTerm", "ai.preferences.features.translate",
  "ai.preferences.features.summarizeChapter", "ai.preferences.features.askConversation",
  "ai.preferences.buildMemory", "ai.preferences.sendHighlightedText",
  "ai.preferences.sendSurroundingContext", "ai.preferences.localOnly", "ai.preferences.followStreaming",
  "ai.connection.configured", "ai.connection.credentialConfigured", "menus.primaryNav.visible",
  "menus.primaryNav.overflow", "menus.shelfHeader.visible", "menus.shelfHeader.overflow",
  "menus.readerHeader.visible", "menus.readerHeader.overflow", "menus.selection.visible",
  "menus.selection.overflow", "ai.connection.provider", "ai.connection.primaryModel",
  "ai.connection.fastModel", "ai.connection.thinkingLevel", "ai.connection.fastThinkingLevel",
  "ai.connection.custom.endpointConfigured", "ai.connection.custom.api",
  "ai.connection.custom.supportsThinking", "ai.connection.custom.maxOutputTokens",
];
export const ineffectiveSettings = new Set([
  "general.launchAtStartup", "general.fileAssociations",
  "ai.preferences.features.explainSelection", "ai.preferences.features.defineTerm",
  "ai.preferences.features.translate", "ai.preferences.features.summarizeChapter",
  "ai.preferences.buildMemory", "ai.preferences.sendHighlightedText",
  "ai.preferences.sendSurroundingContext", "ai.preferences.localOnly",
]);
export const readOnlySettings = new Set([
  "ai.connection.configured", "ai.connection.credentialConfigured", "ai.connection.provider",
  "ai.connection.custom.endpointConfigured",
]);
groups.splice(5, 0, { name: "设置字段逐项覆盖（46 个具体路径）", rows: staticSettingPaths.map((path, i) => {
  const ineffective = ineffectiveSettings.has(path);
  const readonly = readOnlySettings.has(path);
  const effect = ineffective
    ? "保存值有实现；全生产源码扫描未找到对应效果消费者。不能算行为已实现或端到端覆盖。"
    : readonly ? "只读状态，不返回密钥/端点凭据；不等于配置命令。"
      : path === "general.autoUpdate" ? "实际消费者只控制自动检查，不表示无批准自动安装。"
        : path.startsWith("menus.") ? "只影响菜单排列/显示，不调用菜单动作。"
          : "目录有读写且存在产品消费者；仍受格式、配置、scope、授权与持久化契约约束。";
  return cap(`SET${String(i + 1).padStart(2, "0")}`, path, ineffective ? "部分" : "实装",
    actor(ineffective ? "部分" : "接通", readonly ? "get_settings" : "get_settings/update_settings", "类型化设置工具"),
    actor(ineffective ? "部分" : "接通", readonly ? "settings discover/read（需路径授权）" : "settings discover/read/update（需路径授权）", "类型化设置领域"),
    ["SETTINGS","SETDOMAIN","SETTOOLS", path.startsWith("ai.preferences") ? "AIPREFS" : path.startsWith("general") ? "GENERAL" : path.startsWith("reading") ? "PREFS" : path.startsWith("menus") ? "MENUSTATE" : "UI"],
    ineffective ? "仅设置页/设置存储/目录；效果未接" : "设置页；Agent；授权插件可调用（不代表每个插件实际调用）",
    effect);
}) });

groups.push({ name: "组合能力与遗漏补查", rows: [
  cap("MORE01", "周期调度/启动补跑/失败记录", "实装", actor("扩展", "RSS 工具可手动刷新；无调度工具", "查询/配置自动化意图"), actor("部分", "manifest schedules + services.schedules.bind", "有状态的调度服务"), ["SCHED","API","RSS"], "RSS 每小时刷新；外部 Theme Schedule", "最小 15 分钟、首轮 5 秒、每分钟扫描；触发时写 lastRun，不是成功时；关 App 不运行；无暂停/历史查询"),
  cap("MORE02", "一次性延迟/短周期/空闲任务与自触发防环", "部分", actor("自动", "maintenance 有 idle 策略，无通用调度工具", "宿主自动管线/受控计划"), actor("部分", "Worker timer 可用，无宿主可恢复任务", "有 owner/origin 的任务服务"), ["SCHED","MAINT","WORKER","CTX"], "Theme Schedule 用 Worker clock；RSS 定时", "setTimeout 不是可审计后台任务；ignoreSelf 不能阻止跨插件循环"),
  cap("MORE03", "环境 locale/platform/timezone/在线/ready 快照", "部分", actor("自动", "prompt 语言/日期与运行态分别注入", "环境查询工具"), actor("部分", "ctx.locale/appVersion/manifest/capabilities", "统一环境与 availability 快照"), ["CTX","THREAD","RUST","API"], "插件本地化；Agent prompt", "无统一平台/时区/在线/支持格式/就绪信息；读取 locale 并不等于订阅全部环境变化"),
  cap("MORE04", "书籍/集合上下文菜单与 Agent header 插槽", "实装", absent("语义命令，不操作菜单 DOM"), actor("部分", "公开 header surface 仅 shelf/reader", "现有语义插槽扩展"), ["SHELFUI","AGENTUI","MENU","API"], "宿主上下文菜单/Agent header", "宿主已有菜单不等于每处允许 plugin contribution"),
  cap("MORE05", "贡献的动态 visible/enabled/checked 与自有视图刷新", "部分", actor("部分", "工具按 scope 注册，无统一 enablement", "操作 availability"), actor("部分", "静态注册/返回新 view，无通用状态流", "声明式条件与受控视图状态"), ["API","RENDER","CTX","REGISTRY"], "宿主已有动态 UI 条件", "静态入口与实时可用性分离；不允许 Worker 访问 UI store"),
  cap("MORE06", "发现/复用类型化提供者与跨插件权限交集", "部分", actor("扩展", "host 聚合各插件 tool/retrieval", "宿主 broker 消费"), actor("部分", "可注册，无通用 provider discover/invoke", "依赖和资源范围重鉴权的 broker"), ["EXTOOLS","CTX","SYNCTRANSPORT","API"], "宿主消费 voices/content/modes/tools/transports", "注册、被宿主消费、被其他插件调用是三个方向；不开放任意字符串 RPC/他人 storage"),
  cap("MORE07", "插件自有二进制资产与资源配额", "部分", actor("扩展", "只经插件工具间接消费", "受权资源意图"), actor("部分", "包内 assets 有；无可写私有 blob API", "私有可撤销 ResourceRef/流/配额"), ["BLOB","DOCS","API","RUST"], "主题字体包内资源；TTS 内存音频", "包内静态资产、文档 JSON、运行期私有 blob 三者不可混算"),
  cap("MORE08", "声明 UI 本地化、辅助技术、窄窗和输入焦点", "实装", actor("自动", "宿主工具卡/聊天组件统一呈现", "宿主可访问交互"), actor("部分", "PluginText + host renderer", "所有 schema 的可访问性契约"), ["API","RENDER","CTX"], "插件列表/表单；8 语言宿主", "未做产品完整键盘/超长文本/全部 locale E2E；不能以类型齐全代替验收"),
] });

// This reverse index is the authoritative bridge to the earlier acceptance baseline.
export const baselineCoverage: Record<string, string[]> = {
  A01:["CON01"], A02:["TXT13"], A03:["TXT13","TXT02"], A04:["TXT13","LIB11"], A05:["READ01","READ03","CON08"], A06:["CON07","ANN08"], A07:["MORE03"],
  B01:["LIB01"], B02:["LIB02","LIB03","LIB04","LIB05"], B03:["LIB15","LIB16","LIB17","LIB18"], B04:["LIB06"], B05:["LIB08","LIB09"], B06:["LIB11"], B07:["LIB12","LIB13","LIB14"], B08:["LIB07","LIB10"],
  C01:["TXT01","TXT02"], C02:["TXT03"], C03:["TXT04","TXT05"], C04:["TXT07"], C05:["TXT06"], C06:["TXT08"], C07:["TXT09","TXT10"], C08:["TXT11","TXT12"],
  D01:["READ07"], D02:["READ01","READ02"], D03:["READ03"], D04:["READ04"], D05:["READ05"], D06:["READ06"], D07:["READ06","READ20"], D08:["READ09","READ10"], D09:["READ12"], D10:["READ20"], D11:["READ08"], D12:["READ07"],
  E01:["READ13"], E02:["READ13"], E03:["READ14"], E04:["READ14","CON03"], E05:["TXT11","TXT12"], E06:["TXT13"],
  F01:["ANN01"], F02:["ANN02","ANN03","ANN04","ANN05"], F03:["ANN08"], F04:["ANN02","TXT13"], F05:["ANN06","ANN07"], F06:["ANN09"],
  G01:["STAT01"], G02:["READ19"], G03:["STAT02","STAT03"], G04:["STAT05"], G05:["STAT04"],
  H01:["CFG01","CFG10"], H02:["CFG04","CFG05"], H03:["UI02","UI04"], H04:["CFG06","CFG07","CFG08"], H05:["CFG02","CFG03"], H06:["CFG09"],
  I01:["UI01"], I02:["UI03","UI04"], I03:["UI03"], I04:["EXT01","EXT02"], I05:["MORE04"], I06:["READ10","READ11","EXT03"], I07:["MORE05"], I08:["UI05","EXT03"],
  J01:["EXT04"], J02:["EXT05"], J03:["EXT04","EXT06"], J04:["MORE05"], J05:["MORE05"], J06:["EXT06"], J07:["EXT06"], J08:["TXT12","SYS09","MORE07"], J09:["EXT07"], J10:["EXT03"], J11:["MORE08"], J12:["CON04"],
  K01:["READ15"], K02:["READ16"], K03:["READ17"], K04:["READ18"], K05:["READ17","READ18"], K06:["CON03","CON06"],
  L01:["AI06"], L02:["AI07"], L03:["AI01"], L04:["AI02"], L05:["AI03","AI04"], L06:["AI10","AI11","AI12","MEM03"], L07:["AI08","AI09","CON02","CON06"],
  M01:["MEM01"], M02:["MEM10","MEM11"], M03:["MEM02","MEM03"], M04:["MEM04","MEM05"], M05:["MEM06","MEM07","MEM08"], M06:["MEM13"],
  N01:["EXT08"], N02:["LIB14"], N03:["OPS04"], N04:["MORE06"], N05:["CON03","CON06"], N06:["MORE06"],
  O01:["SYS01","SYS02"], O02:["CON08","SYS01","SYS02"], O03:["SYS04"], O04:["MORE07"], O05:["SYS03","EXT12"], O06:["SYS05","OPS08"],
  P01:["SYS11","SYS13"], P02:["SYS10"], P03:["SYS06"], P04:["SYS07"], P05:["SYS08","SYS09","SYS12"], P06:["SYS07","CON02"],
  Q01:["CON07"], Q02:["CON07","READ07"], Q03:["MORE01"], Q04:["MORE02","CON06"], Q05:["MORE02","CON02"], Q06:["CON03","CON06"],
  R01:["CON01","CON03","SYS03"], R02:["CON02"], R03:["CON03","CON09"], R04:["OPS01"], R05:["OPS08","OPS09","SYS15","SYS16","EXT12"], R06:["SYS15","CON05"], R07:["CON01","CON10"], R08:["CON10"],
};
for (const row of groups.flatMap(group => group.rows)) {
  row.baseline = Object.entries(baselineCoverage).filter(([, ids]) => ids.includes(row.id)).map(([id]) => id);
}
