/** Target ownership, not a second runtime API registry. Current facts live in the matrix. */
export type Family = "Domain" | "Contribution" | "Service" | "Schema" | "Contract" | "Boundary";
export type Unit = {
  id: string; family: Family; owner: string; title: string; refs: string[];
  catalog: string[]; operations: string; agent: string; plugin: string;
  limits: string; acceptance: string;
};
const ids = (text: string): string[] => text.split(/\s+/).filter(Boolean).flatMap(token => {
  const range = /^(\D+)(\d+)-(\d+)$/.exec(token);
  return range ? Array.from({ length: Number(range[3]) - Number(range[2]) + 1 }, (_, i) => `${range[1]}${String(Number(range[2]) + i).padStart(2, "0")}`) : [token];
});
function unit(id: string, family: Family, owner: string, title: string, refs: string, catalog: string,
  operations: string, agent: string, plugin: string, limits: string, acceptance: string): Unit {
  return { id, family, owner, title, refs: ids(refs), catalog: catalog.split(" ").filter(Boolean), operations, agent, plugin, limits, acceptance };
}
export const units: Unit[] = [
  unit("D1", "Domain", "library", "书库、集合与可寻址内容", "LIB01-18 TXT01-08 TXT11-13", "domains.library",
    "书籍/集合 list、get、查询、元数据修改、收藏、导入、删除、合并预览/提交、成员调整；TOC 树、章节正文、文本可用性、准备/重试、带位置的精确搜索、链接目标/图片资源解析。查询返回稳定对象引用与内容版本，搜索返回 snippet + Range，目录条目返回标题、层级、目标及可用编号元数据。",
    "沿用书库/正文工具，补失真的参数和可定位结果；意图级工具可组合多个读取，不能绕过书籍 scope、剧透批准和删除批准。",
    "使用相同领域定义，经 manifest 授权取得读/写视图；提供受控原文件/封面引用，不暴露磁盘路径。虚拟书的创建与内容读取仍受 provider 所有权约束。",
    "章节编号解析、匹配排序、导出格式、RSS 订阅属于插件算法。章节 ordinal、书上印刷编号和 sectionIndex 不能混用。缺文件重导入目前只是普通导入流程，不承诺原 ID 原子替换。",
    "不存在章节、无文本、内容版本变化、重复导入/ID 重定向、分页耗尽分别可判定；搜索命中可交给 D2 导航，不要求插件造 CFI。"),
  unit("D2", "Domain", "reading", "阅读会话、导航、模式、播放与统计", "TXT09-10 READ01-09 READ12-20 STAT01-05", "domains.reading",
    "读取 session/loading/book/location/selection/history/mode/playback 快照并观察；open、close、goTo、step、seek、back/forward；Range 选择/清除、临时强调/释放、受支持版式操作；模式启停/步进/恢复、朗读启停与状态；读完标记、已结算及 provisional 统计。业务运行态不因未持久化而变成 Service。",
    "当前 grounding 和自动计时保留；按需查询/导航/模式/朗读使用工具，经同一 reading 控制器。模型不合成阅读时长，不将 opened:true 派发回执当 ready。",
    "读、导航/呈现、持久写分清授权风险；中途启用先读快照再观察；贡献模式/声音并不授权控制用户播放。临时强调带 owner，卸载即清理。",
    "位置恢复验证 book/contentVersion/modeKey/unitId；不把旧 ordinal 强套新分段。会话 timer 是可重置的短时 UI 状态，不是 reading_sessions_pending；不为它建立耐久调度系统。面板开关归 S3。",
    "跨书并发导航由宿主统一裁决，迟到完成不移动新会话；失败不推进历史，back/forward 不产生新分支，用户新跳转截断 forward；实际落点才算完成。模式卸载与音频 fallback 可观察。"),
  unit("D3", "Domain", "annotations", "标注、笔记和问题轨迹", "ANN01-09", "domains.annotations",
    "list/get/filter/page；创建 highlight/underline、改色、笔记 CRUD、受控删除 ask；有业务需求的批次返回原子结果或逐项结果，明确版本冲突；本地/同步写入触发一致失效。",
    "保留 create/edit/delete_annotation，补 style 与精确 ID 查询；自动 recordAsk 是运行时内部能力，不是供模型伪造的问题写工具。",
    "使用同一命令与 Range 校验；补宿主已有 removeAsk；不能直接 append 问题轨迹、事件日志或投影。",
    "新标注默认色归 D5，不与当前对象 recolor 混合。格式化导出由查询 + 插件序列化 + S4 保存组成；不是新的 annotations.exportCSV API。",
    "无位置笔记可以保存；失效 Range 不落错误高亮；并发编辑不静默覆盖，删书后引用返回失效而非误指其他书；失败加载不是空列表。"),
  unit("D4", "Domain", "conversations", "对话内容、线程及回合意图", "AI01-03 MEM12", "domains.conversations",
    "受权读取/搜索线程、消息、摘要/insights；创建、选择、清空线程；用户触发的 draft/发送/停止/重试意图由宿主控制器执行，呈现焦点由 S3 负责。",
    "工具查询与宿主 thread.run 分离；同一核心 Agent 不通过工具递归启动自身无限对话。重试最后用户回合沿用原附件/来源，不伪造用户新输入。",
    "可填入待用户确认的草稿、请求停止指定回合；不能任意指定 role 写 system/assistant/user 历史。llm.ask 不是向产品聊天发送消息。",
    "重试/清空聊天不撤销已完成的标注、记忆或远端 HTTP 副作用；复制聊天是查询 + 剪贴板，不需要专门 Agent 工具。书内单线程与全局多线程仍保持。",
    "停止保存已产生的部分答复；清空/切线程时旧 generation 不得回写新线程；模型回合、存储提交、展示清除的完成状态分别可验证。"),
  unit("D5", "Domain", "settings", "全部真实偏好及生效语义", "UI02 UI04-05 CFG01-13 SET01-74", "domains.settings",
    "discover/read/update/reset；返回类型、可选值、可写性、scope、effective 值、值来源、持久/漫游策略；包含 reader、general、AI、menus、shortcuts、shelf、插件非敏感字段及本次新增遗漏。修改必须映射实际消费者，或明确 unavailable。",
    "沿用 get_settings/update_settings，不为主题/字体/每个布尔字段创建模型工具。敏感配置由 S3 打开宿主设置流程，不把 key 放进提示词。",
    "自有字段与跨插件路径授权分开；动态 option 来自 C1；设置选项变化不能自动执行播放、安装、连接、付款。",
    "明确 null 是值还是 inherit；reset override 不是写默认值；all-books 不等于清覆盖。更新通道 device-local，不被漫游；面板位置/拖动坐标/最后关闭提示不是必须向 Agent 暴露的偏好。",
    "所有可写路径有生产效果消费者；六个现有无效果设置先接线或禁用。两个文本发送设置已控制 Agent 自动附件/viewport/grounding、历史附件检索及收紧时取消；LLM 1.1 结构化 readingContext 与 Dictionary 1.3 已接同一策略和本地缓存边界；任意插件 prompt/HTTP/TTS 与独立检索/旧衍生内容边界仍未闭合。buildMemory 已约束宿主记忆构建，关闭取消在途/排队任务，保留聊天与旧记忆读取；Reading Goals 实际贡献上下文和候选。localOnly 已约束宿主模型调用并取消在途请求，但不约束任意插件 HTTP/TTS/同步，仍需完整隐私边界。切字体、reset、本书覆盖、跨设备更新与失败回滚均验证实际 UI/行为。"),
  unit("D6", "Domain", "memory（目标新增）", "记忆、画像与书内知识的受限读模型", "MEM01-11 MEM13", "",
    "统一 memory/profile/book-memory 现有端口的授权读模型：检索、字段来源、章节摘要/人物概念图、任务状态；记住用户确认的事实、纠错/遗忘反馈、分类纠正和重建请求交给宿主业务命令。当前公共 domain catalog 没有 memory。",
    "保留 search_memory/remember/query_book_graph 与自动抽取、巩固、digest；不把内部端口函数存在计作模型工具或成熟产品入口。",
    "新增受 scope/字段授权的只读领域；提议写由 C4 memoryCandidateProviders 或受控反馈处理，不能写权重、强化次数或画像投影。",
    "不拆 profile/entities/digests 成三套新域。profile/entity 事件投影仍是宿主待建；正式 context bundle 仍待建，插件现在可以组合授权读模型输出自己的格式，但不得声称宿主 bundle 产品已实现。",
    "叙事图遵守阅读边界，说明性图按 flavor；重分类后旧图版本可辨；候选被接受/拒绝有来源。当前未实现的画像与 bundle 单列，不成为 Jumper 的前置条件。"),
  unit("C1", "Contribution", "actions/options", "动作、命令与动态选项", "UI03-05 EXT01-02 MORE04-05 CFG09", "contributions.selectionActions contributions.headerActions contributions.commands contributions.settingsOptions",
    "插件声明 action/command ID、位置、参数、标题、可见/可用/checked 条件与默认键位；宿主组合菜单/快捷键/命令面板；动态设置选项提供候选而非替用户修改值。现有 header shelf/reader 保留，确有宿主插槽的上下文菜单按位置参数扩展。",
    "模型调用的是受 schema/权限约束的语义命令，不是点击菜单或执行 label；插件命令要模型可用需 C4 显式贡献工具或宿主明确适配。",
    "Jumper 0.2 用 reader headerActions 与 observeSession 组合前后跳可用性。commands/headerActions/selectionActions 1.1 的注册句柄 updateState 更新完整 visible/enabled/checked 快照，旧句柄不能改同名新注册。声明无额外 permission 不代表动作能绕过它调用的领域权限。",
    "不为每个菜单再建 contribution family；命令 broker 仅解析已注册类型化描述，禁止任意字符串反射到 host 函数。静态注册与实时 enablement 分开。",
    "禁用/撤权后命令不可执行；菜单状态随 session 刷新；键位冲突可诊断；插件卸载不留下快捷键或悬挂 UI 回调。"),
  unit("C2", "Contribution", "contentProviders/readerModes", "内容与阅读算法提供者", "LIB12-14 READ15-16 EXT10", "contributions.contentProviders contributions.readerModes",
    "content provider 提供插件拥有的虚拟书内容/版本；reader mode 提供已支持 text-unit-navigator 分段策略。宿主负责阅读、版本切换、模式状态和资源引用。",
    "经 library/reading 工具消费结果，不要求模型注册算法或直接读 provider 内部数据。",
    "RSS 和 sentence-reader 保持插件业务；刷新当前内容应有版本失效和落点处理。跨插件消费有真实需要时通过受权类型化 provider broker，不直接访问其他插件 storage。",
    "不是任意格式解码器、HTML/DOM 注入或全新阅读器渲染器；OCR、新格式、新阅读交互原语属于宿主能力更新。",
    "provider 失效、disable、内容变更返回明确 unavailable/stale；旧回调不覆盖新版本；模式恢复必须验证引用仍适用。"),
  unit("C3", "Contribution", "voiceProviders", "声音与合成提供者", "READ17-18", "contributions.voiceProviders",
    "列出 provider/voice、能力与可用性；接受有界文本并产出可消费音频及格式元数据；宿主 reading 控制播放/预取/系统回退和取消。",
    "选择声音可用 settings，开始/停止必须 reading 命令；不能把设置成功当作已经出声。",
    "实现 vendor HTTP、voice 映射与合成；凭据通过隔离 secrets；音频资源归任务/会话所有，不泄露跨插件资产。",
    "不新增独立播放服务与 reading.playback 争夺同一会话；不要求音频编辑器、任意设备控制或后台常驻播放器。",
    "取消/换书/停用 provider 后不再播放迟到音频；回退状态与当前声音可读，费用/请求取消边界明确。"),
  unit("C4", "Contribution", "agent extensions", "工具、上下文、检索与记忆候选", "AI04-05 AI08-12 MEM02-03 EXT09-10 MORE05-06", "contributions.agentTools contributions.agentContextProviders contributions.agentRetrievalProviders contributions.memoryCandidateProviders",
    "工具显式声明 scope/schema/风险；上下文每轮有界注入；检索按需返回有来源片段；记忆候选由宿主去重/政策裁决。四个通道保留不同语义和生命周期，不合并成万能 agent.invoke。",
    "只有插件 installed + enabled + scope/grant/availability 满足时才消费。agentTools 1.1 按当前 visible/enabled 过滤两 scope 的工具集合；AgentThread 每次模型请求前刷新工具与检索定义，不丢弃章节会话。已发出请求保留原定义，缓存工具和检索执行前复核精确注册，旧调用不能转交同名新实现。此接线不是所有宿主内置 Agent 工具的统一 enablement；脚本推理真实 Worker 验收不是自主远端模型验收。上下文与候选没有插件实例不等于宿主 API 未实现。",
    "Dictionary 已有 3 工具 + 1 检索；RSS 有 3 global 工具；其他源插件没有直接操作工具。删除词/CSV/退订/OPML 可以在插件补工具，不要求宿主新增词汇/RSS 领域。",
    "输出不成为高优先级指令；不得通过 plugin tool 规避 host 批准/剧透规则；不能把自有私有数据自动变成所有插件可见。",
    "跨 scope 不暴露工具；输入/输出有界，失败不悬挂整轮；撤权和停用失效；检索引用可追踪，候选无条件入记忆视为失败。"),
  unit("C5", "Contribution", "themes/fonts/syncTransports", "静态资产与密文传输扩展", "EXT08 SYS14 OPS02 OPS04", "contributions.themes contributions.fonts contributions.syncTransports",
    "themes/fonts 由 manifest 声明、宿主加载验证并供 settings 选择；syncTransports 提供密文连接/session 操作，宿主掌管加解密、ACK、游标、重试与同步调度。三者共用贡献生命周期，不共用业务控制器。",
    "主题/字体用 settings；同步用 S9 控制面或用户流程，不把 transport 当控制整套同步的工具。",
    "不要求给静态 manifest 贡献补 ctx.register；transport 必须有 session.close/dispose，持有连接随 owner 释放。",
    "不开放解密 key/事件 ACK 写/字体目录。WebDAV 在源码中但不在 Rust BUNDLED；源仓、编译内置、市场分发、安装、启用、工具可用是六种不同状态。",
    "主题/字体失效可降级；transport 重连/换配置/卸载关闭旧 session；只传密文，不绕过宿主数据合并。"),
  unit("S1", "Service", "storage", "插件私有数据与持久边界", "SYS01-03 SYS05 MORE07", "services.storage",
    "隔离 KV 镜像 + durable ack/flush；文档 collection CRUD、有界查询、所需索引/分页；按业务需要提供版本条件写或批次。迁移 storage-only，quiesce→drain→snapshot→migrate→activate，失败恢复不能覆盖此前已确认的合法写。",
    "无通用私有 KV/文档工具；通过相应插件工具消费，权限不会因调用方是模型而扩大。",
    "按 plugin ID 隔离；KV、docs、secrets、blob 各自标注本地/漫游/备份/卸载保留政策；书籍索引并不自动意味着随书删除。",
    "不是插件业务 schema 搬到宿主，也不是开放 SQL/transaction handle；取消不回滚已持久写。自有二进制数据引用由 S4，密钥由 S2。",
    "GAP01–03 的更新时序、持久确认、镜像失败回滚通过故障注入；保存失败不能成功 toast；大数据导出不要求一次把全部内容装进 Worker。"),
  unit("S2", "Service", "secrets", "隔离凭据", "SYS04 CFG07", "services.secrets",
    "plugin-owned secret get/set/remove；敏感设置 UI 由宿主管理；提供 configured 状态而非向普通 settings/catalog 返回明文。",
    "不读密钥，不把 key 交给模型；配置意图打开用户流程。",
    "仅本插件 namespace，凭据值不得经日志/工具输出/诊断泄露；撤权后失去访问。",
    "现有插件为了自有 HTTP 可读其 secret；目标不强制新增通用凭据代理/OAuth SDK。宿主 AI key、同步解密 key、其他插件 key 永不因服务授权泄露。",
    "跨 namespace/日志脱敏/移除后缓存处理验证；密钥保存与插件非敏感偏好分开报告持久结果。"),
  unit("S3", "Service", "ui", "语义导航、视图与宿主管理流程", "UI01-03 READ10-11 EXT03-07 SYS12 SYS15-17 OPS06-10 CFG07-08 AI04-05 MORE05", "services.ui",
    "语义页面/集合/面板导航、焦点恢复、用户选择集快照；插件自有视图 push/pop/replace/close/refresh、错误/进度呈现；打开指定宿主流程（AI 配置/账号/账单/备份/诊断/更新/数据清除）并返回取消/完成或受限状态。外部 URL 有 scheme/目的约束。",
    "意图工具可请求宿主流程，用户完成批准；查询数据、改变屏幕、确认破坏性行为是三个不同步骤。",
    "不拿 DOM/Router/Jotai/原生窗口句柄；自画确认按钮不能铸造 host approval。可请求安全窗口意图，关闭前等待宿主持久屏障。",
    "不为每个设置页新增域；不公开拖动坐标/任意窗口/静默重启/付款。管理流程是有类型的有限集合，不是绕过领域命令的万能 dispatch。当前禁用 Reveal 不计已实现。",
    "关闭视图释放 callback/任务并恢复焦点；过期结果不打开旧弹窗；失败用 InlineError/安全 toast，不能伪装空结果；账号删除、本地 wipe、卸载各自确认且不串用。"),
  unit("S4", "Service", "resources（目标新增）", "文件、书籍资产与私有二进制资源", "LIB08-09 TXT11-12 SYS09-11 SYS13 MORE07", "",
    "用户选择 FileRef、读取授权资源元数据/范围/块、创建私有临时写入、commit/abort/release、保存到用户选择位置；Book/封面/图像的业务解析由 D1，资源服务只处理授权字节。现有 ui.exportFile 语义迁移到这里，不长期维护两套保存协议。",
    "读写文件必须有来源和用户意图，不接受模型猜出的任意路径；资源呈现与下载不必把 bytes 输入模型。",
    "ResourceRef 绑定 owner/scope/type/size/有效期；包内资产只读，自有写入按配额；大书使用有界块及回压，小文本可保留便利调用。",
    "真实需求来自已有书文件、图片、字体和 TTS 音频，不是新增万能 filesystem；无需对每个短字符串强制建流，也不提供任意 watch 目录。",
    "用户取消选择/保存与失败区分；越界读取/跨插件 ref/撤权拒绝；未提交写 abort；丢失 worker 自动释放；不能伪造路径逃逸。"),
  unit("S5", "Service", "network", "有界 HTTP", "SYS06-07", "services.network",
    "保留 Request 的 method/headers/body/响应 status/headers/bytes；取消、超时、大小/并发限制、授权目的地与重定向检查；重试说明幂等性，离线明确报告。",
    "宿主推理/插件工具可使用，但不因此添加无限制 fetch 模型工具。",
    "RSS/TTS/WebDAV 不各自重写跨 Worker HTTP 桥；协议、认证、业务缓存仍在插件，提供者 HTTP 不变成宿主 RSS 业务。",
    "不建设 WebSocket/TCP/通用离线耐久队列来修复现有 HTTP；中止请求不保证服务端没处理，更不等于撤销已付费操作。",
    "GAP04/05：Request 对象与 url+init 等价；预先 abort 不派发；途中 abort 到达 host fetch；流和重定向不能绕过额度/权限。"),
  unit("S6", "Service", "llm", "受预算约束的独立推理", "AI06-07 CFG08", "services.llm",
    "fast/smart 文本、结构化、流式输出；task scope、timeout/abort、可获得的 usage/终止原因；请求前校验模型能力和授权预算。",
    "thread 与自动管线复用推理设施，但 host prompt/审批/记忆业务仍由 Agent runtime 拥有。",
    "llm.ask 仅独立推理；返回结构符合声明 schema，流结束/错误可判定；不能读实际 key 或默认继承用户全部聊天/记忆。",
    "未提供用量的 vendor 返回 unknown，不编造成本；不为此新增本地模型、向量库或第二个 Agent。",
    "超时/停用/取消后不回写新视图；schema 错误明确失败；预算拒绝在请求前发生，停止不能宣称远端绝无费用。"),
  unit("S7", "Service", "clipboard", "受权复制", "SYS08-09", "services.clipboard",
    "文本写入；宿主已有图像复制通过授权 ImageRef 写入；操作失败用稳定错误，用户取消不等于复制成功。",
    "默认由用户按钮触发；确有对话意图才适配工具，不为每种内容增加复制工具。",
    "文本复制已接通；图像复制尚未接入插件；不自动读取系统剪贴板。",
    "不因为复制聊天/标注就建 conversations.copy/annotations.copy API；组合既有读能力与 clipboard 即可。",
    "不支持格式、失效图像引用、系统写入失败可判定；无输入的后台剪贴板轮询不属于本次范围。"),
  unit("S8", "Service", "schedules", "运行期间的可管理调度", "MORE01-02", "services.schedules",
    "现有 manifest schedules/bind：补枚举、自有计划状态/暂停/恢复、上次触发与成功/失败、重入策略和 owner 清理；空闲任务按宿主资源策略执行。",
    "自动化意图可通过插件工具/受限设置组合，不把每个 setTimeout 都变成模型工具。",
    "Worker clock 足够临时计时和 Theme Schedule；需要补跑的业务明确运行窗口和去重。当前 15 分钟下限/启动扫描与 lastRun 是触发时间必须诚实报告。",
    "关 App 不运行；不承诺 OS 常驻、恰好一次、任意 cron 分布式执行。短时 timer 不持久化是合法设计；业务反馈循环需 origin/深度或显式限流。",
    "长任务不重入、停用清理、失败不标成功；错过触发如何补跑有可复现行为。重启恢复仅对明确声明的计划，不恢复全部 Worker promise。"),
  unit("S9", "Service", "sync（目标新增控制面）", "同步状态与用户请求", "OPS01-05", "",
    "受限状态：连接阶段、积压/错误、上次成功、本地可用性；用户意图 connect/disconnect/requestSync 由宿主 scheduler 执行，密文 transport 仍由 C5 提供。",
    "只读状态或打开连接批准流程；不操纵事件游标/ACK/加密密钥。",
    "普通插件可按授权了解非敏感 availability；transport 插件不因提供连接而获得全局同步管理权；连接配置走宿主 UI/secrets。",
    "不把 checkpoint/replay/事件账本操作暴露为普通 API；健康修复由宿主流程。新控制面只覆盖现有真实同步行为，不建设第二套同步引擎。",
    "断开/换 transport 关闭旧会话；本地/远端应用后的 D1–D6 快照可刷新；只看本地单元测试不能宣称跨设备正确。"),
  unit("S10", "Service", "plugins（目标新增只读目录）", "插件可用性与受控自管理", "EXT11-12 MORE06", "",
    "查询授权可见的插件 ID/版本/安装启用状态、贡献能力与 availability；安装/启停/升级/卸载请求交给 S3 宿主批准流程，实际事务由 host 生命周期所有。",
    "模型按插件能力发现可调用工具，但不能静默安装新代码或授予权限。",
    "允许自有状态与经批准的依赖发现；跨插件调用只能使用注册接口和权限交集；不得读他人私有配置或动态字符串执行函数。",
    "只读目录不演变成依赖求解器/插件商店后端重写；缺消费者时先补插件，不把每个贡献都开放为跨插件 RPC。",
    "源码插件与 bundled 的库存独立核对；实际 installed/enabled 需运行态证据；失效依赖、禁用 provider 不返回可用。"),
  unit("S11", "Service", "session（仅环境元数据）", "阅读状态统一归 D2", "READ07-08 MORE03", "services.session",
    "session 2.0 已删除 subscribe 及四种阅读事件；D2.reading 独占当前阅读快照/观察。环境保留 revision/runtime/platform/locale/timeZone/utcOffsetMinutes/networkHint，Listening Desk 0.7 消费离线提示；格式可用性和服务真实就绪仍缺。",
    "get_host_environment 在全局/书内查询同一快照；自动日期/语言上下文与按需查询分清，不为每个环境字段新建工具。networkHint 不是 endpoint 可达性。",
    "environment 每次刷新，observeEnvironment 立即快照后观察 revision；语言/网络/焦点事件与 30 秒时区复核，末个观察者清理监听。读当前书须 reading 授权，元数据不含阅读或账号状态。Dictionary 1.2 经 reading/library 查询当前标题，不靠未来事件推测；旧 ^1 service 契约不兼容并拒绝，不保留旁路兜底。",
    "这里不是新 session service 设计，也不是全局万能 runtime context。没有需求的设备指纹/硬件枚举不开放。",
    "读快照与订阅之间不丢更新；locale/可用性变化可刷新；撤 reading 权限后缓存/订阅不继续泄露书名与位置。"),
  unit("V1", "Schema", "views", "声明式内容、表单与交互结果", "EXT03-07 MORE05 MORE08 AI04-05", "schemas.views",
    "保留 list/detail/markdown/blocks/form 及宿主组件；补有界异步搜索/分页、loading/empty/error、可取消进度、稳定选择和资源引用。Tree/Table 仅在 TOC 层级或比较字段真实需要时补最小语义与键盘协议。",
    "工具卡/问题卡由宿主呈现；不把 PluginView 树当模型可执行 UI 代码。",
    "声明数据与事件，宿主拥有 React/布局/焦点/本地化；每个 view instance/generation 有局部 callback lease。",
    "Schema 无独立权力；onSubmit 仍走 Domain/Service。当前虚拟列表已有，不冒充仍需重建；无证据的富文本编辑器/任意 canvas/iframe 不进必补清单。",
    "长中文/英文、键盘、窄窗、空数据、失效 callback、异步结果逆序验证；搜索 debounce 不等于取消和防旧结果。"),
  unit("V2", "Schema", "settings", "字段声明而非行为授权", "CFG01-13 SET01-74", "schemas.settings",
    "类型、默认值、scope、约束、secret 标记、动态选项和条件可用性。字段存在、值能保存、效果有消费者分别验证。",
    "从受权 discover 构造工具参数，不另写全量 settings 枚举。",
    "插件设置声明自有数据，跨插件写仍需 D5 授权；隐藏字段不等于安全隔离。",
    "不为每个底层 KV 建公共字段；secret/password 不进入普通 Agent catalog。",
    "新增字段必须注册消费者/默认/范围/reset 语义；移除插件选项后的失效值可诊断。"),
  unit("V3", "Schema", "themes", "受限主题声明", "EXT08 SYS14", "schemas.themes",
    "宿主支持的 tokens/字体资产与 reader theme 声明，版本/资源有效性由 catalog 与 loader 验证。",
    "仅选择已声明主题，不注入样式或代码。",
    "提供资产和 tokens，不直接修改应用 DOM 或全局状态。",
    "新增主题内容不需改宿主；新渲染原语或未支持 token 的行为不由任意 CSS 逃生口绕过。",
    "缺字库/资产路径/插件禁用后回退可用；字号不破坏宿主交互与可访问性。"),
  unit("Q1", "Contract", "catalog/authorization", "发现、授权和来源", "CON01-02 CON09 CON11 AI04 AI09", "",
    "单一 capability catalog + 域定义派生 actor 视图；每个操作记录 owner、schema、version、scope、风险、availability、来源和消费者。授权先于副作用，对象/字段/资源范围在执行时复核。",
    "模型工具只是授权操作的意图适配器，自动管线单独记账。批准票据绑定 actor/operation/对象/有效期，不能被不同请求复用。",
    "manifest consent、运行时 grant、用户一次性批准各司其职；跨插件 broker 取权限交集，不沿调用链提升权限。",
    "不复制第二份能力 registry；不把所有内部行为都变成公开工具。当前对象级授权/metadata policy/packaged CSP 尚未全部验收。",
    "无权限、撤权、过期批准、跨 scope、恶意插件输出和真实打包 CSP 分别测；只测类型不算通过。"),
  unit("Q2", "Contract", "execution/lifecycle", "完成、取消和资源释放", "CON03-06 READ20 AI07", "",
    "短操作 Promise 直接给完成结果；长操作 request/task ID + progress + cancellation + deadline + terminal result。accepted 只表示受理，不是完成。跨 Worker envelope 有版本/类型/长度/并发界限。",
    "工具结束必须有真实业务结果；插件 worker 崩溃不让模型轮次无限等待。",
    "owner = plugin generation + view/session/task lease；停用后拒绝新调用、取消在途并清理回调/连接/临时资源；迟到 effect 在 host 提交边界再验 generation。",
    "cancel 不等于 undo/远端回滚；不强制所有任务耐久恢复。stable AppError code 复用项目错误契约，本文不发明与现有 code 冲突的第二套错误枚举。",
    "GAP06–08/10/12–14/17 的超时、callback、协议碰撞、旧结果/host effect、连接释放逐个故障注入；任务资源数回到基线。"),
  unit("Q3", "Contract", "consistency/observation", "快照、变更和业务写入", "CON07-08 OPS05 OPS11 STAT04-05 CFG10", "",
    "授权 snapshot + revision + invalidation/订阅后重读，覆盖本地、同步和外部写；持久命令在 commit_events 事务完成后确认。CAS/批次只加在会丢用户编辑或部分成功的业务操作。",
    "每轮快照可满足多数查询，不需要让模型订阅所有事件。导航历史与业务撤销不可混用。",
    "事件是状态失效/业务通知而非原始 log 重放权；异步 callback 错误必须被处理。订阅注册与快照的竞态用 revision 重读收敛。",
    "不建设通用 durable event bus/exactly-once/跨插件分布式事务；不要求每次查询带全局快照隔离。无法撤销的外部效果如实报告。",
    "远端变更、事件乱序/重复、subscribe 首次竞态、合法新写后旧失败回滚都不静默产生陈旧 UI；依旧以存储事务为持久边界。"),
  unit("Q4", "Contract", "coverage gate", "行为映射与语义回归门禁", "CON10", "",
    "新增宿主行为必须映射到 Domain/Contribution/Service + schema，并列 Agent/插件 disposition、实际消费者、失败路径和验收；库存新增/旧映射失效/来源丢失使生成检查失败。",
    "shape 测试以外还查工具参数是否被 adapter 丢失、批准是否执行、结果是否真实。",
    "测试同时覆盖注册、Worker wire、host 消费、卸载/撤权和用户入口；源码存在不等于部署/启用。",
    "本轮文档与生成器是人工审计的可追踪门禁，不会自动证明所有 React 闭包行为已经被发现；新产品行为仍需评审。",
    "本模型每条证据行/每个现有 catalog 成员/旧 129 基线均有归属；真实场景成功、失败、并发和撤权四条路径完成后才能关闭相应缺口。"),
  unit("B1", "Boundary", "future/internal", "明确排除与宿主尚未建成部分", "CON11-12 SYS18 MEM07-08 MEM13 OPS09-11", "",
    "禁止任意 SQL/FS/shell/DOM、宿主秘密、原始事件 append、伪造历史、静默付款/授权；新格式/OCR/任意编辑/实时协作/新平台在宿主能力更新时再纳入。",
    "Agent 和插件都不能用更高权限工具绕过产品策略；宿主内部投影修复不是普通模型行为。",
    "可以组合已授权读模型产生导出/插件算法，但不能把尚无的产品能力标成漏一条导出 API。",
    "画像实体投影、正式 context bundle、完整备份、Reveal 占位列为宿主建设/修复，不能为“插件完备”强迫先建设未来产品；移动端遗留 no-op 不计桌面缺口。",
    "需求评审能指出新增的宿主原语才算 host 更新；若只是编号规则、CSV 格式、HTTP 来源或主题内容，则应由已有原语组合。"),
];

export const refinements = [
  ["R1", "已接真实遗漏", "CFG11", "settings 1.2 已注册 appearance.contentTypography.* 四字段 followReader/fontFamily/fontSize/lineSpacing，独立尺寸 x-small/small/medium/large/x-large，行距 compact/comfortable/relaxed；默认 true/null/medium/comfortable。跟随全局 reader，null 为应用 sans；独立字段只在解除跟随后消费。"],
  ["R2", "已接真实遗漏", "CFG12", "settings 1.2 已注册 annotations.defaultColor，yellow/green/blue/pink，默认 yellow；宿主下一次一键标注即时读取，recolor 仍影响后续默认。不是 annotations 领域方法，不重染已有标注。"],
  ["R3", "已接真实遗漏", "CFG13", "settings 1.2 已注册 general.updateChannel，stable/beta，默认 stable，设备本地且不漫游。已有 About 面板跟随 KV 变化；只影响下一次检查，不批准升级/重启。"],
  ["R4", "细化现有契约", "READ16", "modeKey/unitId/content version 决定恢复是否合法；恢复时重解 CFI，不钳制旧 ordinal，无版本旧位置不恢复。模式私有位置不得由插件直接写 read-aware-navigator-state:*。mode sessionTimer 从零计时，不持久化是设计，不是 durable scheduler 缺口。"],
  ["R5", "拒绝重复 API", "AI03 SYS08", "聊天复制 = conversations 读取 + clipboard；retry/clear 不是业务撤销，不删除已完成的工具副作用。draft/发送仍需用户意图与回合 generation。"],
  ["R6", "拒绝虚构宿主能力", "LIB06", "ReaderWorkspace 的重新导入按钮当前调用 library.openImportPicker，不能据此要求/宣称已有原文件原子替换引擎。"],
  ["R7", "收回不必要的暴露", "READ11 MORE02", "面板开关/焦点与用户选择集可以语义化；toc/chat 像素宽度和浮动控制 x/y 由宿主布局管理，不要求每项成为 Agent 工具或 settings 字段。"],
  ["R8", "校正库存口径", "EXT11", "当前源码有十二个第一方插件，Rust BUNDLED 编译清单有六个；WebDAV、Annotation Desk、Listening Desk、Reading Goals、Workspace Profiles、Text Desk 不在内置清单。Text Desk 0.3 组合 library 1.3 正文状态、准备/确认重建/请求取消、列表详情与明确开书；请求详情通过 UI 1.2/views 1.1 实时推送，列表仍显式刷新，任务仅属当前激活代，不宣称耐久调度或全局停止。Workspace Profiles 通过 settings 1.3 快照/原子更新组合书架与外观预设，注册双 scope 的管理工具；0.2 通过 settings 1.4 精确路径增加自身快捷键表单，批量冲突、重置与生命周期边界见 UI04。Reading Goals 实际提供书内上下文和记忆候选，并消费 buildMemory 实时设置；这不是新增宿主域或专属模型工具。源码、编译内置与用户安装态分开枚举，以矩阵生成库存反查，不沿用旧的六源码/五内置数字。"],
  ["R9", "限制基础设施规模", "CON06-08 EXT06 MORE06", "通用耐久队列、可重放事件总线、全局事务、任意跨插件 RPC、富文本编辑器都不是当前必补；选择快照+revision、有限任务、业务批次、已声明 provider、场景所需声明 UI。"],
  ["R10", "细化设置完成语义", "CFG01 CFG10", "settings 1.1 的单个已验证命令现在等待本地 SQLite KV 批次提交；失败整体回滚且不广播成功，跨 actor 命令在前序结算后读快照。结果按授权过滤；不是远端漫游、系统设置效果、密钥或 reading.configureMode 的持久完成证明。"],
] as const;

export const evidence = [
  "apps/web/src/features/settings/lib/content-typography.ts",
  "apps/web/src/features/settings/sections/AppearancePanel.tsx",
  "apps/web/src/features/settings/hooks/useContentTypography.ts",
  "apps/web/src/features/annotations/lib/annotation-prefs.ts",
  "apps/web/src/features/reader/hooks/useReaderTextActions.ts",
  "apps/web/src/features/update/lib/update-channel.ts",
  "apps/web/src/features/settings/sections/AboutPanel.tsx",
  "apps/web/src/features/update/lib/software-update.ts",
  "apps/web/src/features/reader/lib/text-unit-mode-state.ts",
  "apps/web/src/features/reader/hooks/useTextUnitNavigator.ts",
  "apps/web/src/features/reader/hooks/useSessionTimer.ts",
  "apps/web/src/features/reader/components/TextUnitReadoutChip.tsx",
  "apps/web/src/features/reader/lib/reader-panel-layout.ts",
  "apps/web/src/features/reader/lib/reader-panel-sizes.ts",
  "apps/web/src/features/reader/state/panel-intent.ts",
  "apps/web/src/features/ai/hooks/useBookConversation.ts",
  "apps/web/src/features/ai/components/ChatMessageActions.tsx",
  "apps/web/src/App.tsx",
  "apps/desktop/src-tauri/src/plugins.rs",
];

export const scenarios = [
  ["Jumper", "D1 D2 C1 S3 V1 Q2 Q3", "已建第一方 Jumper：reader header/命令、分层目录与版本化精确搜索、共享会话/导航回执/历史。印刷章号、目录序号、标题匹配由插件区分；不存在章节不派发，歧义给候选。隔离 Tauri FB2 Worker 与实际 Agent 端口通过；WebView hidden 导致前台绘制/截图未通过，PDF、超大查询预算与逐调用取消仍未关闭。"],
  ["Dictionary", "D1 D2 C4 S1 S6 S7 V1", "查询/保存/检索已经有工具；删词/CSV 工具缺消费者，应在插件补；当前文本上下文/存储持久屏障缺口由宿主补。复制/导出失败必须可见。"],
  ["RSS/OPML", "D1 C2 C4 S1 S4 S5 S8", "订阅/刷新工具已有，退订/OPML 工具未贡献；文件选择为宿主漏接能力，OPML 解析为插件算法。正文版本更新不能把当前会话悄悄指向旧引用。"],
  ["句读与 TTS", "D2 C2 C3 D5 Q2", "reading 2.5 已共享朗读、模式快照/启停/单位配置、版本化返回、单元步进与模式提供者发现/选择；Listening Desk 组合模式表单、朗读、历史、Current passage 与上下单元。配置的书内状态/提供者偏好同批落盘，回执等待该请求精确持久结果，失败不被偏好回滚误报为 superseded；位置写在配置成功后复核 revision/key/unit。步进从 resting 继续并返回 moved/start-of-book/end-of-book，等待真实页面/分段/React 反馈与目标位置提交，不记跳转历史；返回同样等待持久完成。位置保存失败保留 db code，下一次明确操作可重试；自动朗读消费同一回执，书尾正常停止，保存失败则停止而非继续播下一段。隔离 macOS Tauri 已验跨节、慢 Worker、失败、取消、书尾及双端 SQLite 故障/恢复；空节/非线性/其他格式仍需桌面验证。模式选择通过 availableModes/selectModeKey，失效选择保留且不隐式替换，取消撤回未完成选择但不撤销所有已提交提供者偏好。旧偏好读取无副作用，迁移的新设置、书内配置和旧记录删除同批提交；不同所有者保留，删除失败两端拒绝且旧值保留。READ16 跟随和跨提供者取消补偿仍缺；release、其他系统、远端 TTS 未验。"],
  ["主题与定时主题", "D5 C5 S8 V3", "主题/字体可组合，已有 settings 足以切换；短 clock 不要求耐久工作流。新增主题无需宿主改动，缺字体时回退。"],
  ["WebDAV", "C5 S2 S5 S9 Q2", "密文传输 v2 已有 session.close、宿主会话所有权和原生请求取消；受控同步状态/连接面仍缺双端入口。连接 UI、真实跨设备与升级回滚仍待完整验收。"],
  ["标注批改/导出", "D3 S4 Q3", "补按 ID/分页/有需求的版本条件批次；插件组合 CSV/Markdown 格式，宿主无需对应每种导出格式。中途取消报告已完成项，不能宣称全部回滚。"],
  ["记忆与人物关系", "D6 C4 Q1", "Agent 查询/自动管线已有，插件读模型缺失；画像投影与正式 bundle 尚未实现。超前内容、候选来源和拒绝结果必须可辨；不开放原始投影写。"],
  ["设置自动化", "D5 V2 Q3", "覆盖真实偏好、默认/覆盖/设备本地策略；无效果字段先禁用或修复消费者。禁止以保存成功证明隐私开关真的有效。"],
  ["中途启用/跨设备变化", "D1 D2 D3 D4 D5 Q3", "先获取一致快照再观察或 revision 重读；本地/远端/外部写都使数据失效。无需 universal event replay，但不能漏通知后永久陈旧。"],
  ["插件升级/崩溃/撤权", "S1 S10 Q1 Q2", "quiesce/drain/snapshot/migrate/activate 与失败恢复；超时和 worker crash 结束 pending；旧 callback 与在途 host effect 不污染新代。GAP01–18 未因写文档关闭。"],
  ["账号/备份/诊断/更新", "S3 S4 S9 S10 B1", "打开有边界的宿主流程并反馈真实结果；明示现有备份并非完整快照。不得静默付款、上传日志、读取凭据或 wipe；不把占位 Reveal 算可用。"],
] as const;

/** Legacy scenario IDs stay stable; associations do not assert that tests passed. */
export const scenarioCoverage: Record<string, string[]> = Object.fromEntries([
  ["W01", "D1 D2 C1 S3 V1 Q2 Q3"], ["W02", "D2 D3 S1 Q3"],
  ["W03", "D1 S4 V1 Q2"], ["W04", "D1 D3 S4"], ["W05", "D3 V1 Q1 Q3"],
  ["W06", "D2 S4 V1"], ["W07", "D5 C5 S8"], ["W08", "D2 C1 S3"],
  ["W09", "D1 C2 S1 S5"], ["W10", "D2 C3 Q2"], ["W11", "D1 D2 S3 S6"],
  ["W12", "D6 V1 Q1"], ["W13", "D4 S3 Q2"], ["W14", "D6 S4 B1"],
  ["W15", "C5 S2 S5 S9"], ["W16", "D3 S1 S2 S5 Q2"],
  ["W17", "D5 C1 V1 V2"], ["W18", "C2 C4 S10 Q1"], ["W19", "D2 S11 Q3"],
  ["W20", "S1 S10 Q1 Q2"], ["W21", "S3 S4 B1"], ["W22", "D2 S1 S5 Q2 Q3"],
  ["W23", "S1 Q2 Q3"], ["W24", "S5 Q2"], ["W25", "C5 S3 Q2"],
  ["W26", "S10 Q1 Q2"], ["W27", "S9 Q3"], ["W28", "S3 V1 Q2"],
  ["W29", "S1 Q3"], ["W30", "Q2"], ["W31", "Q1 S11 B1"], ["W32", "Q2 Q4"],
].map(([id, owners]) => [id, owners.split(" ")]));
