/** Target ownership, not a second runtime API registry. Current facts live in the matrix. */
export type Family = "Domain" | "Contribution" | "Service" | "Schema" | "Contract" | "Boundary";
export type Unit = {
  id: string; family: Family; owner: string; title: string; refs: string[];
  catalog: string[]; operations: string; agent: string; plugin: string;
  limits: string; acceptance: string;
};
const ids = (text: string): string[] => text.split(/\s+/).filter(Boolean).flatMap(token => {
  const range = /^(\D+)(\d+)-(\d+)$/.exec(token);
  return range ? Array.from({ length: Number(range[3]) - Number(range[2]) + 1 }, (_, i) => `${range[1]}${String(Number(range[2]) + i).padStart(2, "0")}`) : [token];
});
function unit(id: string, family: Family, owner: string, title: string, refs: string, catalog: string,
  operations: string, agent: string, plugin: string, limits: string, acceptance: string): Unit {
  return { id, family, owner, title, refs: ids(refs), catalog: catalog.split(" ").filter(Boolean), operations, agent, plugin, limits, acceptance };
}
export const units: Unit[] = [
  unit("D1", "Domain", "library", "书库、集合与可寻址内容", "LIB01-18 TXT01-08 TXT11-13", "domains.library",
    "书籍/集合 list、get、查询、元数据修改、收藏、导入、删除、合并预览/提交、成员调整；TOC 树、章节正文、文本可用性、准备/重试、带位置的精确搜索、链接目标/图片资源解析。查询返回稳定对象引用与内容版本，搜索返回 snippet + Range，目录条目返回标题、层级、目标及可用编号元数据。",
    "沿用书库/正文工具；find_book_locations 已返回版本化 Range，read_book_range 双 scope 消费同一 library 1.7 读取，正文与同分节上下文有界、支持续读。当前书剧透 fence 在目标分节加载前检查，确认参数不能自授权限；保持全局/其他书既有政策。意图级工具可组合读取，不能绕过删除批准。",
    "library 1.7 searchLocations.range/readRange 已连接 Worker 与 Text Desk 0.6，组合精确搜索、选区/句段范围详情和实际导航。DOM CFI 与 PDF 页 CFI+quote 同源校验，歧义/缺失/过期明确失败，不把原生路径交给插件。内容查询取消立即结束调用等待，底层资源仍由宿主 drain 释放；真实超过两秒的持有加载已验，无退出假成功。原文件/封面资源、持久标注身份与 Range 写入仍未完整；虚拟书受 provider 所有权约束。",
    "章节编号解析、匹配排序、导出格式、RSS 订阅属于插件算法。章节 ordinal、书上印刷编号和 sectionIndex 不能混用。缺文件重导入目前只是普通导入流程，不承诺原 ID 原子替换。",
    "不存在章节、无文本、内容版本变化、重复导入/ID 重定向、分页耗尽分别可判定；搜索命中可交给 D2 导航，不要求插件造 CFI。"),
  unit("D2", "Domain", "reading", "阅读会话、导航、模式、播放与统计", "TXT09-10 READ01-09 READ12-20 STAT01-05", "domains.reading",
    "读取 session/loading/book/location/selection/history/mode/playback 快照并观察；open、close、goTo、step、seek、back/forward；Range 选择/清除、临时强调/释放、受支持版式操作；模式启停/步进/恢复、朗读启停与状态；读完标记、已结算及 provisional 统计。业务运行态不因未持久化而变成 Service。",
    "当前 grounding 和自动计时保留；按需查询/导航/模式/朗读使用工具，经同一 reading 控制器。模型不合成阅读时长，不将 opened:true 派发回执当 ready。",
    "读、导航/呈现、持久写分清授权风险；reading 2.10 selectRange/clearSelection 先验证源、等待匹配 React 提交，清除绑定所见 id。2.11 新增临时标记查询/观察、条件更新/移除，按 Agent/插件激活代隔离并在阅读器退休时释放；不导航、不选择、不写持久标注。Text Desk 0.8 已组合，FB2/PDF 双端局部验证通过；完整组合和原生在途取消留待集中验收。Agent 命令仅回身份，会话受限时移除位置 quote，不靠导航扩大隐私/剧透权限。selectionActions 1.2 与当前句段复用来源，不给旧标注补签版本。贡献模式/声音并不授权控制用户播放。全部格式/跨平台与旧文档非空迟到仍需验收。",
    "位置恢复验证 book/contentVersion/modeKey/unitId；不把旧 ordinal 强套新分段。会话 timer 是可重置的短时 UI 状态，不是 reading_sessions_pending；不为它建立耐久调度系统。面板开关归 S3。",
    "跨书并发导航由宿主统一裁决，迟到完成不移动新会话；失败不推进历史，back/forward 不产生新分支，用户新跳转截断 forward；实际落点才算完成。模式卸载与音频 fallback 可观察。"),
  unit("D3", "Domain", "annotations", "标注、笔记和问题轨迹", "ANN01-09", "domains.annotations",
    "list/get/filter/page；创建 highlight/underline、改色、笔记 CRUD、受控删除 ask；有业务需求的批次返回原子结果或逐项结果，明确版本冲突；本地/同步写入触发一致失效。",
    "create/edit/delete_annotation、style、精确 ID/分页与条件批次已接同源原生端口；每次调用重新读，不建常驻模型观察。自动 recordAsk 是运行时内部能力，不是供模型伪造的问题写工具。",
    "annotations 2 删除五个无条件改写/删除命令，统一 applyChanges 所见版本条件提交，旧 ^1.x 明确拒绝；createNote/createHighlight 保留，ask 只能条件删除不能伪造创建。events.observe(page/inspect) 提供初始/变化/错误/恢复，读和 callback 结算后一秒重读，64 个订阅上限。Annotation Desk 0.3 实时浏览、错误清旧数据，编辑/批选仍冻结版本。原生 Notes/书籍详情、全局标注弹层和正文标记复用串行观察及所见版本删除，关闭/切书释放；原生读失败清内容/动作/计数，恢复自动重画。真实全局 Delete 已验远端先改后删冲突及重读后成功，编译插件草稿、Worker 原子批次和 Agent 批准冲突均有桌面证据。恢复/重放仍是宿主内部路径，不是公共编辑接口。全局/整书载荷、Range 和 legacy 事件远端完整性仍缺，非即时或每条事件必达。",
    "新标注默认色归 D5，不与当前对象 recolor 混合。格式化导出由查询 + 插件序列化 + S4 保存组成；不是新的 annotations.exportCSV API。",
    "无位置笔记可以保存；失效 Range 不落错误高亮；并发编辑不静默覆盖，删书后引用返回失效而非误指其他书；失败加载不是空列表。"),
  unit("D4", "Domain", "conversations", "对话内容、线程及回合意图", "AI01-03 MEM12", "domains.conversations",
    "受权读取/搜索线程、消息、摘要/insights；创建、选择、清空线程；用户触发的 draft/发送/停止/重试意图由宿主控制器执行，呈现焦点由 S3 负责。",
    "已接 get_conversation_state 双 scope、manage_conversation 全局管理与 request_conversation_turn 双 scope 草稿/发送/重试/取消建议。请求只有宿主 UI 确认后执行，不能用模型工具递归生成或停止/清空自身。书内只操作本书，请求状态与回合完成分开；重试沿用原消息/附件。",
    "conversations 1.2 已接管理、运行态观察与 requestTurn/cancelTurnRequest/turnRequests，读写分权。每个已挂载目标最多一个待确认请求，五分钟过期、关闭/退休取消；草稿不覆盖用户文本，发送/重试复核空闲和 transcript generation。只留 128 个自有可读摘要，不伪造 role 历史。stop/clear 等最后写入；定向检查通过，组合插件/Tauri E2E 待验。",
    "重试/清空聊天不撤销已完成的标注、记忆或远端 HTTP 副作用；复制聊天是查询 + 剪贴板，不需要专门 Agent 工具。书内单线程与全局多线程仍保持。",
    "停止保存已产生的部分答复；清空/切线程时旧 generation 不得回写新线程；模型回合、存储提交、展示清除的完成状态分别可验证。"),
  unit("D5", "Domain", "settings", "全部真实偏好及生效语义", "UI02 UI04-05 CFG01-13 SET01-74", "domains.settings",
    "discover/read/update/reset；返回类型、可选值、可写性、scope、effective 值、值来源、持久/漫游策略；包含 reader、general、AI、menus、shortcuts、shelf、插件非敏感字段及本次新增遗漏。修改必须映射实际消费者，或明确 unavailable。",
    "沿用 get_settings/update_settings，不为主题/字体/每个布尔字段创建模型工具。敏感配置由 S3 打开宿主设置流程，不把 key 放进提示词。",
    "自有字段与跨插件路径授权分开；动态 option 来自 C1；设置选项变化不能自动执行播放、安装、连接、付款。",
    "明确 null 是值还是 inherit；reset override 不是写默认值；all-books 不等于清覆盖。更新通道 device-local，不被漫游；面板位置/拖动坐标/最后关闭提示不是必须向 Agent 暴露的偏好。",
    "所有可写路径有生产效果消费者；六个现有无效果设置先接线或禁用。两个文本发送设置已控制 Agent 自动附件/viewport/grounding、历史附件检索及收紧时取消；LLM 1.1 结构化 readingContext 与 Dictionary 1.3 已接同一策略和本地缓存边界；任意插件 prompt/HTTP/TTS 与独立检索/旧衍生内容边界仍未闭合。buildMemory 已约束宿主记忆构建，关闭取消在途/排队任务，保留聊天与旧记忆读取；Reading Goals 实际贡献上下文和候选。localOnly 已约束宿主模型调用并取消在途请求，但不约束任意插件 HTTP/TTS/同步，仍需完整隐私边界。切字体、reset、本书覆盖、跨设备更新与失败回滚均验证实际 UI/行为。"),
  unit("D6", "Domain", "memory", "记忆、画像与书内知识的受限读模型", "MEM01-11 MEM13", "domains.memory",
    "memory 1.5 已开放 search/bookGraph/inspect、条件反馈与 classification/classify/分类观察。个人/跨书/本书记忆复用 Agent 存储检索；人物概念图共用先过滤再合并的纯查询，元数据读取失败不跳过边界。纪要提示词现共用同一策略，分类/状态/坐标变化时下一轮刷新且保留同章对话，不回收已发内容。纠错/置顶/遗忘通过正式事件与原子条件提交，Agent manage_memory 每次要求批准；后台现有记录维护同样使用模型前快照和整批条件事务，旧判断不能静默覆盖用户纠错。空闲检查读取真实版本与衰减期限，事务内回执不吞掉新增/迟到写，判断失败保留重试；仍是五分钟空闲轮询，非即时观察或耐久任务。分类纠正已接双端条件写，自动分类只填空、不覆盖新选择；图谱任务 start/get/list/cancel/retry/rebuild 与观察已接两端，按 actor 激活代隔离，共用本机队列、边界与条件写；重建保留旧行直到成功，失败目标可以重试。Agent 每次生成批准，插件另需 service:llm；每次章节尝试上限 1–1000、默认 20，重试继承或显式修改，空章/失败计数且下轮优先未尝试项。真实批准显示对象/上限，插件显示停止原因与逐章问题；token/费用预算、字段来源及内容版本仍缺。",
    "保留 search_memory/remember/query_book_graph 与自动抽取、巩固、digest；classify_book 两 scope 可查询/批准分类变更，书内仅本书，冲突需重读和重新批准，关闭自动构建不阻止手动纠正；不把内部端口函数存在计作模型工具或成熟产品入口。",
    "Memory Desk 0.6 已组合记忆读写、书库、导航和生成任务；条件反馈和分类纠正需 memory:write，额外字段与过期版本拒绝。分类详情自动观察，表单确认分类及剧透边界变化并冻结版本；该确认是插件 UX，不是宿主新授权票据。memory:read 目前授予全部记忆 scope，查询 scopes 只是过滤，不是按书授权；图谱按宿主阅读位置保护，插件不能自行声明确认剧透。events.observe 与自有 live views 已接变化/错误/恢复，表单版本冻结；更细授权仍缺；新增候选由 C4 memoryCandidateProviders 处理，现有记忆通过受控反馈管理，不能写权重、强化次数或画像投影。",
    "不拆 profile/entities/digests 成三套新域。profile/entity 事件投影仍是宿主待建；正式 context bundle 仍待建，插件现在可以组合授权读模型输出自己的格式，但不得声称宿主 bundle 产品已实现。",
    "叙事图按阅读位置在合并别名/关系前过滤，未知位置不披露；说明性/已读完书可全图，重分类后排除旧 flavor。Agent 书内仍用回合 fence/global 保留既有全图政策，并非两端所有上下文权限相同。纪要提示词与图查询现共享分类/严格已完成章节过滤，未分类默认叙事；分类/状态/坐标变化和降级重试使下一用户轮重建提示词，选区不扩大权限，同章对话保留。真实 SQLite AgentThread 脚本推理和编译 Memory Desk 已验分类切换；非已发请求撤销/历史擦除，稳定策略下成功缓存不逐轮刷新。原生 macOS debug 已验 Worker、Agent 工具、编译插件、SQLite 读故障/恢复和来源导航。chapterHref 不是版本化来源；摘要内容版本、细粒度授权、完整格式及跨平台仍缺。画像与 bundle 单列，不成为 Jumper 的前置条件。"),
  unit("C1", "Contribution", "actions/options", "动作、命令与动态选项", "UI03-05 EXT01-02 MORE04-05 CFG09", "contributions.selectionActions contributions.headerActions contributions.commands contributions.settingsOptions",
    "插件声明 action/command ID、位置、参数、标题、可见/可用/checked 条件与默认键位；宿主组合菜单/快捷键/命令面板；动态设置选项提供候选而非替用户修改值。现有 header shelf/reader 保留，确有宿主插槽的上下文菜单按位置参数扩展。",
    "模型调用受 schema/权限约束的语义命令，不是菜单 label；18 个命令由 list_host_commands/execute_host_command 双 scope、插件 commands.list/execute 与原生命令面板共用服务。UI 1.6 新增授权快照观察，覆盖工作区、已提交 shelf 设置和语言，串行合并/错误恢复/释放；Library Desk 0.6 实时 checked/可用性和稳定搜索，资源选择冻结点击时 revision。Agent 查询读取同源状态，不新增常驻模型观察。设置已保存但导航失败返回 partial，开书等 ready 不清无关覆盖层；原生等待/禁重/Escape/旧帧隔离与迟到 begin 已修复。领域设置失败由 caller 呈现，旧 void 写保留全局提示，SQL 故障复测不再双 toast。目标级完整 availability、导入、跨插件、其余原生入口/焦点/打包跨平台仍缺；插件命令给模型使用需 C4 显式贡献工具或宿主明确适配。",
    "Jumper 0.2 用 reader headerActions 与 observeSession 组合前后跳可用性。commands/headerActions/selectionActions 1.1 的注册句柄 updateState 更新完整 visible/enabled/checked 快照，旧句柄不能改同名新注册。声明无额外 permission 不代表动作能绕过它调用的领域权限。",
    "不为每个菜单再建 contribution family；命令 broker 仅解析已注册类型化描述，禁止任意字符串反射到 host 函数。静态注册与实时 enablement 分开。",
    "禁用/撤权后命令不可执行；菜单状态随 session 刷新；键位冲突可诊断；插件卸载不留下快捷键或悬挂 UI 回调。"),
  unit("C2", "Contribution", "contentProviders/readerModes", "内容与阅读算法提供者", "LIB12-14 READ15-16 EXT10", "contributions.contentProviders contributions.readerModes",
    "content provider 提供插件拥有的虚拟书内容/版本；reader mode 提供已支持 text-unit-navigator 分段策略。宿主负责阅读、版本切换、模式状态和资源引用。",
    "经 library/reading 工具消费结果，不要求模型注册算法或直接读 provider 内部数据。",
    "RSS 和 sentence-reader 保持插件业务；刷新当前内容应有版本失效和落点处理。跨插件消费有真实需要时通过受权类型化 provider broker，不直接访问其他插件 storage。",
    "不是任意格式解码器、HTML/DOM 注入或全新阅读器渲染器；OCR、新格式、新阅读交互原语属于宿主能力更新。",
    "provider 失效、disable、内容变更返回明确 unavailable/stale；旧回调不覆盖新版本；模式恢复必须验证引用仍适用。"),
  unit("C3", "Contribution", "voiceProviders", "声音与合成提供者", "READ17-18", "contributions.voiceProviders",
    "列出 provider/voice、能力与可用性；接受有界文本并产出可消费音频及格式元数据；宿主 reading 控制播放/预取/系统回退和取消。",
    "选择声音可用 settings，开始/停止必须 reading 命令；不能把设置成功当作已经出声。",
    "实现 vendor HTTP、voice 映射与合成；凭据通过隔离 secrets；音频资源归任务/会话所有，不泄露跨插件资产。",
    "不新增独立播放服务与 reading.playback 争夺同一会话；不要求音频编辑器、任意设备控制或后台常驻播放器。",
    "取消/换书/停用 provider 后不再播放迟到音频；回退状态与当前声音可读，费用/请求取消边界明确。"),
  unit("C4", "Contribution", "agent extensions", "工具、上下文、检索与记忆候选", "AI04-05 AI08-12 MEM02-03 EXT09-10 MORE05-06", "contributions.agentTools contributions.agentContextProviders contributions.agentRetrievalProviders contributions.memoryCandidateProviders",
    "工具显式声明 scope/schema/风险；上下文每轮有界注入；检索按需返回有来源片段；记忆候选由宿主去重/政策裁决。四个通道保留不同语义和生命周期，不合并成万能 agent.invoke。",
    "只有插件 installed + enabled + scope/grant/availability 满足时才消费。agentTools 1.1 按当前 visible/enabled 过滤两 scope 的工具集合；AgentThread 每次模型请求前刷新工具与检索定义，不丢弃章节会话。已发出请求保留原定义，缓存工具和检索执行前复核精确注册，旧调用不能转交同名新实现。此接线不是所有宿主内置 Agent 工具的统一 enablement；脚本推理真实 Worker 验收不是自主远端模型验收。上下文与候选没有插件实例不等于宿主 API 未实现。",
    "Dictionary 已有 3 工具 + 1 检索；RSS 有 3 global 工具；其他源插件没有直接操作工具。删除词/CSV/退订/OPML 可以在插件补工具，不要求宿主新增词汇/RSS 领域。",
    "输出不成为高优先级指令；不得通过 plugin tool 规避 host 批准/剧透规则；不能把自有私有数据自动变成所有插件可见。",
    "跨 scope 不暴露工具；输入/输出有界，失败不悬挂整轮；撤权和停用失效；检索引用可追踪，候选无条件入记忆视为失败。"),
  unit("C5", "Contribution", "themes/fonts/syncTransports", "静态资产与密文传输扩展", "EXT08 SYS14 OPS02 OPS04", "contributions.themes contributions.fonts contributions.syncTransports",
    "themes/fonts 由 manifest 声明、宿主加载验证并供 settings 选择；syncTransports 提供密文连接/session 操作，宿主掌管加解密、ACK、游标、重试与同步调度。三者共用贡献生命周期，不共用业务控制器。",
    "主题/字体用 settings；同步用 S9 控制面或用户流程，不把 transport 当控制整套同步的工具。",
    "不要求给静态 manifest 贡献补 ctx.register；transport 必须有 session.close/dispose，持有连接随 owner 释放。",
    "不开放解密 key/事件 ACK 写/字体目录。WebDAV 在源码中但不在 Rust BUNDLED；源仓、编译内置、市场分发、安装、启用、工具可用是六种不同状态。",
    "主题/字体失效可降级；transport 重连/换配置/卸载关闭旧 session；只传密文，不绕过宿主数据合并。"),
  unit("S1", "Service", "storage", "插件私有数据与持久边界", "SYS01-03 SYS05 MORE07", "services.storage",
    "隔离 KV 镜像 + durable ack/flush；文档 collection CRUD、有界查询、所需索引/分页；按业务需要提供版本条件写或批次。迁移 storage-only，quiesce→drain→snapshot→migrate→activate，失败恢复不能覆盖此前已确认的合法写。",
    "无通用私有 KV/文档工具；通过相应插件工具消费，权限不会因调用方是模型而扩大。",
    "按 plugin ID 隔离；KV、docs、secrets、blob 各自标注本地/漫游/备份/卸载保留政策；书籍索引并不自动意味着随书删除。",
    "不是插件业务 schema 搬到宿主，也不是开放 SQL/transaction handle；取消不回滚已持久写。自有二进制数据引用由 S4，密钥由 S2。",
    "GAP01–03 的更新时序、持久确认、镜像失败回滚通过故障注入；保存失败不能成功 toast；大数据导出不要求一次把全部内容装进 Worker。"),
  unit("S2", "Service", "secrets", "隔离凭据", "SYS04 CFG07", "services.secrets",
    "plugin-owned secret get/set/remove；敏感设置 UI 由宿主管理；提供 configured 状态而非向普通 settings/catalog 返回明文。",
    "不读密钥，不把 key 交给模型；配置意图打开用户流程。",
    "仅本插件 namespace，凭据值不得经日志/工具输出/诊断泄露；撤权后失去访问。",
    "现有插件为了自有 HTTP 可读其 secret；目标不强制新增通用凭据代理/OAuth SDK。宿主 AI key、同步解密 key、其他插件 key 永不因服务授权泄露。",
    "跨 namespace/日志脱敏/移除后缓存处理验证；密钥保存与插件非敏感偏好分开报告持久结果。"),
  unit("S3", "Service", "ui / maintenance", "语义导航、视图与宿主管理流程", "UI01-03 READ10-11 EXT03-07 SYS12 SYS15-17 OPS06-10 CFG07-08 AI04-05 MORE05", "services.ui services.maintenance",
    "语义页面/集合/面板导航、焦点恢复、用户选择集快照；插件自有视图 push/pop/replace/close/refresh、错误/进度呈现；打开指定宿主流程（AI 配置/账号/账单/备份/诊断/更新/数据清除）并返回取消/完成或受限状态。外部 URL 有 scheme/目的约束。",
    "意图工具可请求宿主流程，用户完成批准；查询数据、改变屏幕、确认破坏性行为是三个不同步骤。get_software_update 已接双 scope 本地状态及按需 release feed 检查；open_maintenance_settings 打开并定位 updates/diagnostics 宿主控件，不代表安装、导出或发送已完成。",
    "不拿 DOM/Router/Jotai/原生窗口句柄；自画确认按钮不能铸造 host approval。maintenance 1.0 snapshot/observe/openSettings 内置可用，checkForUpdates 需 service:network；与原生 UI 共用更新状态和互斥锁，频道变化使旧检查失效。安装/重启与诊断内容留在宿主，任务最终回执未接。可请求安全窗口意图，关闭前等待宿主持久屏障。",
    "不为每个设置页新增域；不公开拖动坐标/任意窗口/静默重启/付款。管理流程是有类型的有限集合，不是绕过领域命令的万能 dispatch。当前禁用 Reveal 不计已实现。",
    "关闭视图释放 callback/任务并恢复焦点；过期结果不打开旧弹窗；失败用 InlineError/安全 toast，不能伪装空结果；账号删除、本地 wipe、卸载各自确认且不串用。"),
  unit("S4", "Service", "resources（目标新增）", "文件、书籍资产与私有二进制资源", "LIB08-09 TXT11-12 SYS09-11 SYS13 MORE07", "",
    "用户选择 FileRef、读取授权资源元数据/范围/块、创建私有临时写入、commit/abort/release、保存到用户选择位置；Book/封面/图像的业务解析由 D1，资源服务只处理授权字节。现有 ui.exportFile 语义迁移到这里，不长期维护两套保存协议。",
    "读写文件必须有来源和用户意图，不接受模型猜出的任意路径；资源呈现与下载不必把 bytes 输入模型。",
    "ResourceRef 绑定 owner/scope/type/size/有效期；包内资产只读，自有写入按配额；大书使用有界块及回压，小文本可保留便利调用。",
    "真实需求来自已有书文件、图片、字体和 TTS 音频，不是新增万能 filesystem；无需对每个短字符串强制建流，也不提供任意 watch 目录。",
    "用户取消选择/保存与失败区分；越界读取/跨插件 ref/撤权拒绝；未提交写 abort；丢失 worker 自动释放；不能伪造路径逃逸。"),
  unit("S5", "Service", "network", "有界 HTTP", "SYS06-07", "services.network",
    "保留 Request 的 method/headers/body/响应 status/headers/bytes；取消、超时、大小/并发限制、授权目的地与重定向检查；重试说明幂等性，离线明确报告。",
    "宿主推理/插件工具可使用，但不因此添加无限制 fetch 模型工具。",
    "RSS/TTS/WebDAV 不各自重写跨 Worker HTTP 桥；协议、认证、业务缓存仍在插件，提供者 HTTP 不变成宿主 RSS 业务。",
    "不建设 WebSocket/TCP/通用离线耐久队列来修复现有 HTTP；中止请求不保证服务端没处理，更不等于撤销已付费操作。",
    "GAP04/05：Request 对象与 url+init 等价；预先 abort 不派发；途中 abort 到达 host fetch；流和重定向不能绕过额度/权限。"),
  unit("S6", "Service", "llm", "受预算约束的独立推理", "AI06-07 CFG08", "services.llm",
    "fast/smart 文本、结构化、流式输出；task scope、timeout/abort、可获得的 usage/终止原因；请求前校验模型能力和授权预算。",
    "thread 与自动管线复用推理设施，但 host prompt/审批/记忆业务仍由 Agent runtime 拥有。",
    "llm.ask 仅独立推理；返回结构符合声明 schema，流结束/错误可判定；不能读实际 key 或默认继承用户全部聊天/记忆。",
    "未提供用量的 vendor 返回 unknown，不编造成本；不为此新增本地模型、向量库或第二个 Agent。",
    "超时/停用/取消后不回写新视图；schema 错误明确失败；预算拒绝在请求前发生，停止不能宣称远端绝无费用。"),
  unit("S7", "Service", "clipboard", "受权复制", "SYS08-09", "services.clipboard",
    "文本写入；宿主已有图像复制通过授权 ImageRef 写入；操作失败用稳定错误，用户取消不等于复制成功。",
    "默认由用户按钮触发；确有对话意图才适配工具，不为每种内容增加复制工具。",
    "文本复制已接通；图像复制尚未接入插件；不自动读取系统剪贴板。",
    "不因为复制聊天/标注就建 conversations.copy/annotations.copy API；组合既有读能力与 clipboard 即可。",
    "不支持格式、失效图像引用、系统写入失败可判定；无输入的后台剪贴板轮询不属于本次范围。"),
  unit("S8", "Service", "schedules", "运行期间的可管理调度", "MORE01-02", "services.schedules",
    "现有 manifest schedules/bind：补枚举、自有计划状态/暂停/恢复、上次触发与成功/失败、重入策略和 owner 清理；空闲任务按宿主资源策略执行。",
    "全局 Agent 已接 list_plugin_schedules 与逐次批准的 manage_plugin_schedule pause/resume/run，只作用于当前已绑定声明计划，不创建代码或 OS job。书内不增加全局自动化管理工具。",
    "schedules 1.1 已接自有 list/observe/control；暂停和最新开始/结束/成功/错误记录持久保存，已发回调不随 pause 撤销；手动 run 可越过暂停/间隔一次但不恢复自动运行。同 key 跨绑定不重叠，退休后不再派发或写迟到结果，已派发记录写参与生命周期排空。15 分钟下限、首次 5 秒/每分钟扫描保留，错过多次合并一轮，不承诺精确时刻；旧 lastRun 仅迁移为开始时间。schedule-state/runs 不再漫游。定向检查通过，组合和 Tauri 验收待集中进行。",
    "关 App 不运行；不承诺 OS 常驻、恰好一次、任意 cron 分布式执行。短时 timer 不持久化是合法设计；业务反馈循环需 origin/深度或显式限流。",
    "长任务不重入、停用清理、失败不标成功；错过触发如何补跑有可复现行为。重启恢复仅对明确声明的计划，不恢复全部 Worker promise。"),
  unit("S9", "Service", "sync", "同步状态与用户请求", "OPS01-07", "services.sync",
    "受限状态：连接阶段、积压/错误、上次成功、本地可用性；用户意图 connect/disconnect/requestSync 由宿主 scheduler 执行，密文 transport 仍由 C5 提供。",
    "已接 get_sync_status 双 scope 状态/积压和按需远端套餐用量；manage_sync 经批准立即同步或打开 Data & Sync 页面。不操纵游标/ACK/密钥；打开页面不是连接、退出、购买或删除账号已完成。定向流程回执仍待接。",
    "services.sync 1.0 需独立 service:sync，提供 snapshot/observe/backlog/account/requestSync/openSettings。transport/network 不隐式获权；投影不含 email/accountId、blobKey、密钥、ticket、游标或书架选择。连接换代/管理进行中不交付旧结果；已派发共享同步不随调用者取消而回滚。定向检查通过，组合与桌面验收待集中进行。",
    "不把 checkpoint/replay/事件账本操作暴露为普通 API；健康修复由宿主流程。新控制面只覆盖现有真实同步行为，不建设第二套同步引擎。",
    "断开/换 transport 关闭旧会话；本地/远端应用后的 D1–D6 快照可刷新；只看本地单元测试不能宣称跨设备正确。"),
  unit("S10", "Service", "plugins", "插件可用性与受控自管理", "EXT11-12 MORE06", "services.plugins",
    "查询授权可见的插件 ID/版本/安装启用状态、贡献能力与 availability；安装/启停/升级/卸载请求交给 S3 宿主批准流程，实际事务由 host 生命周期所有。",
    "list_installed_plugins 已接双 scope 公共目录；模型按插件能力发现可调用工具，但不能静默安装新代码或授予权限。",
    "services.plugins 1.0 list/observe 已接 installed 元数据和变化，不返回私有配置/路径/密钥/原始错误，enabled 不代表健康；有界偏移分页变化需重读。跨插件调用仍只能使用注册接口和权限交集；具体提供者发现未完成。",
    "只读目录不演变成依赖求解器/插件商店后端重写；缺消费者时先补插件，不把每个贡献都开放为跨插件 RPC。",
    "源码插件与 bundled 的库存独立核对；实际 installed/enabled 需运行态证据；失效依赖、禁用 provider 不返回可用。"),
  unit("S11", "Service", "session（仅环境元数据）", "阅读状态统一归 D2", "READ07-08 MORE03", "services.session",
    "session 2.0 已删除 subscribe 及四种阅读事件；D2.reading 独占当前阅读快照/观察。环境保留 revision/runtime/platform/locale/timeZone/utcOffsetMinutes/networkHint，Listening Desk 0.7 消费离线提示；格式可用性和服务真实就绪仍缺。",
    "get_host_environment 在全局/书内查询同一快照；自动日期/语言上下文与按需查询分清，不为每个环境字段新建工具。networkHint 不是 endpoint 可达性。",
    "environment 每次刷新，observeEnvironment 立即快照后观察 revision；语言/网络/焦点事件与 30 秒时区复核，末个观察者清理监听。读当前书须 reading 授权，元数据不含阅读或账号状态。Dictionary 1.2 经 reading/library 查询当前标题，不靠未来事件推测；旧 ^1 service 契约不兼容并拒绝，不保留旁路兜底。",
    "这里不是新 session service 设计，也不是全局万能 runtime context。没有需求的设备指纹/硬件枚举不开放。",
    "读快照与订阅之间不丢更新；locale/可用性变化可刷新；撤 reading 权限后缓存/订阅不继续泄露书名与位置。"),
  unit("V1", "Schema", "views", "声明式内容、表单与交互结果", "EXT03-07 MORE05 MORE08 AI04-05", "schemas.views",
    "保留 list/detail/markdown/blocks/form 及宿主组件；补有界异步搜索/分页、loading/empty/error、可取消进度、稳定选择和资源引用。Tree/Table 仅在 TOC 层级或比较字段真实需要时补最小语义与键盘协议。",
    "工具卡/问题卡由宿主呈现；不把 PluginView 树当模型可执行 UI 代码。",
    "声明数据与事件，宿主拥有 React/布局/焦点/本地化；每个 view instance/generation 有局部 callback lease。",
    "Schema 无独立权力；onSubmit 仍走 Domain/Service。当前虚拟列表已有，不冒充仍需重建；无证据的富文本编辑器/任意 canvas/iframe 不进必补清单。",
    "长中文/英文、键盘、窄窗、空数据、失效 callback、异步结果逆序验证；搜索 debounce 不等于取消和防旧结果。"),
  unit("V2", "Schema", "settings", "字段声明而非行为授权", "CFG01-13 SET01-74", "schemas.settings",
    "类型、默认值、scope、约束、secret 标记、动态选项和条件可用性。字段存在、值能保存、效果有消费者分别验证。",
    "从受权 discover 构造工具参数，不另写全量 settings 枚举。",
    "插件设置声明自有数据，跨插件写仍需 D5 授权；隐藏字段不等于安全隔离。",
    "不为每个底层 KV 建公共字段；secret/password 不进入普通 Agent catalog。",
    "新增字段必须注册消费者/默认/范围/reset 语义；移除插件选项后的失效值可诊断。"),
  unit("V3", "Schema", "themes", "受限主题声明", "EXT08 SYS14", "schemas.themes",
    "宿主支持的 tokens/字体资产与 reader theme 声明，版本/资源有效性由 catalog 与 loader 验证。",
    "仅选择已声明主题，不注入样式或代码。",
    "提供资产和 tokens，不直接修改应用 DOM 或全局状态。",
    "新增主题内容不需改宿主；新渲染原语或未支持 token 的行为不由任意 CSS 逃生口绕过。",
    "缺字库/资产路径/插件禁用后回退可用；字号不破坏宿主交互与可访问性。"),
  unit("Q1", "Contract", "catalog/authorization", "发现、授权和来源", "CON01-02 CON09 CON11 AI04 AI09", "",
    "单一 capability catalog + 域定义派生 actor 视图；每个操作记录 owner、schema、version、scope、风险、availability、来源和消费者。授权先于副作用，对象/字段/资源范围在执行时复核。",
    "模型工具只是授权操作的意图适配器，自动管线单独记账。批准票据绑定 actor/operation/对象/有效期，不能被不同请求复用。",
    "manifest consent、运行时 grant、用户一次性批准各司其职；跨插件 broker 取权限交集，不沿调用链提升权限。",
    "不复制第二份能力 registry；不把所有内部行为都变成公开工具。当前对象级授权/metadata policy/packaged CSP 尚未全部验收。",
    "无权限、撤权、过期批准、跨 scope、恶意插件输出和真实打包 CSP 分别测；只测类型不算通过。"),
  unit("Q2", "Contract", "execution/lifecycle", "完成、取消和资源释放", "CON03-06 READ20 AI07", "",
    "短操作 Promise 直接给完成结果；长操作 request/task ID + progress + cancellation + deadline + terminal result。accepted 只表示受理，不是完成。跨 Worker envelope 有版本/类型/长度/并发界限。",
    "工具结束必须有真实业务结果；插件 worker 崩溃不让模型轮次无限等待。",
    "owner = plugin generation + view/session/task lease；停用后拒绝新调用、取消在途并清理回调/连接/临时资源；迟到 effect 在 host 提交边界再验 generation。",
    "cancel 不等于 undo/远端回滚；不强制所有任务耐久恢复。stable AppError code 复用项目错误契约，本文不发明与现有 code 冲突的第二套错误枚举。",
    "GAP06–08/10/12–14/17 的超时、callback、协议碰撞、旧结果/host effect、连接释放逐个故障注入；任务资源数回到基线。"),
  unit("Q3", "Contract", "consistency/observation", "快照、变更和业务写入", "CON07-08 OPS05 OPS11 STAT04-05 CFG10", "",
    "授权 snapshot + revision + invalidation/订阅后重读，覆盖本地、同步和外部写；持久命令在 commit_events 事务完成后确认。CAS/批次只加在会丢用户编辑或部分成功的业务操作。",
    "每轮快照可满足多数查询，不需要让模型订阅所有事件。导航历史与业务撤销不可混用。",
    "事件是状态失效/业务通知而非原始 log 重放权；异步 callback 错误必须被处理。订阅注册与快照的竞态用 revision 重读收敛。",
    "不建设通用 durable event bus/exactly-once/跨插件分布式事务；不要求每次查询带全局快照隔离。无法撤销的外部效果如实报告。",
    "远端变更、事件乱序/重复、subscribe 首次竞态、合法新写后旧失败回滚都不静默产生陈旧 UI；依旧以存储事务为持久边界。"),
  unit("Q4", "Contract", "coverage gate", "行为映射与语义回归门禁", "CON10", "",
    "新增宿主行为必须映射到 Domain/Contribution/Service + schema，并列 Agent/插件 disposition、实际消费者、失败路径和验收；库存新增/旧映射失效/来源丢失使生成检查失败。",
    "shape 测试以外还查工具参数是否被 adapter 丢失、批准是否执行、结果是否真实。",
    "测试同时覆盖注册、Worker wire、host 消费、卸载/撤权和用户入口；源码存在不等于部署/启用。",
    "本轮文档与生成器是人工审计的可追踪门禁，不会自动证明所有 React 闭包行为已经被发现；新产品行为仍需评审。",
    "本模型每条证据行/每个现有 catalog 成员/旧 129 基线均有归属；真实场景成功、失败、并发和撤权四条路径完成后才能关闭相应缺口。"),
  unit("B1", "Boundary", "future/internal", "明确排除与宿主尚未建成部分", "CON11-12 SYS18 MEM07-08 MEM13 OPS09-11", "",
    "禁止任意 SQL/FS/shell/DOM、宿主秘密、原始事件 append、伪造历史、静默付款/授权；新格式/OCR/任意编辑/实时协作/新平台在宿主能力更新时再纳入。",
    "Agent 和插件都不能用更高权限工具绕过产品策略；宿主内部投影修复不是普通模型行为。",
    "可以组合已授权读模型产生导出/插件算法，但不能把尚无的产品能力标成漏一条导出 API。",
    "画像实体投影、正式 context bundle、完整备份、Reveal 占位列为宿主建设/修复，不能为“插件完备”强迫先建设未来产品；移动端遗留 no-op 不计桌面缺口。",
    "需求评审能指出新增的宿主原语才算 host 更新；若只是编号规则、CSV 格式、HTTP 来源或主题内容，则应由已有原语组合。"),
];

export const refinements = [
  ["R1", "已接真实遗漏", "CFG11", "settings 1.2 已注册 appearance.contentTypography.* 四字段 followReader/fontFamily/fontSize/lineSpacing，独立尺寸 x-small/small/medium/large/x-large，行距 compact/comfortable/relaxed；默认 true/null/medium/comfortable。跟随全局 reader，null 为应用 sans；独立字段只在解除跟随后消费。"],
  ["R2", "已接真实遗漏", "CFG12", "settings 1.2 已注册 annotations.defaultColor，yellow/green/blue/pink，默认 yellow；宿主下一次一键标注即时读取，recolor 仍影响后续默认。不是 annotations 领域方法，不重染已有标注。"],
  ["R3", "已接真实遗漏", "CFG13", "settings 1.2 已注册 general.updateChannel，stable/beta，默认 stable，设备本地且不漫游。已有 About 面板跟随 KV 变化；只影响下一次检查，不批准升级/重启。"],
  ["R4", "细化现有契约", "READ16", "modeKey/unitId/content version 决定恢复是否合法；恢复时重解 CFI，不钳制旧 ordinal，无版本旧位置不恢复。模式私有位置不得由插件直接写 read-aware-navigator-state:*。mode sessionTimer 从零计时，不持久化是设计，不是 durable scheduler 缺口。"],
  ["R5", "拒绝重复 API", "AI03 SYS08", "聊天复制 = conversations 读取 + clipboard；retry/clear 不是业务撤销，不删除已完成的工具副作用。draft/发送仍需用户意图与回合 generation。"],
  ["R6", "拒绝虚构宿主能力", "LIB06", "ReaderWorkspace 的重新导入按钮当前调用 library.openImportPicker，不能据此要求/宣称已有原文件原子替换引擎。"],
  ["R7", "收回不必要的暴露", "READ11 MORE02", "面板开关/焦点与用户选择集可以语义化；toc/chat 像素宽度和浮动控制 x/y 由宿主布局管理，不要求每项成为 Agent 工具或 settings 字段。"],
  ["R8", "校正库存口径", "EXT11 LIB05 UI01 UI02", "当前源码有十四个第一方插件，Rust BUNDLED 编译清单有六个；WebDAV、Annotation Desk、Listening Desk、Reading Goals、Workspace Profiles、Text Desk、Library Desk、Memory Desk 不在内置清单。Memory Desk 0.6 组合 memory 1.5、书库、导航与图谱任务，查询个人/跨书/本书记忆，浏览受边界保护的章节图谱并复核来源后开书；加入有版本条件的纠错/置顶/遗忘与表单确认；0.4 新增分类详情/观察与条件纠正，Agent classify_book 每次变更经真实批准组件确认，查询观察驱动实时视图并隔离编辑草稿，Agent 用同源 manage_memory 并逐次批准；图谱查询沿用 search_memory/query_book_graph，manage_book_graph 提供逐次批准的生成任务。Library Desk 0.3 新增 UI 1.3 工作区导航、原生选择集和搜索表单；跨集合勾选经明确分组选择后显示在书架，回执等待目标组件提交，Agent get_workspace/navigate_app 双 scope 走同一服务。既有功能组合 library 1.6 批量删除、持久清理查询/安全重试和实时视图，Agent 全局 delete_books/list_book_removal_cleanup 消费同一领域；启动恢复属于宿主，不要求插件保留已删 ID。Text Desk 0.4 组合 library 1.4 本书/跨书多查询检索与片段查看、正文状态、准备/确认重建/请求取消、列表详情与明确开书；请求详情通过 UI 1.2/views 1.1 实时推送，列表仍显式刷新，任务仅属当前激活代，不宣称耐久调度或全局停止。Workspace Profiles 通过 settings 1.3 快照/原子更新组合书架与外观预设，注册双 scope 的管理工具；0.2 通过 settings 1.4 精确路径增加自身快捷键表单，批量冲突、重置与生命周期边界见 UI04。Reading Goals 0.3 还组合 reading 2.8 一致时长快照/可退订观察、UI 1.2 实时推送与 views 1.2 内联错误，支持日期切换和待结算分页；Agent 双 scope get_reading_time/get_reading_insights 消费同一领域。新增最近 7/30/365 天与全部历史趋势、日/月列表、全部历史小时分布和成就，并消费同源正式 sessionRecorded 事件更新；period 不改变小时分布口径，asOfDay 不是历史数据库快照。原有书内上下文、记忆候选和 buildMemory 消费保留；并不新增计时写权限或读取目标的专属工具。源码、编译内置与用户安装态分开枚举，以矩阵生成库存反查，不沿用旧的六源码/五内置数字。"],
  ["R9", "限制基础设施规模", "CON06-08 EXT06 MORE06", "通用耐久队列、可重放事件总线、全局事务、任意跨插件 RPC、富文本编辑器都不是当前必补；选择快照+revision、有限任务、业务批次、已声明 provider、场景所需声明 UI。"],
  ["R10", "细化设置完成语义", "CFG01 CFG10", "settings 1.6 为领域/原生/插件 KV、远端覆盖、备份合并/前缀恢复和动态目录增加授权快照观察；Agent 查询与插件共用进程 revision，Workspace Profiles 0.3 实时显示七项当前预设值。source 区分本地/远端/恢复/目录/混合，旧调用者无法归因时 origin=null；旧 settings.changed 仍只含领域命令。读取等 KV/凭据写结算，凭据只暴露配置状态；失败写不发成功，排队插件写退役前复核。64 观察者上限、串行合并、稳定错误与释放有回归。凭据现只在本地持久成功后封装发布，使用持久主密钥，回补等队列结算；远端覆盖等保存成功再通知且不回发，原生加密存储故障已有证据。不代表凭据 outbox/崩溃重放、原子账号切换、完整来源审计、CAS、同步或全部原生草稿/效果完成；CFG10 保持部分。"],
] as const;

export const evidence = [
  "apps/web/src/features/settings/lib/content-typography.ts",
  "apps/web/src/features/settings/sections/AppearancePanel.tsx",
  "apps/web/src/features/settings/hooks/useContentTypography.ts",
  "apps/web/src/features/annotations/lib/annotation-prefs.ts",
  "apps/web/src/features/reader/hooks/useReaderTextActions.ts",
  "apps/web/src/features/update/lib/update-channel.ts",
  "apps/web/src/features/settings/sections/AboutPanel.tsx",
  "apps/web/src/features/update/lib/software-update.ts",
  "apps/web/src/features/reader/lib/text-unit-mode-state.ts",
  "apps/web/src/features/reader/hooks/useTextUnitNavigator.ts",
  "apps/web/src/features/reader/hooks/useSessionTimer.ts",
  "apps/web/src/features/reader/components/TextUnitReadoutChip.tsx",
  "apps/web/src/features/reader/lib/reader-panel-layout.ts",
  "apps/web/src/features/reader/lib/reader-panel-sizes.ts",
  "apps/web/src/features/reader/state/panel-intent.ts",
  "apps/web/src/features/ai/hooks/useBookConversation.ts",
  "apps/web/src/features/ai/components/ChatMessageActions.tsx",
  "apps/web/src/App.tsx",
  "apps/desktop/src-tauri/src/plugins.rs",
];

export const scenarios = [
  ["Jumper", "D1 D2 C1 S3 V1 Q2 Q3", "已建第一方 Jumper：reader header/命令、分层目录与版本化精确搜索、共享会话/导航回执/历史。印刷章号、目录序号、标题匹配由插件区分；不存在章节不派发，歧义给候选。隔离 Tauri FB2 Worker 与实际 Agent 端口通过；WebView hidden 导致前台绘制/截图未通过，PDF、超大查询预算与逐调用取消仍未关闭。"],
  ["Dictionary", "D1 D2 C4 S1 S6 S7 V1", "查询/保存/检索已经有工具；删词/CSV 工具缺消费者，应在插件补；当前文本上下文/存储持久屏障缺口由宿主补。复制/导出失败必须可见。"],
  ["RSS/OPML", "D1 C2 C4 S1 S4 S5 S8", "订阅/刷新工具已有，退订/OPML 工具未贡献；文件选择为宿主漏接能力，OPML 解析为插件算法。正文版本更新不能把当前会话悄悄指向旧引用。"],
  ["句读与 TTS", "D2 C2 C3 D5 Q2", "reading 2.5 已共享朗读、模式快照/启停/单位配置、版本化返回、单元步进与模式提供者发现/选择；Listening Desk 组合模式表单、朗读、历史、Current passage 与上下单元。配置的书内状态/提供者偏好同批落盘，回执等待该请求精确持久结果，失败不被偏好回滚误报为 superseded；位置写在配置成功后复核 revision/key/unit。步进从 resting 继续并返回 moved/start-of-book/end-of-book，等待真实页面/分段/React 反馈与目标位置提交，不记跳转历史；返回同样等待持久完成。位置保存失败保留 db code，下一次明确操作可重试；自动朗读消费同一回执，书尾正常停止，保存失败则停止而非继续播下一段。隔离 macOS Tauri 已验跨节、慢 Worker、失败、取消、书尾及双端 SQLite 故障/恢复；空节/非线性/其他格式仍需桌面验证。模式选择通过 availableModes/selectModeKey，失效选择保留且不隐式替换，取消撤回未完成选择但不撤销所有已提交提供者偏好。旧偏好读取无副作用，迁移的新设置、书内配置和旧记录删除同批提交；不同所有者保留，删除失败两端拒绝且旧值保留。READ16 跟随和跨提供者取消补偿仍缺；release、其他系统、远端 TTS 未验。"],
  ["主题与定时主题", "D5 C5 S8 V3", "主题/字体可组合，已有 settings 足以切换；短 clock 不要求耐久工作流。新增主题无需宿主改动，缺字体时回退。"],
  ["WebDAV", "C5 S2 S5 S9 Q2", "密文传输 v2 已有 session.close、宿主会话所有权和原生请求取消；sync 1.0 已接双端状态/积压/立即同步和设置页入口，独立授权不随 transport 自动授予。定向连接流程、跨设备与升级回滚仍待接线或集中验收。"],
  ["标注批改/导出", "D3 S4 Q3", "补按 ID/分页/有需求的版本条件批次；插件组合 CSV/Markdown 格式，宿主无需对应每种导出格式。中途取消报告已完成项，不能宣称全部回滚。"],
  ["记忆与人物关系", "D6 C4 Q1", "memory 1.5 与 Memory Desk 0.6 已接检索/保护图谱及有版本条件的纠错/置顶/遗忘，Agent 共享检索与合并逻辑，双端任务控制与观察已接、失败重建目标保留；后台巩固/强化已接模型前快照与整批条件提交，空闲检查覆盖外部写/时间变化，事务回执与失败重试避免漏掉下一轮；按书授权、摘要来源版本、新事实去重/遗忘后再抽取与跨设备协调仍缺。画像投影与正式 bundle 尚未实现；候选来源和拒绝结果必须可辨，不开放原始投影写。"],
  ["设置自动化", "D5 V2 Q3", "覆盖真实偏好、默认/覆盖/设备本地策略；无效果字段先禁用或修复消费者。禁止以保存成功证明隐私开关真的有效。"],
  ["中途启用/跨设备变化", "D1 D2 D3 D4 D5 Q3", "先获取一致快照再观察或 revision 重读；本地/远端/外部写都使数据失效。无需 universal event replay，但不能漏通知后永久陈旧。"],
  ["插件升级/崩溃/撤权", "S1 S10 Q1 Q2", "quiesce/drain/snapshot/migrate/activate 与失败恢复；超时和 worker crash 结束 pending；旧 callback 与在途 host effect 不污染新代。GAP01–18 未因写文档关闭。"],
  ["账号/备份/诊断/更新", "S3 S4 S9 S10 B1", "打开有边界的宿主流程并反馈真实结果；明示现有备份并非完整快照。不得静默付款、上传日志、读取凭据或 wipe；不把占位 Reveal 算可用。"],
] as const;

/** Legacy scenario IDs stay stable; associations do not assert that tests passed. */
export const scenarioCoverage: Record<string, string[]> = Object.fromEntries([
  ["W01", "D1 D2 C1 S3 V1 Q2 Q3"], ["W02", "D2 D3 S1 Q3"],
  ["W03", "D1 S4 V1 Q2"], ["W04", "D1 D3 S4"], ["W05", "D3 V1 Q1 Q3"],
  ["W06", "D2 S4 V1"], ["W07", "D5 C5 S8"], ["W08", "D2 C1 S3"],
  ["W09", "D1 C2 S1 S5"], ["W10", "D2 C3 Q2"], ["W11", "D1 D2 S3 S6"],
  ["W12", "D6 V1 Q1"], ["W13", "D4 S3 Q2"], ["W14", "D6 S4 B1"],
  ["W15", "C5 S2 S5 S9"], ["W16", "D3 S1 S2 S5 Q2"],
  ["W17", "D5 C1 V1 V2"], ["W18", "C2 C4 S10 Q1"], ["W19", "D2 S11 Q3"],
  ["W20", "S1 S10 Q1 Q2"], ["W21", "S3 S4 B1"], ["W22", "D2 S1 S5 Q2 Q3"],
  ["W23", "S1 Q2 Q3"], ["W24", "S5 Q2"], ["W25", "C5 S3 Q2"],
  ["W26", "S10 Q1 Q2"], ["W27", "S9 Q3"], ["W28", "S3 V1 Q2"],
  ["W29", "S1 Q3"], ["W30", "Q2"], ["W31", "Q1 S11 B1"], ["W32", "Q2 Q4"],
].map(([id, owners]) => [id, owners.split(" ")]));
